### ISSUE TITLE
[feature request] expand/collaps button for the shown streams of the cannels for more clarity

### ISSUE THREAD

**Issue by MadZeh** [MrBrax/LiveStreamDVR#157]
I would like to suggest an expand/collaps button for the shown streams of the channel-list left side and the channel-overview as well for a better carity because with many channels and streams the list is getting messy.

This is not a high priority feature but it would be very nice. The more important thing is to fix the most bugs.

**Comment by MrBrax** [comment]
yeah feeling the same, if i can find a neat way to do it

**Comment by MrBrax** [comment]
https://user-images.githubusercontent.com/1517911/165990360-f8c73943-6bfb-444f-be83-ba4e01177779.mp4

i think this looks pretty neat

**Comment by MadZeh** [comment]
> i think this looks pretty neat

the animation is nice, but I think, the channel name should be the button.

**Comment by MrBrax** [comment]
![1651252193627](https://user-images.githubusercontent.com/1517911/165991291-8cd02860-29d9-4e0d-9d18-9f5e1622e3ae.png)
made it like this now, you think the name would work? i guess jumping to the streamer itself isn't that important, but showing how many vods are hidden might be useful?

**Comment by MadZeh** [comment]
I would hide the hole list and not only a few. Another suggest is to hide all but the live one. so you have the count of vods behind the channel name like now.

**Comment by MrBrax** [comment]
it got exponentially more difficult to implement, i'll add a customizable amount to show though

**Comment by MrBrax** [comment]
https://user-images.githubusercontent.com/1517911/166099941-841a93e4-1dc2-44a1-9559-af73d8af1e04.mp4

a bit more compact with this

**Comment by MadZeh** [comment]
Thumbs Up! This ist neat

**Comment by Serph91P** [comment]
> 1651310641145.mp4 
> a bit more compact with this

would this also be possible to implement in the recorded stream overview or whatever you call it.
Sou you dont have to scroll to all of them, I think this would be especially usefull for mobile.

![image](https://user-images.githubusercontent.com/8904984/166262184-455f7d04-310e-40c2-a4cc-2c857259291a.png)

**Comment by MrBrax** [comment]
> > 1651310641145.mp4
> > a bit more compact with this
> 
> would this also be possible to implement in the recorded stream overview or whatever you call it. Sou you dont have to scroll to all of them, I think this would be especially usefull for mobile.

ok feature pushed, although no non-hacky way to do a nice animation

**Comment by Serph91P** [comment]
> > > 1651310641145.mp4
> > > a bit more compact with this
> > 
> > 
> > would this also be possible to implement in the recorded stream overview or whatever you call it. Sou you dont have to scroll to all of them, I think this would be especially usefull for mobile.
> 
> ok feature pushed, although no non-hacky way to do a nice animation

looking great thanks
