### ISSUE TITLE
[feature request] Jellyfin/Kodi compatible Metadata files

### ISSUE THREAD

**Issue by MadZeh** [MrBrax/LiveStreamDVR#176]
My idea is to add a `tvshow.nfo` to the channel vod directory with for example the following content:

`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>`
`<tvshow>`
`    <title>Dhalucard</title>`
`    <originaltitle>Dhalucard</originaltitle>`
`    <showtitle>Dhalucard</showtitle>`
`    <uniqueid type="twitch">dhalucard</uniqueid>`
` </tvshow>`

and add `dhalucard_2022-04-30T11_59_09Z_39347953048.nfo` with infos out of the `dhalucard_2022-04-30T11_59_09Z_39347953048.json`

`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>`
`<episodedetails>`
`    <title>[GER 18+ / Tag 630] Rainbow Six Siege // 16' - Dead by Daylight // 18' - *Naraka Bladepoint Turnier // 20' - Switch Sports *[#Werbung]</title>`   <--- "twitch_vod_title"
`    <season>202204</season>`  <--- YYYYMM of "started_at"
`    <episode>30115909</episode>`   <--- DDHHMMSS of "started_at"
`    <uniqueid type="twitch" default="true">1471086505</uniqueid>`   <---  "twitch_vod_id"
`</episodedetails>`

Important is to escape the chars `<` with `&#60;`, `&` with `&#38;`, `>` with `&#62;`, `'` with `&#39;` and `"` with `&#34;`

With these files, the storage path could be easily added in jellyfin or Kodi and used with the Metadata in their libraries

Like the times before:

Nothing with high priority but a "nice to have"

**Comment by MrBrax** [comment]
hmm that is a pretty neat idea, i already have some other chapter formats so why not

**Comment by MrBrax** [comment]
i think season/episode numbers could be a problem since they expect regular sxe format, but metadata should probably work

**Comment by MadZeh** [comment]
I created the files manually for testing and they worked without problems on kodi and Jellyfin with allocating the "seasons" and "eposodes" like i wrote in the example metafile

**Comment by MrBrax** [comment]
i think i came up with a pretty robust idea, it now keeps track of the stream number for each channel, and i use that with the year as the season

**Comment by MadZeh** [comment]
To show what it looks like in Jellyfin with my self created meta-files
![filelist](https://user-images.githubusercontent.com/1353564/166444617-06ec9d67-ef76-47d1-b55f-5af5dcb72a4b.png)
![jellyfin_chapterview](https://user-images.githubusercontent.com/1353564/166444645-ab9a8029-26c1-464b-abe6-4dbf148e4563.png)
![jellyfin_episodeview](https://user-images.githubusercontent.com/1353564/166444658-dc7a3389-1f08-4665-a08a-69127b4520a8.png)
:

**Comment by MrBrax** [comment]
![1651577273778](https://user-images.githubusercontent.com/1517911/166445016-ca55e8c5-b421-4d84-a9b8-024b4b4a4775.png)

i can't test it that easily, but this is how the nfo files look right now

**Comment by MadZeh** [comment]
the reason why i wouldn't use only the year for the season is because it gets very confusing with the amount of episodes in one season. This is why i used a combination of year and month for it.

**Comment by MrBrax** [comment]
hmm yeah maybe, i haven't used jellyfin much, but maybe there's a way to use the airdate?

**Comment by MadZeh** [comment]
sadly I think no.

**Comment by MadZeh** [comment]
Another solution is maybe to set the showtitle to `Nymplol (2022)` and the season just to `05` for the month.

**Comment by MrBrax** [comment]
would just create a ton of shows, i made the season number the year and month, but kodi metadata just sucks to update so i couldn't test it

**Comment by MadZeh** [comment]
Jellyfin messed up as well. it just ignores the showtitle in the [episode].nfo and requires the tvshow.nfo for the showname.

**Comment by MadZeh** [comment]
The `tvshow.nfo` seems to be only created for new channels and not for existing ones. Is there any check if the file exist when a stream ends and the episode nfo is created? Can't check it till now, because none of my known streamers was live.

**Comment by MrBrax** [comment]
> The `tvshow.nfo` seems to be only created for new channels and not for existing ones. Is there any check if the file exist when a stream ends and the episode nfo is created? Can't check it till now, because none of my known streamers was live.

it's supposed to save the tvshow.nfo on every channel load, did you enable the setting in settings? because i made it disabled by default

you can reset channels in the tools section

**Comment by Serph91P** [comment]
> > The `tvshow.nfo` seems to be only created for new channels and not for existing ones. Is there any check if the file exist when a stream ends and the episode nfo is created? Can't check it till now, because none of my known streamers was live.
> 
> it's supposed to save the tvshow.nfo on every channel load, did you enable the setting in settings? because i made it disabled by default
> 
> you can reset channels in the tools section

Have the setting enabled but its not writing the file. The chapter file is being written though. Nothing really in the logs. Do I have to re add the the channel?

**Comment by MrBrax** [comment]
> > > The `tvshow.nfo` seems to be only created for new channels and not for existing ones. Is there any check if the file exist when a stream ends and the episode nfo is created? Can't check it till now, because none of my known streamers was live.
> > 
> > 
> > it's supposed to save the tvshow.nfo on every channel load, did you enable the setting in settings? because i made it disabled by default
> > you can reset channels in the tools section
> 
> Have the setting enabled but its not writing the file. The chapter file is being written though. Nothing really in the logs. Do I have to re add the the channel?

nope that should be it, seems to be generating on my end

**Comment by Serph91P** [comment]
> > > > The `tvshow.nfo` seems to be only created for new channels and not for existing ones. Is there any check if the file exist when a stream ends and the episode nfo is created? Can't check it till now, because none of my known streamers was live.
> > > 
> > > 
> > > it's supposed to save the tvshow.nfo on every channel load, did you enable the setting in settings? because i made it disabled by default
> > > you can reset channels in the tools section
> > 
> > 
> > Have the setting enabled but its not writing the file. The chapter file is being written though. Nothing really in the logs. Do I have to re add the the channel?
> 
> nope that should be it, seems to be generating on my end

Strange I don't see the files being generated.
![Screenshot_20220505-070138](https://user-images.githubusercontent.com/8904984/166866058-20333650-bddd-4e0b-ad64-fd784d53f098.png)
![Screenshot_20220505-070208](https://user-images.githubusercontent.com/8904984/166866069-1435ef3b-58c9-4fb9-a946-d19d270cacfa.png)

**Comment by MadZeh** [comment]
Since I resetted the channels, all *.nfo files were created.
The only thing is, Kodi and Jellyfin are ignoring the given thumbs tag in the `tvshow.nfo`. workaround could be to download the picture and save it named `folder.png` wich ist recognized by both, Kodi and Jellyfin.

**Comment by MrBrax** [comment]
yes the container needs to be restarted/updated/reset for them to be regenerated.

i noticed that too, probably need to make a public cache folder

**Comment by Serph91P** [comment]
> yes the container needs to be restarted/updated/reset for them to be regenerated.
> 
> i noticed that too, probably need to make a public cache folder

after teh latest update they got generated, thanks.

**Comment by MrBrax** [comment]
finally got the files downloading properly, might work now with latest push

**Comment by MadZeh** [comment]
After reset all channels and restart the container I got the .nfo files for every existing stream, but for today's captured streams no .nfo were created. Even in log isn't anything to see about the *.nfo like on restart.

**Comment by MadZeh** [comment]
Little "bug" found. Don't know why my config was resetted but suddenly all new video files were in the root of the vod directory. 
You should disable the creation of the *.nfo if no subfolders for each channel is used.

**Comment by MrBrax** [comment]
that's true, i don't know why i still have that option, it just gets so messy with every streamer in one folder
i was gonna make it so every vod got its own folder too

**Comment by Serph91P** [comment]
did some testing over the weekend. Today I imported some old json the nfo got created after a restart of the container. Only thin I notice (using Jellyfin) only the vods with the new json get a season, the old ones are gather into one season called 1
![Screenshot_20220509-113101](https://user-images.githubusercontent.com/8904984/167382343-c60aee9f-2b63-431c-b31e-3496b67e9f10.png)
But the nfo has a season set:
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<episodedetails>
	<title>Cozy Elden Ring (Deaths: 2)! - !HFWUnboxing - YouTube.com/CohhDaily - !PC - #EpicPartner Creator Code: COHH</title>
	<showtitle>CohhCarnage</showtitle>
	<uniqueid type="twitch">1418765049</uniqueid>
	<season>202203</season>
	<episode>1</episode>
	<plot>1. Cozy Elden Ring (Deaths: 2)! - !HFWUnboxing - YouTube.com/CohhDaily - !PC - #EpicPartner Creator Code: COHH (Elden Ring)
2. Cozy Elden Ring (Deaths: 4)! - !HFWUnboxing - YouTube.com/CohhDaily - !PC - #EpicPartner Creator Code: COHH (Elden Ring)
3. Cozy Elden Ring (Deaths: 5)! - !HFWUnboxing - YouTube.com/CohhDaily - !PC - #EpicPartner Creator Code: COHH (Elden Ring)
</plot>
	<runtime>141</runtime>
	<actor>
		<name>CohhCarnage</name>
		<role>Themselves</role>
	</actor>
	<tag>Elden Ring</tag>
	<premiered>2022-03-07</premiered>
	<aired>2022-03-07</aired>
	<dateadded>2022-03-07</dateadded>
	<year>2022</year>
	<studio>CohhCarnage</studio>
	<id>1418765049</id>
</episodedetails>`

**Comment by MrBrax** [comment]
bit weird yeah, haven't studied their nfo format enough to understand what's going on there unfortunately

**Comment by MrBrax** [comment]
i guess the one thing i didn't think about is that the stored episode number never resets, so when we get to 2023 or even just the next month, the number will continue from last time

**Comment by Serph91P** [comment]
> i guess the one thing i didn't think about is that the stored episode number never resets, so when we get to 2023 or even just the next month, the number will continue from last time

Another two thinks I noticed. 
-The channel picture ist bot showing for all "Series" only some get it displayed dunno why. 
-And all episodes are declared as EP1 in one season.

**Comment by MrBrax** [comment]
is the episode number different in every episode nfo file?

i thought about having the season number without the 20 prepending it, since i doubt twitch will be a thing in 78 years

**Comment by Serph91P** [comment]
> is the episode number different in every episode nfo file?
> 
> i thought about having the season number without the 20 prepending it, since i doubt twitch will be a thing in 78 years

They are different for all the files. Found A fix, seems like the info was not updated after a refresh of the metadata it is correct.
But without the 20 you would need to change something else because next year would start with 01 or?

**Comment by MrBrax** [comment]
s2201e01 (jan)
s2305e01 (may)
s2410e01 (oct)
etc etc

**Comment by MrBrax** [comment]
no season name change yet, but i made the episode number editable under the show advanced expando on vods
