### ISSUE TITLE
Invalid VOD JSON version

### ISSUE THREAD

**Issue by condor125** [MrBrax/LiveStreamDVR#189]
Is it possible to convert the json of old vods so they reappear in the vod list?

**Comment by MrBrax** [comment]
not without a lot of work, you can try diffing an old and new one, the one thing that stops it is the `version` field but there's a lot of differences

**Comment by Serph91P** [comment]
> i used another method of trying to migrate the json and it does work now, but you need to make all logins lowercase and change the segments names in the new json

what do you mean by that? In the json I found those two: 
"broadcaster_user_login":"cohhcarnage","broadcaster_user_name":"CohhCarnage"

and what are the segnet names?

**Comment by MrBrax** [comment]
> > i used another method of trying to migrate the json and it does work now, but you need to make all logins lowercase and change the segments names in the new json
> 
> what do you mean by that? In the json I found those two: "broadcaster_user_login":"cohhcarnage","broadcaster_user_name":"CohhCarnage"
> 
> and what are the segmet names?

the segment names are still kind of a pain to fix if the username isn't all lowercase, but if you enable the environment variable at the bottom of the readme it should migrate old jsons now

**Comment by Serph91P** [comment]
Oh that's just great thank you again for your great work. Only thing I noticed. The nfo files are not being generated. But els working like a charm.

**Comment by MrBrax** [comment]
> Oh that's just great thank you again for your great work. Only thing I noticed. The nfo files are not being generated. But els working like a charm.

for the videos or the channel? is the option enabled?
it will only generate a missing nfo file on server start

**Comment by Serph91P** [comment]
For the video. I already restartet the server for it to convert the json. Maybe have to restart again?

**Comment by MrBrax** [comment]
> For the video. I already restartet the server for it to convert the json. Maybe have to restart again?

it should display any errors if the nfo creation didn't happen, not sure what else otherwise

**Comment by Serph91P** [comment]
> > For the video. I already restartet the server for it to convert the json. Maybe have to restart again?
> 
> it should display any errors if the nfo creation didn't happen, not sure what else otherwise

Another restart helped they got created.
