### ISSUE TITLE
Doesn't recognize when stream goes live, but force recording works fine

### ISSUE THREAD

**Issue by rrweller** [MrBrax/LiveStreamDVR#194]
I am having an issue where it doesn't automatically record when the stream goes live, but if I go and click force record then it finds the stream and records fine. Looking in the logs, there aren't any errors around the time the stream began. In fact there is nothing until I manually start the recording

[2022-05-09.log](https://github.com/MrBrax/TwitchAutomator/files/8655745/2022-05-09.log)

**Comment by MrBrax** [comment]
seems like your subscriptions don't apply, check your external app url

**Comment by rrweller** [comment]
Do I need to be subscribed to the channel for it to auto record, or am I misunderstanding what you mean by subscriptions? Also dumb question, but what exactly do I need for the external app url? I was having trouble finding information on what it needs to be.

**Comment by MrBrax** [comment]
Not the payment related subscription, no.

![1652185898224](https://user-images.githubusercontent.com/1517911/167628912-a52c3638-3a7c-4f2c-8ef7-05d6956a4e4a.png)

This, under the settings. The help text should explain it. You can validate it with the button below the save button.

**Comment by MrBrax** [comment]
It needs to be the publically accessible URL of your webserver, using a domain name with https (let's encrypt works)
