### ISSUE TITLE
collapse vods default

### ISSUE THREAD

**Issue by dabenzel** [MrBrax/LiveStreamDVR#200]
would be good, if you can add a setting that all vods are collapsed on site load.

thanks

**Comment by MrBrax** [comment]
you mean the ones in the main body and not the menu?

**Comment by dabenzel** [comment]
yep, the ones on the dashboard right side "Recorded VODs"

**Comment by MrBrax** [comment]
There's an option "Minimize VODs by default" in client settings, should work

**Comment by dabenzel** [comment]
Perfect, didn't have seen it. Was always in "Config"
