### ISSUE TITLE
Burning .chatdump chat not working

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/LiveStreamDVR#201]
Hello!

I am using LiveStreamDVR trough a docker container on Unraid. 

After you solved issue: #177 (Thank you :D) I'm luckily able to download the live chat. But now I encounter the problem where I'm not able to use the .chatdump for burning. 

In this example I downloaded a VOD of an streamer which doesn't save his VOD's:
![image](https://user-images.githubusercontent.com/84481241/168476812-549748a3-36ee-4a7e-a7e3-979b765c3f3f.png)

These are all the created files including the .chatdump files:
![image](https://user-images.githubusercontent.com/84481241/168476854-863d2c93-47c2-4c87-ba18-6cdbe7899a3a.png)

Now I would love to burn in the chat with the .chatdump file because I'm not able to download the chat after the VOD has been recorded. When reading the render menu within LiveStreamDVR I would think it would be possible even tho the offset could be a little bit off:
![image](https://user-images.githubusercontent.com/84481241/168476788-a9cb20a2-7d79-40f8-8dda-d625747961e7.png)

These are the options I am trying:
![image](https://user-images.githubusercontent.com/84481241/168476903-8e613168-255b-4658-919a-a15be99dee9e.png)

When executing I get the following:
![image](https://user-images.githubusercontent.com/84481241/168476946-e9959da5-e3f7-4d39-9c02-99c149fcebca.png)
![image](https://user-images.githubusercontent.com/84481241/168476969-4accd061-c491-4f1b-aaa7-13753c6e3a67.png)

Other (maybe) useful logs:
[tdrender_lekkerspelen_2022-05-14T22_45_23Z_39404180808_stderr.log](https://github.com/MrBrax/LiveStreamDVR/files/8695115/tdrender_lekkerspelen_2022-05-14T22_45_23Z_39404180808_stderr.log)
[tdrender_lekkerspelen_2022-05-14T22_45_23Z_39404180808_stdout.log](https://github.com/MrBrax/LiveStreamDVR/files/8695116/tdrender_lekkerspelen_2022-05-14T22_45_23Z_39404180808_stdout.log)
[2022-05-15.log](https://github.com/MrBrax/LiveStreamDVR/files/8695117/2022-05-15.log)

Maybe I'm totally mistaken by the fact you can render/burn chat with a .chatdump file. Would love tho know :)

**Comment by MrBrax** [comment]
It's quite odd, because the function that errors (TimestampToSeconds) in TwitchDownloader is never used in the program, quite difficult to debug.

**Comment by MrBrax** [comment]
found the issue, if you're able to open and edit the chatdump file, the seconds in the duration needs to be trimmed down to a whole rounded number

![1652627481742](https://user-images.githubusercontent.com/1517911/168479965-ce8321cf-42a8-4299-b6a2-c4c0ea710319.png)

i pushed a fix but it won't apply to already captured dumps
