### ISSUE TITLE
Option to "drop" chapters less than 60 seconds

### ISSUE THREAD

**Issue by MadZeh** [MrBrax/LiveStreamDVR#203]
Just a little comfort thing.
2 of my captured streamers are changing the game and a few seconds later the title or vice versa. This leads to unnecessary chapters.
Perhaps you can add an option to "drop" these short chapters just before the \*.ts is converted to the \*.mp4/\*.mkv/\*.mov. Maybe even with the option to set the min length of the chapters
![Screenshot 2022-05-17 215903](https://user-images.githubusercontent.com/1353564/168900762-7ad62c56-66dc-4de8-adef-e1ae7ff738ad.png)
.

**Comment by MrBrax** [comment]
pushed the feature, untested as always ;)

**Comment by MrBrax** [comment]
what it won't do is merge the two games and titles into one, not sure how i'd make the logic for that

**Comment by MadZeh** [comment]
I'll test it. thx for the work you doing!

**Comment by MadZeh** [comment]
The duration of the last chapter of a stream wasn't recognized correct and were deleted regardless of the duration.

**Comment by MadZeh** [comment]
I set the min duration to 90 Seconds and every stream since the option was set has a missing last chapter independent of their real duration:
![Screenshot 2022-05-20 173115](https://user-images.githubusercontent.com/1353564/169562878-7355ed50-c8a3-4cb2-998e-82910ea13571.png)

Stream of "Dhalucard" and shown data on twitchtracker.com:
- 18.05.
![Screenshot 2022-05-20 172928](https://user-images.githubusercontent.com/1353564/169562977-e3d946d8-9477-41cf-87fd-4380d640411d.png)
![Screenshot 2022-05-20 172828](https://user-images.githubusercontent.com/1353564/169563068-916f980d-94ee-4da4-bfa4-9bd16c1545a7.png)

- 19.05.
![Screenshot 2022-05-20 172944](https://user-images.githubusercontent.com/1353564/169563138-fe9f4d6d-b26c-4c5b-af62-ee58abad7a8b.png)
![Screenshot 2022-05-20 173144](https://user-images.githubusercontent.com/1353564/169563186-6e99f320-a660-4c40-b18e-0554b82ca754.png)

Stream of "Staiy" and shown data on twitchtracker.com:
- 18.05.
![Screenshot 2022-05-20 173028](https://user-images.githubusercontent.com/1353564/169563321-925d636e-8a31-4536-abd5-094d047dc9ed.png)
![Screenshot 2022-05-20 173259](https://user-images.githubusercontent.com/1353564/169563390-61e70c9c-d8cd-408e-9d1c-1e5e25f0b50a.png)

- 19.05.
![Screenshot 2022-05-20 173043](https://user-images.githubusercontent.com/1353564/169563426-4b90a50c-7ac9-4d56-b282-bb770289177f.png)
![Screenshot 2022-05-20 173323](https://user-images.githubusercontent.com/1353564/169563446-964002c2-e9b7-4ae2-8241-5cddd7618ad8.png)

While capture was running, the chapters were shown correctly

**Comment by MadZeh** [comment]
Maybe the duration of the last chapter isn't calculated correctly because there no chapter end time given and the result is n/a or (null).

**Comment by MrBrax** [comment]
it should set the end time at the end of the capture, before the chapter removal happens

i've added a few debug messages, maybe that'll help

**Comment by MadZeh** [comment]
I'll test it tomorrow. there are 2 jobs in progress already so i can't update the container.

**Comment by MrBrax** [comment]
hot module replacement would definitely be nice like the php version could

**Comment by MadZeh** [comment]
found this in the log:


`2022-05-21 11:18:31.269 28 | vodclass <SUCCESS> Saving JSON of dhalucard_2022-05-21T08_00_13Z_39427227784  (stream capture end)`
`...`
`2022-05-21 11:18:31.274 28 | vodclass <INFO> Removing chapter [GER 18+ / Tag 651] *V Rising mit Juli // 19' - K*ller in the Cabin // 21' - DBD mit der Crew *[#Werbung] with duration undefined on dhalucard_2022-05-21T08_00_13Z_39427227784` 
`...`

**duration undefined** on last chapter

`...`
`2022-05-21 11:18:33.266 28 | job <DEBUG> Check status for job capture_dhalucard_2022-05-21T08_00_13Z_39427227784`
`2022-05-21 11:18:34.307 28 | vodclass <DEBUG> Can't request duration because dhalucard_2022-05-21T08_00_13Z_39427227784 is converting!`
`2022-05-21 11:18:35.268 28 | job <DEBUG> Check status for job capture_dhalucard_2022-05-21T08_00_13Z_39427227784`
`2022-05-21 11:19:01.311 28 | vodclass <SUCCESS> Saving JSON of dhalucard_2022-05-21T08_00_13Z_39427227784  (is_converting set)`
`2022-05-21 11:19:01.315 28 | vodclass <DEBUG> Can't request duration because dhalucard_2022-05-21T08_00_13Z_39427227784 is converting!`
`2022-05-21 11:19:01.316 28 | vodclass <INFO> Saving FFMPEG chapters file for dhalucard_2022-05-21T08_00_13Z_39427227784 to /usr/local/share/twitchautomator/data/storage/vods/dhalucard/dhalucard_2022-05-21T08_00_13Z_39427227784-ffmpeg-chapters.txt`
`2022-05-21 11:19:01.318 28 | helper <INFO> Remuxing /usr/local/share/twitchautomator/data/storage/vods/dhalucard/dhalucard_2022-05-21T08_00_13Z_39427227784.ts to /usr/local/share/twitchautomator/data/storage/vods/dhalucard/dhalucard_2022-05-21T08_00_13Z_39427227784.mp4`
`2022-05-21 11:19:01.323 28 | helper <INFO> Executing /usr/bin/ffmpeg -i /usr/local/share/twitchautomator/data/storage/vods/dhalucard/dhalucard_2022-05-21T08_00_13Z_39427227784.ts -i /usr/local/share/twitchautomator/data/storage/vods/dhalucard/dhalucard_2022-05-21T08_00_13Z_39427227784-ffmpeg-chapters.txt -map_metadata 1 -c copy -bsf:a aac_adtstoasc -movflags faststart -loglevel repeat+level+verbose /usr/local/share/twitchautomator/data/storage/vods/dhalucard/dhalucard_2022-05-21T08_00_13Z_39427227784.mp4`
`2022-05-21 11:19:01.323 28 | helper <SUCCESS> Spawned process 104 for remux_dhalucard_2022-05-21T08_00_13Z_39427227784.ts`

**Comment by MrBrax** [comment]
does it say earlier when calculating chapter durations why?

**Comment by MadZeh** [comment]
I attach the log-file of today for you. Maybe you can find anything.

[2022-05-21.log](https://github.com/MrBrax/LiveStreamDVR/files/8747492/2022-05-21.log)
