### ISSUE TITLE
DE Translation File

### ISSUE THREAD

**Issue by MadZeh** [MrBrax/LiveStreamDVR#207]
[de.zip](https://github.com/MrBrax/LiveStreamDVR/files/8748237/de.zip)

**Comment by MadZeh** [comment]
found a little typo in line 50:

`    "edit": "Edititiieren",` 

should be:

`    "edit": "Editieren",`

**Comment by MrBrax** [comment]
Nice! You should be able to make pull requests though

**Comment by MadZeh** [comment]
Have made a pull request...
