### ISSUE TITLE
Error displaying subscription list

### ISSUE THREAD

**Issue by condor125** [MrBrax/LiveStreamDVR#215]
using a Twitch account that has >100 subscriptions
reinstalling LiveStreamDVR
using config.json and channels.json from an older installation

fetching subs on /about only shows 100 subscriptions, log shows >100. The subscriptions that are not shown on /about bring up error messages on /dashboard:
xxx is not subscribed to stream.online. Please check the config and subscribe.
xxx is not subscribed to stream.offline. Please check the config and subscribe.
xxx is not subscribed to channel.update. Please check the config and subscribe.
etc.

**Comment by MrBrax** [comment]
that makes sense, i think the twitch api paginates them, gonna have to make a loop
