### ISSUE TITLE
Chat capture files cleanup.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/LiveStreamDVR#222]
At the moment, when someone enables the capture of the chat of any stream, we end up with the following files:

![image](https://user-images.githubusercontent.com/14930057/170690227-7f3a04cc-9e30-4c6d-98f5-89f842b7ce1f.png)

I might be wrong but at least `.chatdump` and `.chatdump.line` should be dupes. `.chatdump.txt` seems to be the chat without all the json bullshit, plaintext messages per line.

Can we make LiveStreamDVR at least to cleanup these extra files after the stream ends? After a couple of hundreds recordings this takes up GB of space without any valid propose (in my eyes)

**Comment by MrBrax** [comment]
yeah i gotta make the chat dumper clean up, right now if it quits unexpectedly, it won't make the single json file, the .line file is invalid json with just one entry per newline for a safeguard
