### ISSUE TITLE
Delete all recordings from any streamer.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/LiveStreamDVR#227]
I might be wrong but there's no delete all recordings from a channel. Not even deleting the streamer itself from LiveStreamDVR will delete the vods.

Two suggestions:
- Add a button where someone can delete all vods from a streamer without removing the streamer from LiveStreamDVR.
- Ask if you want to delete all vods when you delete a streamer from LiveStreamDVR

**Comment by MrBrax** [comment]
should *probably* work
