### ISSUE TITLE
Force resubscribe

### ISSUE THREAD

**Issue by henrikx** [MrBrax/LiveStreamDVR#229]
When pressing subscribe on the channel settings page, even if the subscription was deleted from the "about" page, then nothing happens.

Log just says this:
```
web_1  | 2022-06-06 19:19:50.004 | helper <INFO> Skip subscription to 23161357:stream.online (lirik), in cache.
web_1  | 2022-06-06 19:19:50.005 | helper <INFO> Skip subscription to 23161357:stream.offline (lirik), in cache.
web_1  | 2022-06-06 19:19:50.005 | helper <INFO> Skip subscription to 23161357:channel.update (lirik), in cache.
```

In order to subscribe again, the keys mentioned in the log must be deleted manually in the KeyValue-page. This should be automatic whenever the subscribe button is pressed.

**Comment by MrBrax** [comment]
oh right yeah i should fix that, for the time being use the keyvalue editor in settings and delete the "23161357.sub.*" and  "23161357.substatus.*" keys

**Comment by henrikx** [comment]
This works now, but it only works after the subscriptions have been removed first.

**Comment by henrikx** [comment]
The first reason is if a subscription was removed then it should be easy to recreate it.

The second reason is that I've had it twice now that a subscription is seemingly registered, but vod recordings never start as if the call was never made from Twitch. Resubscribing fixes that issue for whatever reason. Regardless that is a different issue entirely, so since this works I'll close it. Thanks.
