### ISSUE TITLE
Chapters not aligned

### ISSUE THREAD

**Issue by henrikx** [MrBrax/LiveStreamDVR#236]
The errors in the screenshot have started accumuliating on my dashboard. I don't know what to do with this as the error message does not really suggest how to fix it. 
![image](https://user-images.githubusercontent.com/10342989/172922316-0821a836-cf34-4cee-a0b5-9930d753162c.png)

I would suggest putting these errors in the logs only as there isn't really a way for the user to fix them and the reprecussions of leaving them unfixed seem to be negligible.

**Comment by henrikx** [comment]
These are the chapters for the mentioned VODs. Not sure what to make of it.

![image1](https://user-images.githubusercontent.com/10342989/172935370-00006351-67ce-4054-91b7-dcbfad45dcdb.png)

![image2](https://user-images.githubusercontent.com/10342989/172935230-e4f79374-74bf-4597-a5e8-dd711f802b1e.png)

![image3](https://user-images.githubusercontent.com/10342989/172935133-0a1e17fb-b42a-41f4-9a08-879725fc2b8d.png)

**Comment by MrBrax** [comment]
alright for the no chapters ones that makes sense, and the rest are probably just because of the notification from twitch getting sent out late

i put the errors behind a dropdown to start with

does that first user not update their status?

**Comment by henrikx** [comment]
> does that first user not update their status?

He does have a status, but I haven't seen him change title or games between those streams.

**Comment by Serph91P** [comment]
> The errors in the screenshot have started accumuliating on my dashboard. I don't know what to do with this as the error message does not really suggest how to fix it. ![image](https://user-images.githubusercontent.com/10342989/172922316-0821a836-cf34-4cee-a0b5-9930d753162c.png)
> 
> I would suggest putting these errors in the logs only as there isn't really a way for the user to fix them and the reprecussions of leaving them unfixed seem to be negligible.

Have updated today and have now 244 of those errors. Those where not shown before. Have not set anything to delete seconds or smith.
![Screenshot_20220611-080741](https://user-images.githubusercontent.com/8904984/173175667-d44066ab-34ec-429a-ba70-7d88130d7e98.png)
![Uploading Screenshot_20220611-081041.png…]()

**Comment by MrBrax** [comment]
what's the most common error in those? i added some for having chapters start after 0 which shouldn't happen

**Comment by Serph91P** [comment]
> what's the most common error in those? i added some for having chapters start after 0 which shouldn't happen

Oh that's funny I uploaded another screen but it's not showing. Anyway here ya go: 
![Screenshot_20220611-104647](https://user-images.githubusercontent.com/8904984/173180769-9e01b7d8-2d80-4085-9197-3ef1f0424db1.png)

**Comment by Serph91P** [comment]
> what's the most common error in those? i added some for having chapters start after 0 which shouldn't happen

Just saw those are different errors sorry. Should I open another ticket for this.

**Comment by MrBrax** [comment]
alright i figured out why the end time and duration won't work, since the duration of the vod and start/end time for the twitch vod will be different, i can remove that check since it doesn't make any sense
