### ISSUE TITLE
Stream title/game change not registered 

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#247]
Just saw that the game/title change is not registered. Attached two screens one from LSDVR and one from twitch. As you can see the title and the game are different. Will attach log later when recording of another stream is ended.
![Screenshot_20220616-114843](https://user-images.githubusercontent.com/8904984/174096605-c03a52d9-5d4a-45c1-9610-fe35ef79000f.png)
![Screenshot_20220616-114849](https://user-images.githubusercontent.com/8904984/174096625-1e31f682-bb51-47e9-865a-885be53b3659.png)

**Comment by MadZeh** [comment]
But did you reset the channels or resubscribe ist, because for me the game/title-change is working

**Comment by Serph91P** [comment]
> But did you reset the channels or resubscribe them, because for me the game/title-change is working

Other channels are working fine and at some point I did the reset channel thingy never looked at this channel noticed today.

**Comment by MadZeh** [comment]
sounds for me like a subscribtion thing, because on my installation maxim's stream is working as expected

**Comment by Serph91P** [comment]
> sounds for me like a subscribtion thing, because on my installation maxim's stream is working as expected

Just resubscribed maybe this will help. What does the subscribe button on the channel settings page do?

**Comment by MrBrax** [comment]
i'm guessing it's either a subscription missing or twitch not sending it out properly, pretty hard to debug

**Comment by Serph91P** [comment]
> i'm guessing it's either a subscription missing or twitch not sending it out properly, pretty hard to debug

I guess it was subscibtion missing. Because after resubscribing it is working now. Why though I dont know. Been subscribed to this channel since the beginning.
