### ISSUE TITLE
bug/feature? Video not allowing time line scrubling in Emby

### ISSUE THREAD

**Issue by BoavaNet** [MrBrax/LiveStreamDVR#248]
After a stream video gets converted from TS to mp4,  Emby doesn't seem to want to be able to scrub the timeline and constantly goes back to the beginning of the video When attempting to skip ahead.  But if I play the video from the file format TS it works perfectly fine I can scrub the timeline and skip ahead. Not sure if this is just a video conversion that removes something, Or if it's just Emby.

**Comment by MrBrax** [comment]
any special apps you're using? i downloaded the portable server and added a few recordings, scrubbed fine in the browser at least

**Comment by BoavaNet** [comment]
Here is a video of what im talking about, let me know if you what the video file as well. but it looks like it only happens with big files https://cloud.boavanet.com/s/QLYR7TMkcd3tKjy

My setup---
Unraid on the bare metal
docker for Emby and LiveStreamDVR

**Comment by MrBrax** [comment]
could it be the mkv container?

**Comment by BoavaNet** [comment]
i've tried with mp4 as wall some thing

**Comment by MrBrax** [comment]
are there any errors in the server log or something?

**Comment by BoavaNet** [comment]
Emby log file and ffmpeg logs

https://cloud.boavanet.com/s/K5x2PybFpHJnPTe

**Comment by MrBrax** [comment]
very odd. i don't think i have high hopes of fixing this, client compatibility from ffmpeg flags isn't really my specialty :/

**Comment by BoavaNet** [comment]
it's all good im working with Emby as well to see if they find anything. thx for looking

**Comment by BoavaNet** [comment]
Is it possible to disable the conversion after the stream or downloading of VODS

**Comment by MrBrax** [comment]
added a quick untested config option for it, not sure what issues it could cause
