### ISSUE TITLE
force record via api doesn't seem to work

### ISSUE THREAD

**Issue by makiele** [MrBrax/LiveStreamDVR#256]
Hi

As I haven't exposed my server to the public internet, I use a bash script to check for livestreams going online and send a call via the LiveStreamDVR api. I did so via the command `curl http://127.0.0.1:8082/api/v0/channels/example_channel/force_record`.

This worked with version `6.1.0/0.4.0` of TwitchAutomator but stopped working after I upgraded to the latest LiveStreamDVR (0.3.4/0.9.7) version. 

Calling the api returns
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="referrer" content="no-referrer" />
    <title>LiveStreamDVR</title>
    <script type="module" crossorigin src="/assets/index.d2e1ba15.js"></script>
    <link rel="stylesheet" href="/assets/index.70c299e1.css">
  </head>
  <body>
    <div id="app"></div>

  </body>
</html>

```

Other api-calls still work perfectly fine.

any idea what I am doing wrong?

thanks for your work!

**Comment by MrBrax** [comment]
is /v1/ a typo? because the version is v0

**Comment by makiele** [comment]
yes, sorry it's a typo - I used v0 like in the documentation - but it doesn't work.

**Comment by MrBrax** [comment]
i see it now, you need to make a post request

**Comment by makiele** [comment]
well that did it - docs say "GET" which worked with the older version - but POST did the trick.

thank you very much for the help

**Comment by MrBrax** [comment]
oh yeah the docs aren't automatically generated
