### ISSUE TITLE
Improvements for stream title keywords matching

### ISSUE THREAD

**Issue by condor125** [MrBrax/LiveStreamDVR#259]
Currently the stream title is only checked for keywords at the beginning of the stream.
It would be better to check for keywords on each channel update and then start/stop the recording accordingly.

Also, an option to exclude keywords would be helpful.

**Comment by MrBrax** [comment]
yeah it's kind of an useless feature, would require some rewrites for that to work, ending stream after a title change will probably not be a thing though
