### ISSUE TITLE
Add 50p options to quality list

### ISSUE THREAD

**Issue by condor125** [MrBrax/LiveStreamDVR#262]
Some European IRL streamers stream with 50fps, it would be nice to allow 720p50 and 1080p50 in the quality list.

**Comment by MrBrax** [comment]
quality system in streamlink is really annoying, a streamer can use 1079p if they want, and i just can't add every single one without just removing the check altogether. not sure how to solve it

**Comment by MrBrax** [comment]
just removed the quality check for now
