### ISSUE TITLE
Streamlink binary not found

### ISSUE THREAD

**Issue by nikothann** [MrBrax/LiveStreamDVR#263]
After fully configuring the script, for some reason it does not see the path to Streamlink. What could be wrong? I did everything exactly following the steps. Installed with pip, but the console says "Streamlink binary not found at: /usr/bin/python3.8/streamlink"
Sorry for the dumb question, I don't know much about it..
![Screenshot_1](https://user-images.githubusercontent.com/60501473/181997032-1bda6054-d35b-481e-a98a-9b928962e190.png)

**Comment by MrBrax** [comment]
are the python bins actually in that folder? on the servers i've used and in docker also they're not in a python subfolder

**Comment by nikothann** [comment]
"whereis python" pointing to this folder

**Comment by MrBrax** [comment]
"whereis streamlink" is the one you should use, pip usually puts the binaries somewhere else

**Comment by nikothann** [comment]
command showed the path /usr/local/bin/streamlink
Should I put this in the "Python binary directory"?

**Comment by MrBrax** [comment]
you should put "/usr/local/bin/" as the directory yes

**Comment by nikothann** [comment]
It didn't work. Maybe I installed streamlink wrong?
![Screenshot_4](https://user-images.githubusercontent.com/60501473/182001824-aeb98a4b-c9c4-444c-a9d9-ab9d747f18f2.png)

**Comment by MrBrax** [comment]
the log should show something with exec and the like, what it returns. anything off when it does streamlink?

**Comment by MrBrax** [comment]
considering yt-dlp shows up, that's really odd

**Comment by nikothann** [comment]
Hmm, now it says that it is not found even in /usr/local/bin/streamlink
Any advice on how to install streamlink correctly? I'll try to reset the disk and do everything again
![Screenshot_5](https://user-images.githubusercontent.com/60501473/182002023-335a679c-ca53-44b0-84a3-0885b87cd737.png)

**Comment by MrBrax** [comment]
does running /usr/local/bin/streamlink via terminal not work? i just install everything via "pip install streamlink" etc, as long as every package uses the same toggle of the --user switch it should all work

**Comment by nikothann** [comment]
/usr/local/bin/streamlink Not a directory
Thanks anyway, I'll keep trying...

**Comment by MrBrax** [comment]
are you trying to cd or just execute it?

the server and all the other stuff can be located anywhere

**Comment by MrBrax** [comment]
what was the issue?
