### ISSUE TITLE
Capture Starts 2-4 mins later

### ISSUE THREAD

**Issue by lucas19961** [MrBrax/LiveStreamDVR#265]
The Capture Starts 2-4 Minuts latert then the stream.  Can i configure it ?

**Comment by MrBrax** [comment]
nope sorry, from the readme:

> Because of notification delays, the stream usually starts capturing after ~2 minutes after the stream goes live.

maybe if websocket support in the future sends more timely events this will be improved, but as of now it's quite delayed

**Comment by lucas19961** [comment]
Ok :) Thanks for the answer
