### ISSUE TITLE
Server Crashes at start

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#267]
Dunno if the same error(https://github.com/MrBrax/LiveStreamDVR/issues/258), but after latest update there is no frontend, the log says something about files already beeing present?
[error.txt](https://github.com/MrBrax/LiveStreamDVR/files/9276764/error.txt)

**Comment by MrBrax** [comment]
odd that the file would exist, added a handler just in case

**Comment by Serph91P** [comment]
> odd that the file would exist, added a handler just in case

hmmm actualy the server is crashing, after some time. any way to fix this?

**Comment by Serph91P** [comment]
> same exact error?

different file, rest looks the same pretty much
[error.txt](https://github.com/MrBrax/LiveStreamDVR/files/9283900/error.txt)
:

**Comment by MrBrax** [comment]
hm, i guess you don't use the develop branch? i didn't push that to master

**Comment by Serph91P** [comment]
> hm, i guess you don't use the develop branch? i didn't push that to master

Nope don't use develop, didn't think it would be necessary. Will try to change, it's just called develop even on docker?

**Comment by MrBrax** [comment]
pushed it to master, should probably be fixed. develop can be unstable
