### ISSUE TITLE
Scheduled/automated clip downloads

### ISSUE THREAD

**Issue by cr08** [MrBrax/LiveStreamDVR#271]
Low priority feature request but thought it might be useful for some. But since we already have a manual clip download function, is it possible we can have an automated/scheduled version of this? I don't know if or think the Twitch API's would allow the system to be notified when a clip is created. But an alternative may be a simple timed check? Say every 24h (or user configurable period) go out and pull the list of clips from the channel, compare against what we already have stored and only grab what doesn't already exist? Just spitballing on functionality here.

Side-request: Adding the ability to add the associated chat log for clips? I can't find a way for tcd to do it, but I know TwitchDownloader can and confirmed the functionality exists in the CLI version. One caveat that I have not had a chance to check in the CLI version but I know happens in the GUI version of TD is clips with no chat will just show Failed so may need to have the necessary checks for this.

**Comment by MrBrax** [comment]
hooking onto when each clip is created sounds a bit spammy to me, if a channel is just fairly big, you'll be downloading thousands of clips of nothing

**Comment by MrBrax** [comment]
made one that would run once a day with some configuration options, not that fleshed out yet

**Comment by cr08** [comment]
Sorry for the delayed replies, but this is greatly appreciated! Seems to be working well so far. I'm seeing the clips stored, just nothing in the web interface (which honestly I'm perfectly ok with at the moment. No rush from me to flesh the rest of it out. 😄 ).

**Comment by MrBrax** [comment]
alright done, you think thumbnails would be useful or would that take up too much space in the list?

**Comment by MrBrax** [comment]
i think that turned out pretty decent

**Comment by cr08** [comment]
Had a lull in clips to test with but had some come through last night 😄Looks great here and works well so far. Once again, thanks for the work on this. It's greatly appreciated!

**Comment by MrBrax** [comment]
sounds good. should probably add something to change the scheduling though, maybe the raw cron text?

**Comment by CappiSteijns** [comment]
Trying to get clips downloaded with no success so far. 

Using following settings:

![SmartSelect_20221024_211213_Firefox.jpg](https://user-images.githubusercontent.com/84481241/197606770-75ccc571-fdf5-4a51-ba5e-91d0cca6b3cb.jpg)

After this it doesn't seem to do anything? Even if it would only download every ~24 hours it does not pick anything up.

Speaking of, when does it try to download the clip? The moment a new clip has been created or ever X hours?

**Comment by CappiSteijns** [comment]
> yeah it should run at 00:00 midnight every day i think, and it should output scheduler related stuff to the log, does that not happen?

Suddenly it worked! It downloaded exactly at 00:00. (As you can see in the log)
[2022-10-25.txt](https://github.com/MrBrax/LiveStreamDVR/files/9855771/2022-10-25.txt)


It does give the clips strange names tho as you can see in the pictures.
![SmartSelect_20221025_001622_Firefox.jpg](https://user-images.githubusercontent.com/84481241/197641098-fbd35117-8d48-4d24-93f5-4d0082c46bd5.jpg)

Could it be possible to download the clips as soon as they are created? It does happen streamers delete the clips as well as the whole vod.

And right now it will download the last clips from 1 day, would it be possible to download all existing clips using LiveStreamDVR? Yes, I do understand it will take a lot of gb's and most of the clips are not really usefull but I would really like to archive them all.

Thanks for your time!

**Comment by MrBrax** [comment]
> as soon as they are created?

nope, no such webhook

> download all existing clips

technically possible i guess, but you'd probably get banned from the api for downloading tens of thousands of clips

**Comment by MrBrax** [comment]
clips also cannot be sorted by anything other than view count as far as i know, so it is what it is

**Comment by CappiSteijns** [comment]
> the names are just the official clip id's, i made them use the template name now
> 
> > as soon as they are created?
> 
> nope, no such webhook
> 
> > download all existing clips
> 
> technically possible i guess, but you'd probably get banned from the api for downloading tens of thousands of clips

Thanks for the help and info, seems to be working! :)
