### ISSUE TITLE
need help to setup

### ISSUE THREAD

**Issue by aerox845** [MrBrax/LiveStreamDVR#274]
hello everyone i seem to not be able to get it running propably but would love to have it running.

i use unraid and installed it as docker - also installed SWAG docker to try get reverse proxy setup with duckdns but i simply dont get it up running always get External URL is invalid: External app url 'https://****.duckdns.org/api/v0/hook' responded with an unexpected response:  (status: 0)

sure there is some setup wrong. also i dont know what to put into "base path" at basic options.

![2022-08-21 16_10_59-Settings - LiveStreamDVR](https://user-images.githubusercontent.com/20801290/185795184-9743b8eb-1cd3-4b7c-8c58-35cec612c6b8.png)
?
is there anywhere a full guide somwhere
yes i put in twitch secret etc just blanked it out in the screenshot hmm maybe its a problem cause swag has different IP then the docker from livestreamDVR?

**Comment by aerox845** [comment]
okay know i got it as far as that my proxy is running but it complains its got invalid response cause it is pointing towards the swag start landing page hmm

**Comment by MrBrax** [comment]
is duckdns running a reverse proxy? otherwise you need one on your own host that points to the docker container

**Comment by Serph91P** [comment]
> okay know i got it as far as that my proxy is running but it complains its got invalid response cause it is pointing towards the swag start landing page hmm

you will need to setup swag to use a subdomain. For example livestream.duckdns.org. to do this you will need to setup a config to tell swag what to do when someone comes from said domain or more like to which application or ip to point it to. But this also includes that you have a subdomain setup at duckdns. I think its better explained here (https://docs.linuxserver.io/general/swag#reverse-proxy) If you need ruther help, dont hesitate to ask. I have quite an extensive setup with SWAG.

**Comment by aerox845** [comment]
thanks for the help by testing i also found out that i didnt have anything setup in that SWAG stuff - then i fooled around with docker container and docker compose but i cant really get it setup and running.

i found some config file on reddit which made me play around with docker compose to get SWAG and LiveStreamDVR Docker running in the same network then i could ping from the swag docker to the LivestreamDVR by using"twichtautomator" as dns name but when i try to acces it from web i get 502bad gateway which tells me that my config/the reddit config file didnt help me.

now i m back without docker compose there i can ping from SWAG console to livestreamDVR successfully  by ip (172.17.0.2 ) 

so yeah i think all is in the pointin SWAG to the right ip/url needed but i have a hard time figureing it out

**Comment by aerox845** [comment]
i got it up and running - sorry for the hassle :) i m stupid haha

**Comment by Serph91P** [comment]
> i got it up and running - sorry for the hassle :) i m stupid haha

if you need furhter help maybe those two videos will help. Those are the best channels to go about unraid.
https://www.youtube.com/watch?v=N7FlsvhpVGE
https://www.youtube.com/watch?v=I0lhZc25Sro

Regards
