### ISSUE TITLE
Server Crashing again after channel live?

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#275]
Here is the latest log where errors occure I guess.

> h0llylp_2022-04-26T14_58_47Z_39332389944 is not yet remuxed but no ts file found, skipping!
> 2022-08-23 16:19:28.187 | vodclass <WARNING> Loaded VOD h0llylp_2022-04-26T14_58_47Z_39332389944 is not finalized!
> 2022-08-23 16:19:28.272 | vodclass <ERROR> No chapters on h0llylp_2022-08-16T14_12_31Z_45929855068!
> h0llylp_2022-08-16T14_12_31Z_45929855068 is not yet remuxed, remuxing now!
> Converted file '/usr/local/share/twitchautomator/data/storage/vods/h0llylp/h0llylp_2022-08-16T14_12_31Z_45929855068.mp4' for 'h0llylp_2022-08-16T14_12_31Z_45929855068' already exists, skipping remux!
> 2022-08-23 16:19:28.274 | vodclass <WARNING> Loaded VOD h0llylp_2022-08-16T14_12_31Z_45929855068 is not finalized!
> 2022-08-23 16:19:28.275 | config <SUCCESS> Loaded channel h0llylp with 47 vods
> 2022-08-23 16:19:28.276 | channel <SUCCESS> Loaded 8 channels!
> 37.209.38.162 - admin [23/Aug/2022:14:19:28 +0000] "POST /api/v0/tools/reset_channels HTTP/1.1" 200 43 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
> 37.209.38.162 - admin [23/Aug/2022:14:19:34 +0000] "GET /tools HTTP/1.1" 200 485 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
> 37.209.38.162 - admin [23/Aug/2022:14:19:34 +0000] "GET /api/v0/settings HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
> 37.209.38.162 - admin [23/Aug/2022:14:19:35 +0000] "GET /api/v0/channels HTTP/1.1" 200 951123 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
> 37.209.38.162 - admin [23/Aug/2022:14:19:35 +0000] "GET /api/v0/jobs HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
> JSON from 172.18.0.1: { action: 'helloworld' }
> 2022-08-23 16:46:11.208 | hook <INFO> Hook called
> 2022-08-23 16:46:11.210 | automator <INFO> Channel update for h0llylp
> Notifying clients: Live non-capturing channel h0llylp changed status: Just Chatting (!gow Letzter Stream vor der Gamescom! (Bis Sonntag) / Der September wird abgefahren | @H0llyLP), category offlineStatusChange
> 54.184.54.118 - - [23/Aug/2022:14:46:11 +0000] "POST /api/v0/hook HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
> 2022-08-23 16:46:11.213 | automator <INFO> Channel h0llylp not capturing, saving channel data to cache: Just Chatting (!gow Letzter Stream vor der Gamescom! (Bis Sonntag) / Der September wird abgefahren | @H0llyLP)
> 2022-08-23 16:46:11.214 | automator <INFO> Channel h0llylp status is online but not capturing, starting capture from chapter update.
> 2022-08-23 16:46:11.216 | vodclass <INFO> Create VOD JSON for h0llylp: h0llylp_2022-08-16T14_12_31Z_45929855068.json @ /usr/local/share/twitchautomator/data/storage/vods/h0llylp
> 2022-08-23 16:46:11.217 | vodclass <SUCCESS> Saving JSON of h0llylp_2022-08-16T14_12_31Z_45929855068  (create json)
> 2022-08-23 16:46:11.219 | vodclass <ERROR> No chapters on h0llylp_2022-08-16T14_12_31Z_45929855068!
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MrBrax** [comment]
did it end just like that? no stack trace or exit message?

**Comment by Serph91P** [comment]
> did it end just like that? no stack trace or exit message?

Yep, have something running called uptime Kuma which checks/pings a specified address. I get a message if something is down. The log i attached is the most recent one.

**Comment by MrBrax** [comment]
is that the console log? because exceptions don't appear in those, i need the running one

**Comment by Serph91P** [comment]
> 
[error_log.txt](https://github.com/MrBrax/LiveStreamDVR/files/9414626/error_log.txt)


Attached the log you requested I think :D

**Comment by MrBrax** [comment]
did you not visit the site at all? it should be outputting pageview info...
doesn't seem like anything crashed, unless there's that auto updater that just kills the container that's been discussed earlier

**Comment by Serph91P** [comment]
of i visit the site. But then after cloudflare said host not rechable i checked the console log where it say what I wrot in the first post.

**Comment by MrBrax** [comment]
![1661336198721](https://user-images.githubusercontent.com/1517911/186393816-033e9da3-369e-4018-a694-a2e2dbb7f4e3.png)

this is how the console log looks, the complete lack of log lines without the date in the start tells me it's the wrong one

**Comment by Serph91P** [comment]
> ![1661336198721](https://user-images.githubusercontent.com/1517911/186393816-033e9da3-369e-4018-a694-a2e2dbb7f4e3.png)
> 
> this is how the console log looks, the complete lack of log lines without the date in the start tells me it's the wrong one

lets try this again :D
[error-log.txt](https://github.com/MrBrax/LiveStreamDVR/files/9415201/error-log.txt)

**Comment by MrBrax** [comment]
nope, still not right. are you copying it from the log files themselves?
```
Initialising...
Environment: undefined
Running as user undefined
``` 
this is the first output in the console when you start it

**Comment by Serph91P** [comment]
> 

ok lets ask different, where should I look for the log because this is all I know about.

**Comment by MrBrax** [comment]
the console/terminal where the program is running

**Comment by Serph91P** [comment]
> the console/terminal where the program is running

that was the first thing I posted just after the crash.

**Comment by MrBrax** [comment]
you must have missed the last text then, because there's no stack trace

**Comment by Serph91P** [comment]
> you must have missed the last text then, because there's no stack trace

sorry but this is the last there is 

> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

the only thing after is press any key to close the console from unraid.

**Comment by MrBrax** [comment]
gotta be something related to docker then? i think that text only appears if you mistype the run command when starting it manually

**Comment by Serph91P** [comment]
> gotta be something related to docker then? i think that text only appears if you mistype the run command when starting it manually

hmmm, mistype not possible since unraid ui. you baiscally press start and it starts. Dunno about Docker. Will keep an close eye when it happens again.

**Comment by MrBrax** [comment]
you're sure it's not the auto updating thing?

**Comment by Serph91P** [comment]
> you're sure it's not the auto updating thing?

Thats turned off even if it was on it would run at night and LSDVR crashed in the middle of the day.

**Comment by MrBrax** [comment]
i might have gotten something similar this morning, the node process didn't exit but just froze, very odd.

**Comment by Serph91P** [comment]
> i might have gotten something similar this morning, the node process didn't exit but just froze, very odd.

Could also have been my internet connection. Had problems the last couple of days. Now it's fixed. Let's hope it's working again. Btw love the new update.
