### ISSUE TITLE
Streams constantly declared live

### ISSUE THREAD

**Issue by makiele** [MrBrax/LiveStreamDVR#276]
Hi again!

As you may (or may not) remember from my last issue, I haven't exposed LiveStreamDVR to the public internet and therfore force recording via bash script.

After a power-outage, my docker container updated to the latest image, going from version` 0.3.4/0.9.7` to `0.4.2/1.0.0`. Apart from having to delete the logs folder to get the container to start, another issues, albeit only cosmetic, has arisen.

Most of my channels are displayed as "live" even though they are offline. Even channels that are captured constantly will change from "live capturing" to "live" after the stream has ended.

In contrast, channels that have zero recorded vods in my LiveStreamDVR do not appear as "live".

In the example below, only the captured stream is really live, the two other streams are actually offline.
 
Any idea what changed in between the versions mentioned above? Any chance to have them show offline even without me being subscribed to events?
 
 thank you again for your awesome work!
![grafik](https://user-images.githubusercontent.com/62406247/186783682-a03f221d-cc1f-455f-9e7a-b33a46cd1215.png)

**Comment by MrBrax** [comment]
that makes sense, there's now a separate "live" and "capturing" status, one is for the actual channel status via event hooks and the other is the local recording. if you start recording manually, it doesn't know when the channel goes offline. gonna have to come up with a solution to that
