### ISSUE TITLE
(Feature request) rename old vods

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#279]
Love the naming scheme implemented, like how easy it is. Where you can go like login}_{season}_{episode}. And even clickable presets and stuff. Great work.
Only thing I wish there was you could rename all the old vods the same fashion after you changed it. Also would help I hope with importing in Plex. So at least the seasons are getting registered correctly because Plex cannot read the nfo files generated for kodi or at least not anymore. Because at it is right now Plex goes like. Season is 2022 and so on see: https://support.plex.tv/articles/200265256-naming-home-series-media/ .Just something for you to think about.

**Comment by Serph91P** [comment]
Oh forgot to ask what do you mean by `Vod filename. This will break automatic segment finding if changed from default.

Default: {login}_{date}_{id}`?

Won't it just not be able to ad them to the nfo or something or won't it be able to find them at all.

**Comment by Serph91P** [comment]
What would be even better would be to implement the metadata into the files dunno if that's possible.
See Plex wiki:

> Personal Media Shows: The Personal Media Shows agent is used to identify media files that haven’t been broadcast and so don’t appear in online databases. Shows scanned using this agent will be presented like a TV series. This is useful if you have a set of videos from a single event, like a wedding. If Local Media Assets is enabled for the agent, any embedded metadata in the files will be used for that show.

**Comment by MrBrax** [comment]
plex is kind of a pain. regular metadata is already written to the files, can't seem to find a season field for it though
> Oh forgot to ask what do you mean by `Vod filename. This will break automatic segment finding if changed from default.

in a worst case scenario if the segment list is empty, it won't be able to find the mp4 files because of a different naming scheme. not really a problem anymore since you can edit the segment list manually in the gui

**Comment by Serph91P** [comment]
> plex is kind of a pain. regular metadata is already written to the files, can't seem to find a season field for it though
> 
> > Oh forgot to ask what do you mean by `Vod filename. This will break automatic segment finding if changed from default.
> 
> in a worst case scenario if the segment list is empty, it won't be able to find the mp4 files because of a different naming scheme. not really a problem anymore since you can edit the segment list manually in the gui

Found this on Reddit. Plex itself doesn't really seem to want to disclose this information. So the naming scheme would need to be "name of series s01ep01" or something. https://www.reddit.com/r/PleX/comments/rt8pdk/plex_wont_read_metadata_from_my_own_mp4_files/hqrhmf7

**Comment by Serph91P** [comment]
Or what also could help folder for seasons. Could to this myself but would be gorgeous if lsdvr would do it. I know it would be a bigger change with folder.

**Comment by Serph91P** [comment]
https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/

**Comment by MrBrax** [comment]
i had ideas about having subfolders for vods, but that's probably gonna take some time. gonna need some database over the vods too

**Comment by MrBrax** [comment]
ok so this feature might just break everything, but as a first start the subfolders seem to be working

**Comment by MrBrax** [comment]
yeah well sometimes when i'm out and about i get ideas in my head :)

it should be able to find all existing files and work as normal, but that only happens if there's no database file for the channel in the config folder, so no way to manually call a refresh. if you make subfolders for them, delete the database file for the channel and restart the server it should pick them up

**Comment by Serph91P** [comment]
> yeah well sometimes when i'm out and about i get ideas in my head :)
> 
> it should be able to find all existing files and work as normal, but that only happens if there's no database file for the channel in the config folder, so no way to manually call a refresh. if you make subfolders for them, delete the database file for the channel and restart the server it should pick them up

What does the db file look like or where is it. Because just updated and everything is working so far. But dont see any db file of some sorts. Will try later to sort them in Folder. Also what is the naming you intended to use or make it modular like filenames?

**Comment by MrBrax** [comment]
database files are stored in /data/config/vods_db/*.json

naming for vod folders is the same as the filename right now, will most likely make it the same with templates

**Comment by Serph91P** [comment]
> database files are stored in /data/config/vods_db/*.json
> 
> naming for vod folders is the same as the filename right now, will most likely make it the same with templates

so every stream gets his own subfolder?

**Comment by MrBrax** [comment]
yes, i think that's good for organizing

**Comment by Serph91P** [comment]
> yes, i think that's good for organizing. can be disabled of course

got it, question wouldnt it make more sense in terms of medeia server to make season folder like put every stream of june in the folder 202206 or something?

**Comment by MrBrax** [comment]
i don't think it would break if you did that honestly, you could just use {season} as the folder name and it would put every stream for that month in there. added the functionality on latest build

**Comment by Serph91P** [comment]
> i don't think it would break if you did that honestly, you could just use {season} as the folder name and it would put every stream for that month in there. added the functionality on latest build

but the season is 2022 so it would put every stream of the year in there no?
![image](https://user-images.githubusercontent.com/8904984/188102024-333483f1-03e9-42cb-a914-95d75769b5e9.png)

**Comment by MrBrax** [comment]
yeah you're right, i could add some more variables to use

**Comment by Serph91P** [comment]
> yeah you're right, i could add some more variables to use

Your making every Media Server user happy right now :)

**Comment by MrBrax** [comment]
any suggestions for more fields? could be anything from the user or at the point of starting the stream

**Comment by MrBrax** [comment]
fields like {season} and {date} etc

i'm adding year/month/date as separate ones

**Comment by Serph91P** [comment]
> fields like {season} and {date} etc
> 
> i'm adding year/month/date as separate ones

I dont think from my point there is anything that makes sense to add.

**Comment by Serph91P** [comment]
> fields like {season} and {date} etc
> 
> i'm adding year/month/date as separate ones

There is something broken herem just tried season and this is what came out :D
![image](https://user-images.githubusercontent.com/8904984/188105088-ec71e162-84a9-45e3-93f8-6d260417e529.png)

**Comment by MrBrax** [comment]
is that in a manual stream record?

**Comment by Serph91P** [comment]
> is that in a manual stream record?

yeah

**Comment by MrBrax** [comment]
alright, pushing changes. changing the folder names is not implemented yet, but you could just rename them yourself and use the new "rescan vods" in the streamer header. should work without leaving vods in memory now hopefully

**Comment by MrBrax** [comment]
yup typo

**Comment by Serph91P** [comment]
ok that did not work. 
moved now everything is season specific folders. Plex no liky. Looks almost like its getting it from somwhere else. Because after that I tried just Season 03 and so on an still:
![image](https://user-images.githubusercontent.com/8904984/188176187-3a7af5b2-bd09-4462-bb7a-6fb017709a3b.png)

**Comment by MrBrax** [comment]
https://forums.plex.tv/t/the-plex-dance/197064 done this?

**Comment by MrBrax** [comment]
also, plex does support daily format just by date, maybe that could be something? i think it should split if there's multiple per day

**Comment by Serph91P** [comment]
> https://forums.plex.tv/t/the-plex-dance/197064 done this?

dunno where the error is, because i completely deleted the Library and added it again. The Menus shown there arnt even present anymore.

**Comment by Serph91P** [comment]
![image](https://user-images.githubusercontent.com/8904984/188181269-6f6e1e3e-df79-4568-b500-5ce52a64568b.png)
![image](https://user-images.githubusercontent.com/8904984/188181907-09c47ed8-394f-47c5-a409-eea69c9daa4d.png)

**Comment by MrBrax** [comment]
what if you use regular dates like "username (2022-08-28)-01.mp4"

**Comment by Serph91P** [comment]
> what if you use regular dates like "username (2022-08-28)-01.mp4"

Nope, will test tomorrow again. Make an extra direcotry where I can test things safely. Just renamed wrong files :D

**Comment by Serph91P** [comment]
> what if you use regular dates like "username (2022-08-28)-01.mp4"

OK got it, gonne need some changes I think to ask for.
Thats how it looks atm:
![image](https://user-images.githubusercontent.com/8904984/188264376-0c9bd95f-e3c0-4641-8dfd-352d6f532dfc.png)
![image](https://user-images.githubusercontent.com/8904984/188264386-7a910166-6c9c-48e0-bd2b-d9f6c7142bd7.png)
![image](https://user-images.githubusercontent.com/8904984/188264405-1a9d1c85-5fbb-4464-ad00-87add5680da9.png)

Only Problem there is now I think is that episode and month which I need to get the naming on point are written without a preceding 0 until it has two numbers like 10 and so on. 
![image](https://user-images.githubusercontent.com/8904984/188264489-5b236d6f-f1f9-4b80-b9a4-f875a5397aa8.png)

Then the year is left dunno about this because the season would start at 01 again but the year will change.
Like streamername (2023) - S01E01 and so on. Dunno what to do about that because the month will start again obv next year.
You could change Season for episode to be continous this would work.

**Comment by MrBrax** [comment]
i thought about adding the last two digits of the year, like 20/21/22/23 and so on, so the season number would at least be a bit shorter like "2209"

**Comment by Serph91P** [comment]
> i thought about adding the last two digits of the year, like 20/21/22/23 and so on, so the season number would at least be a bit shorter like "2209"

I can try if plex will eat it like this, because 202209 works for the season. Because the plex documentation says it has to be in this pattern for episodes 

> /Band of Brothers (2001)/Season 01/Band of Brothers (2001) - s01e01 - Currahee.mkv

**Comment by MrBrax** [comment]
i think it's pretty much a losing battle with how little control you get, i added the short year to the most recent one but it feels like an endless endeavor

**Comment by Serph91P** [comment]
> i think it's pretty much a losing battle with how little control you get, i added the short year to the most recent one but it feels like an endless endeavor

yeah I hate plex for losing plugin support, there was one where you could use the kodi nfo stuff. Will Have to rename everything myself then.

**Comment by MrBrax** [comment]
is there a perfect naming scheme for this that's achievable? i feel like there are too many obstacles for it

**Comment by Serph91P** [comment]
> is there a perfect naming scheme for this that's achievable? i feel like there are too many obstacles for it.. maybe a counting season number for every month that doesn't take the month number into consideration?

yeah there is:
streamername (year) - s01e01
Where your season statement ist just incrementing numbers while month change maybe and episode ist just incrementing while a season is running I guess dunno how easy to make. Maybe I sit down with my Mentor (learning web dev right now) do to this.

**Comment by MrBrax** [comment]
oh so you mean having a separate show for each streamer year? because plex only cares about one or the other naming scheme i think

**Comment by Serph91P** [comment]
> oh so you mean having a separate show for each streamer year? because plex only cares about one or the other naming scheme i think

hmmm. 
streamername (year) is fine. the part about S09E11 is crucial. Because if this isnt right the episode get scrambeled up.
![image](https://user-images.githubusercontent.com/8904984/188265919-9353e8c0-dce9-4f43-ada5-ef45bbf9bf68.png)
the year gets ignored. The folder name (Season202207) is the part that is important and S07E01 need to match.
![image](https://user-images.githubusercontent.com/8904984/188265959-f9527c00-6ae3-44b3-8aac-13bc76b89dcc.png)

**Comment by MrBrax** [comment]
yes, year will never matter on an episode basis if there's a season/episode naming scheme. it's one or the other really.

**Comment by Serph91P** [comment]
> yes, year will never matter on an episode basis if there's a season/episode naming scheme. it's one or the other really.

So it would need to:

2022
- Season 01
  - streamername (2022) - s01e01
  - streamername (2022) - s01e02
  - ...
- Season02
  - streamername (2022) - s01e01
  - streamername (2022) - s01e02
  - ...

2023

- Season13
  - streamername (2023) - s13e01
  - streamername (2023) - s13e02

**Comment by MrBrax** [comment]
yes and that would create a different show entry in plex for every streamer+year. technically possible to have template based channel folders but they're very hardcoded right now

**Comment by Serph91P** [comment]
> yes and that would create a different show entry in plex for every streamer+year. technically possible to have template based channel folders but they're very hardcoded right now

You think? because I have atm one Season with 2022 and one with Season2023 and it ignores it completely the only thing that seems to matter is the Season. Sorry dont quite get what you mean.
![image](https://user-images.githubusercontent.com/8904984/188266231-d612c5d5-dcf3-4c4a-9235-5334421ad405.png)
![image](https://user-images.githubusercontent.com/8904984/188266237-8e6bef3e-bdf1-4b45-8763-e6872f203355.png)

**Comment by MrBrax** [comment]
the only thing that will matter with the years is if you make folders like "gronkh (2022)" and "gronkh (2023)" and place the respective years into those

**Comment by Serph91P** [comment]
ok

**Comment by Serph91P** [comment]
Plex sucks so much when it comes to files. I'd like to switch, but I've invested too much time in other themes that I don't want to switch without losing hours. I mean if there is a folder called 202209 but the file inside is named wrong it is not recognized at all. As soon as you rename the file to the correct format it finds the file immediately. I mean the file has not really been wrongly named only something was not there, the season.

**Comment by MrBrax** [comment]
`/login/Season 202209/login - s202209e05.mp4` should work, but it could just be that plex doesn't support seasons that high.

a last resort could be just having a videos library and browse by folder, that's what i do with misc videos

**Comment by Serph91P** [comment]
> `/login/Season 202209/login - s202209e05.mp4` should work, but it could just be that plex doesn't support seasons that high.
> 
> a last resort could be just having a videos library and browse by folder, that's what i do with misc videos

Yeah thats what I do atm aswell but it sucks to navigate it with a remote I think aspecialy if you have so many streams like I have. But yeah.

**Comment by Serph91P** [comment]
> `/login/Season 202209/login - s202209e05.mp4` should work, but it could just be that plex doesn't support seasons that high.
> 
> a last resort could be just having a videos library and browse by folder, that's what i do with misc videos

that actually worked:
![image](https://user-images.githubusercontent.com/8904984/188268141-24fc6fc8-8f75-44da-9c4f-4daf46ebaffa.png)

**Comment by MrBrax** [comment]
the padding you mean? did i forget that? because the episode numbers should work for each month

**Comment by Serph91P** [comment]
> the padding you mean? did i forget that? because the episode numbers should work for each month

Looks like it this streamer went live after the update. 
![Screenshot_20220903-172421](https://user-images.githubusercontent.com/8904984/188277411-9b9eed6f-23c3-4a89-a851-3c47953073c1.png)

**Comment by MrBrax** [comment]
you mean all three of them are supposed to be capturing?
i updated my server and everything seems to be recording fine so far

**Comment by Serph91P** [comment]
> you mean all three of them are supposed to be capturing? i updated my server and everything seems to be recording fine so far

No the last one should be named e04 but it's only 4

**Comment by MrBrax** [comment]
simple padding oversight, added absolute season numbering too, unsure if it will work at all though

**Comment by Serph91P** [comment]
> simple padding oversight, added absolute season numbering too, unsure if it will work at all though

looks like its working:
![image](https://user-images.githubusercontent.com/8904984/188415098-79d2fb3c-64b9-481d-8b08-26cdcd125e7d.png)

**Comment by Serph91P** [comment]
Video Download uses old naming pattern and the streams are not sorted by date.
![image](https://user-images.githubusercontent.com/8904984/188629848-52a43faf-b48c-4ee4-8f77-af1ed620c476.png)

**Comment by MrBrax** [comment]
> > simple padding oversight, added absolute season numbering too, unsure if it will work at all though
> 
> The old files I have renamed are beeing recognized. But not completely, the file is said to be deleted. ![image](https://user-images.githubusercontent.com/8904984/188628678-0c8a6cde-100e-4c37-994f-b7615d0fed85.png) Tried to delete the db file an restarted + Scan for vods. Still deleted

if you hover over the segment and check the url, does it make sense to the one on disk?

**Comment by MrBrax** [comment]
> Video Download uses old naming pattern and the streams are not sorted by date. ![image](https://user-images.githubusercontent.com/8904984/188629848-52a43faf-b48c-4ee4-8f77-af1ed620c476.png)

hadn't really planned out the downloader stuff, the episode number wouldn't work with those

**Comment by Serph91P** [comment]
> > > simple padding oversight, added absolute season numbering too, unsure if it will work at all though
> > 
> > 
> > The old files I have renamed are beeing recognized. But not completely, the file is said to be deleted. ![image](https://user-images.githubusercontent.com/8904984/188628678-0c8a6cde-100e-4c37-994f-b7615d0fed85.png) Tried to delete the db file an restarted + Scan for vods. Still deleted
> 
> if you hover over the segment and check the url, does it make sense to the one on disk?

Nope is the same as it says already.

**Comment by MrBrax** [comment]
> > > > simple padding oversight, added absolute season numbering too, unsure if it will work at all though
> > > 
> > > 
> > > The old files I have renamed are beeing recognized. But not completely, the file is said to be deleted. ![image](https://user-images.githubusercontent.com/8904984/188628678-0c8a6cde-100e-4c37-994f-b7615d0fed85.png) Tried to delete the db file an restarted + Scan for vods. Still deleted
> > 
> > 
> > if you hover over the segment and check the url, does it make sense to the one on disk?
> 
> Nope is the same as it says already.

does the link work? what i'm saying is does the path look the same as it does in the storage, no missing folder?

**Comment by Serph91P** [comment]
> > > > > simple padding oversight, added absolute season numbering too, unsure if it will work at all though
> > > > 
> > > > 
> > > > The old files I have renamed are beeing recognized. But not completely, the file is said to be deleted. ![image](https://user-images.githubusercontent.com/8904984/188628678-0c8a6cde-100e-4c37-994f-b7615d0fed85.png) Tried to delete the db file an restarted + Scan for vods. Still deleted
> > > 
> > > 
> > > if you hover over the segment and check the url, does it make sense to the one on disk?
> > 
> > 
> > Nope is the same as it says already.
> 
> does the link work? what i'm saying is does the path look the same as it does in the storage, no missing folder?

Sadly no. I guess it has to to with that the files is named completly different from what the dashboard shows.
![image](https://user-images.githubusercontent.com/8904984/188702206-ef113820-7eb7-4897-88fb-0c165dd68393.png)
![image](https://user-images.githubusercontent.com/8904984/188702445-307e826a-142e-49c2-9c4c-dc8373edd3a5.png)

**Comment by MrBrax** [comment]
in that case you can expand advanced on the vod and edit the segments

**Comment by Serph91P** [comment]
> in that case you can expand advanced on the vod and edit the segments

that worked.

**Comment by MrBrax** [comment]
it should now be sorting by started_at date instead of name
