### ISSUE TITLE
Add Support For Personal OAuth Tokens

### ISSUE THREAD

**Issue by tony-rsrv** [MrBrax/LiveStreamDVR#280]
StreamLink allows you to pass a personal OAuth Token which provides you a stream without ads if you are subscribed to the channel. I think this would be a great addition to this project as well.

**Comment by MrBrax** [comment]
would this be better implemented as a text file in the config directory or a config option? i feel like with that token you'd compromise the entire account if stolen?

**Comment by tony-rsrv** [comment]
It's up to your discretion. I don't mind how it's implemented.

**Comment by MrBrax** [comment]
ok so now with a `twitch_oauth.txt` file in the config folder containing only the token it... might work? no idea with the spaces in the argument which might break it
