### ISSUE TITLE
[Feature suggestion] Stream schedule guesstimator

### ISSUE THREAD

**Issue by TicTac9k1** [MrBrax/LiveStreamDVR#281]
People switch up their streaming times from time to time for various reasons or do not have a streaming schedule necessarily and stream whenever. It would be helpful to keep track which days at which hours the tracked channels based on previous streams.

I understand it's kind of out of scope for the project, but I think this could be be a useful addition.

**Comment by MrBrax** [comment]
it could be possible as it already stores the history of previous streams and chapters
