### ISSUE TITLE
[Feature Request] Collaps all Streams

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#283]
Could you do the same in the main view like you did in the sidebar where you could kinda collapse the whole thing and press a button and all streams appear again. Because for me with about "1000" streams it gets kinda confusing and you have to scroll through everything.

**Comment by MrBrax** [comment]
hmm it's pretty cramped with space for buttons, mostly surprised you have that many lol

**Comment by Serph91P** [comment]
> hmm it's pretty cramped with space for buttons, mostly surprised you have that many lol

Yeah I know am quite the data horder. and it's not so many but enough to make the UI quite big and stuff. Could you do something with the already present arrow like double assignation of the function.

**Comment by MrBrax** [comment]
made "m" as a hotkey to toggle all, unless i find some other solution in the future 🤷‍♀️

**Comment by Serph91P** [comment]
> made "m" as a hotkey to toggle all, unless i find some other solution in the future woman_shrugging

I think you misunderstood or iam stupid :D
When I press m only the streams in the sidebar collapse, I meant something that collapses the streams in the overview or however you wanna call it. Then you press your hotkey ore something and they all are visible again.

![image](https://user-images.githubusercontent.com/8904984/188095513-52a18201-f6dc-4c71-b8b8-58337050457b.png)

**Comment by MrBrax** [comment]
yes the small arrow next to the other actions in the streamer header does that, only per streamer though

**Comment by Serph91P** [comment]
> yes the small arrow next to the other actions in the streamer header does that, only per streamer though

hmmm meant more like the option for the sdidebar where you can set 0.
![image](https://user-images.githubusercontent.com/8904984/188098544-2f3527a1-3188-4c67-9c49-e7c2b44ecdf1.png)
so you can "hide" them there as well you know.

**Comment by MrBrax** [comment]
oh right yeah got it

**Comment by MrBrax** [comment]
feature pushed

**Comment by Serph91P** [comment]
> feature pushed

Working like a charm
