### ISSUE TITLE
[Bug] Invalid Time value

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#287]
Had this error when stream went live:

>

>  2022-09-02 17:28:20.992 | hook <INFO> Hook called
> 
> 2022-09-02 17:28:21.029 | automator.handle <INFO> Automator channel.update event for royalphunk
> /usr/local/share/twitchautomator/server/node_modules/date-fns/format/index.js:392
>     throw new RangeError('Invalid time value');
>           ^
> 
> 
> RangeError: Invalid time value
>     at format11 (/usr/local/share/twitchautomator/server/node_modules/date-fns/format/index.js:392:11)
>     at Automator.vodBasenameTemplate (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:99:26)
>     at Automator.updateGame (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:288:31)
>     at Automator.handle (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:213:24)
>     at Hook (/usr/local/share/twitchautomator/server/src/Controllers/Hook.ts:189:32)
>     at Layer.handle (/usr/local/share/twitchautomator/server/node_modules/express/lib/router/layer.js:95:5)
>     at next (/usr/local/share/twitchautomator/server/node_modules/express/lib/router/route.js:144:13)
>     at AuthCore (/usr/local/share/twitchautomator/server/src/Helpers/Auth.ts:80:5)
>     at Layer.handle (/usr/local/share/twitchautomator/server/node_modules/express/lib/router/layer.js:95:5)
>     at next (/usr/local/share/twitchautomator/server/node_modules/express/lib/router/route.js:144:13)
> 
> Node.js v18.8.0
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MrBrax** [comment]
hmm, can't immediately see why the date is broken via tests, gonna have to update my own server

**Comment by MrBrax** [comment]
added a valid check, but the date definitely shouldn't be empty to begin with.

i think i just realised what happened. i'm guessing this is a new channel that hasn't streamed before and did a channel update, therefore never setting the start date?
also it's using the basename to update chapters, that's not good

**Comment by Serph91P** [comment]
> added a valid check, but the date definitely shouldn't be empty to begin with.
> 
> i think i just realised what happened. i'm guessing this is a new channel that hasn't streamed before and did a channel update, therefore never setting the start date? also it's using the basename to update chapters, that's not good

Newly added yes and changed the title before stream I think an then started streaming.

**Comment by MrBrax** [comment]
made it use the capture id instead, on a bigger project to replace using the vod basename for everything :/

**Comment by tony-rsrv** [comment]
Not sure if this is related, but stream went offline twice and it captured the first two streams fine but the third stream has an incorrect duration: https://i.tony.pm/c5RI9Sx.png

**Comment by MrBrax** [comment]
yeah any interruptions would start the stream again with a new name, hopefully fixed when using the capture id now
