### ISSUE TITLE
Better Error Handling or Subprocess Survivability

### ISSUE THREAD

**Issue by tony-rsrv** [MrBrax/LiveStreamDVR#288]
I had a crash happen due to the time bug while two other streamers were live. This caused the entire program to crash and not record the other two streamers. Would love each stream to be handled independently so crashes because of one stream doesn't cause all streams to crash.

**Comment by MrBrax** [comment]
develop branch is unstable as it's the live code i'm working on. i think the only thing that would solve all errors is to put the entire program in an error handler, which is not a good idea. best course of actions is probably to do a feature freeze and just bug fix until it's stable enough to release
