### ISSUE TITLE
[Bug] video download crashes on some streams

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#291]
Its a vod thats 40min long and it just crashed on these files dunno whats wrong with them:
https://www.twitch.tv/videos/1576885257

> 

> /usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:2907
>             throw new Error(`VOD ${vod.basename} is already in cache!`);
>                   ^
> 
> 
> Error: VOD maxim_2022-08-30T13-02-57Z_1 is already in cache!
>     at Function.addVod (/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:2907:19)
>     at Function.load (/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:2730:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at _TwitchChannel.createVOD (/usr/local/share/twitchautomator/server/src/Core/TwitchChannel.ts:446:26)
>     at DownloadVideo (/usr/local/share/twitchautomator/server/src/Controllers/Channels.ts:343:21)
> 
> Node.js v18.8.0
> error Command failed with exit code 1.
> 2022-09-06 14:02:10.478 | vod.calculateChapters <ERROR> No chapters found for maxim_2022-09-01T05-08-48Z_39774390952, can't calculate chapters
> Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"uuid":"1ff...
> 2022-09-06 14:02:13.481 | vodclass <INFO> Fetching mediainfo of maxim_2022-09-01T05-08-48Z_39774390952, segment #0
> 2022-09-06 14:02:13.482 | helper.videometadata <ERROR> Invalid mediainfo for /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-09-01T05-08-48Z_39774390952.mp4 (missing  Duration)
> 2022-09-06 14:02:13.483 | vodclass <ERROR> Could not get mediainfo of maxim_2022-09-01T05-08-48Z_39774390952 (/usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-09-01T05-08-48Z_39774390952.mp4 @ /usr/local/share/twitchautomator/data/storage/vods/maxim): Invalid mediainfo: no format/duration
> 2022-09-06 14:02:13.484 | vodclass <ERROR> Could not find duration of maxim_2022-09-01T05-08-48Z_39774390952
> Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"uuid":"1ff...
> 2022-09-06 14:02:15.470 | channel <INFO> Download VOD 1577635672
> 2022-09-06 14:02:15.760 | vodclass <INFO> Download of maxim_2022-08-31T04-57-29Z_46004791628.mp4 successful
> Broadcasting data to 1 clients: {"server":true,"action":"video_download","data":{"success":true,...
> 2022-09-06 14:02:15.761 | channel <INFO> Create VOD JSON for maxim: maxim_2022-08-31T04-57-29Z_46004791628.json @ /usr/local/share/twitchautomator/data/storage/vods/maxim
> 2022-09-06 14:02:15.762 | vodclass <SUCCESS> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628  (create json)
> 2022-09-06 14:02:15.767 | vodclass <ERROR> No chapters on maxim_2022-08-31T04-57-29Z_46004791628!
> maxim_2022-08-31T04-57-29Z_46004791628 is not yet remuxed but no ts file found, skipping!
> maxim_2022-08-31T04-57-29Z_46004791628 has an mp4 file but is not finalized!
> 2022-09-06 14:02:15.771 | vod.addSegment <INFO> Adding segment maxim_2022-08-31T04-57-29Z_46004791628.mp4 to maxim_2022-08-31T04-57-29Z_46004791628
> 2022-09-06 14:02:15.772 | vod.finalize <INFO> Finalize maxim_2022-08-31T04-57-29Z_46004791628 @ /usr/local/share/twitchautomator/data/storage/vods/maxim
> 2022-09-06 14:02:15.773 | vodclass <INFO> Fetching mediainfo of maxim_2022-08-31T04-57-29Z_46004791628, segment #0
> 2022-09-06 14:02:15.773 | helper.mediainfo <INFO> Run mediainfo on /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4
> 2022-09-06 14:02:15.780 | helper.execSimple <EXEC> Executing 'mediainfo': $ /usr/bin/mediainfo --Full --Output=JSON /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4
> 2022-09-06 14:02:15.793 | helper.execSimple <INFO> Process 54 for 'mediainfo' exited with code 0
> 2022-09-06 14:02:15.794 | helper.videometadata <ERROR> Invalid mediainfo for /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 (missing  Duration)
> 2022-09-06 14:02:15.795 | vodclass <ERROR> Could not get mediainfo of maxim_2022-08-31T04-57-29Z_46004791628 (/usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 @ /usr/local/share/twitchautomator/data/storage/vods/maxim): Invalid mediainfo: no format/duration
> 2022-09-06 14:02:15.795 | vod.finalize <ERROR> Failed to save vtt chapters for maxim_2022-08-31T04-57-29Z_46004791628: Error: TwitchVOD.saveVTTChapters: chapters are not set
> 2022-09-06 14:02:15.796 | vod.finalize <ERROR> Failed to save kodi nfo for maxim_2022-08-31T04-57-29Z_46004791628: Error: TwitchVOD.saveKodiNfo: started_at is not set
> 2022-09-06 14:02:15.797 | vod.calculateChapters <ERROR> No start time found for maxim_2022-08-31T04-57-29Z_46004791628, can't calculate chapters
> 2022-09-06 14:02:15.797 | vodclass <WARNING> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628 with no chapters!!
> 2022-09-06 14:02:15.798 | vodclass <SUCCESS> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628  (fix no segment added)
> maxim_2022-08-31T04-57-29Z_46004791628 is finalized but no ended_at found, fixing!
> 2022-09-06 14:02:15.801 | vodclass <INFO> Fetching mediainfo of maxim_2022-08-31T04-57-29Z_46004791628, segment #0
> 2022-09-06 14:02:15.803 | helper.videometadata <ERROR> Invalid mediainfo for /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 (missing  Duration)
> 2022-09-06 14:02:15.803 | vodclass <ERROR> Could not get mediainfo of maxim_2022-08-31T04-57-29Z_46004791628 (/usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 @ /usr/local/share/twitchautomator/data/storage/vods/maxim): Invalid mediainfo: no format/duration
> 2022-09-06 14:02:15.804 | vodclass <ERROR> Could not find duration of maxim_2022-08-31T04-57-29Z_46004791628
> maxim_2022-08-31T04-57-29Z_46004791628 has no duration or started_at, skipping!
> maxim_2022-08-31T04-57-29Z_46004791628 is finalized but no chapters found, fixing now!
> 2022-09-06 14:02:15.804 | vodclass <WARNING> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628 with no chapters!!
> 2022-09-06 14:02:15.805 | vodclass <SUCCESS> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628  (fix chapters)
> 2022-09-06 14:02:15.809 | channel <ERROR> Vod on disk and vod in memory are not the same for maxim
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: maxim (2022) - s202209e06, maxim (2022) - s202209e08, maxim (2022) - s202209e10, maxim (2022) - s202209e13, maxim_2022-08-30T12-49-02Z_1, maxim_2022-08-30T13-02-57Z_1, maxim_2022-09-02T05-04-09Z_39778285560, maxim_2022-09-01T05-08-48Z_39774390952, maxim_2022-08-31T04-57-29Z_46004791628, category system
> 2022-09-06 14:02:15.809 | channel <ERROR> Vod on disk and vod in main memory are not the same for maxim
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: maxim (2022) - s202209e06, maxim (2022) - s202209e08, maxim (2022) - s202209e10, maxim (2022) - s202209e13, maxim_2022-08-30T12-49-02Z_1, maxim_2022-08-30T13-02-57Z_1, maxim_2022-09-02T05-04-09Z_39778285560, maxim_2022-09-01T05-08-48Z_39774390952, maxim_2022-08-31T04-57-29Z_46004791628, category system
> 2022-09-06 14:02:15.810 | vodclass <WARNING> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628 with no chapters!!
> 2022-09-06 14:02:15.810 | vodclass <SUCCESS> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628  (manual creation)
> 2022-09-06 14:02:15.814 | vod.addSegment <INFO> Adding segment maxim_2022-08-31T04-57-29Z_46004791628.mp4 to maxim_2022-08-31T04-57-29Z_46004791628
> 2022-09-06 14:02:15.815 | vod.finalize <INFO> Finalize maxim_2022-08-31T04-57-29Z_46004791628 @ /usr/local/share/twitchautomator/data/storage/vods/maxim
> 2022-09-06 14:02:15.816 | vodclass <INFO> Fetching mediainfo of maxim_2022-08-31T04-57-29Z_46004791628, segment #0
> 2022-09-06 14:02:15.817 | helper.videometadata <ERROR> Invalid mediainfo for /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 (missing  Duration)
> 2022-09-06 14:02:15.817 | vodclass <WARNING> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628 with no chapters!!
> 2022-09-06 14:02:15.818 | vodclass <SUCCESS> Saving JSON of maxim_2022-08-31T04-57-29Z_46004791628  (manual finalize)
> 2022-09-06 14:02:15.818 | vodclass <ERROR> Could not get mediainfo of maxim_2022-08-31T04-57-29Z_46004791628 (/usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 @ /usr/local/share/twitchautomator/data/storage/vods/maxim): Invalid mediainfo: no format/duration
> 2022-09-06 14:02:15.819 | vod.finalize <ERROR> Failed to save vtt chapters for maxim_2022-08-31T04-57-29Z_46004791628: Error: TwitchVOD.saveVTTChapters: chapters are not set
> 2022-09-06 14:02:15.819 | vodclass <INFO> Saving Kodi NFO file for maxim_2022-08-31T04-57-29Z_46004791628 to /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.nfo
> 2022-09-06 14:02:15.820 | vod.finalize <ERROR> Failed to save kodi nfo for maxim_2022-08-31T04-57-29Z_46004791628: TypeError: Cannot read properties of undefined (reading 'title')
> 2022-09-06 14:02:15.820 | vod.matchProviderVod <INFO> Trying to match maxim_2022-08-31T04-57-29Z_46004791628 to provider...
> 2022-09-06 14:02:15.827 | vodclass <INFO> Fetching mediainfo of maxim_2022-08-31T04-57-29Z_46004791628, segment #0
> 2022-09-06 14:02:15.828 | helper.videometadata <ERROR> Invalid mediainfo for /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 (missing  Duration)
> 2022-09-06 14:02:15.828 | vodclass <ERROR> Could not get mediainfo of maxim_2022-08-31T04-57-29Z_46004791628 (/usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 @ /usr/local/share/twitchautomator/data/storage/vods/maxim): Invalid mediainfo: no format/duration
> 2022-09-06 14:02:15.829 | vodclass <ERROR> Could not find duration of maxim_2022-08-31T04-57-29Z_46004791628
> Broadcasting data to 1 clients: {"server":true,"action":"end_download","data":{"vod":{"uuid":"0c...
> 2022-09-06 14:02:16.105 | vod.matchProviderVod <SUCCESS> Found matching VOD for maxim_2022-08-31T04-57-29Z_46004791628
> 2022-09-06 14:02:16.105 | vod.calculateChapters <ERROR> No chapters found for maxim_2022-08-31T04-57-29Z_46004791628, can't calculate chapters
> Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"uuid":"0c6...
> 2022-09-06 14:02:19.107 | vodclass <INFO> Fetching mediainfo of maxim_2022-08-31T04-57-29Z_46004791628, segment #0
> 2022-09-06 14:02:19.108 | helper.videometadata <ERROR> Invalid mediainfo for /usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 (missing  Duration)
> 2022-09-06 14:02:19.108 | vodclass <ERROR> Could not get mediainfo of maxim_2022-08-31T04-57-29Z_46004791628 (/usr/local/share/twitchautomator/data/storage/vods/maxim/maxim_2022-08-31T04-57-29Z_46004791628.mp4 @ /usr/local/share/twitchautomator/data/storage/vods/maxim): Invalid mediainfo: no format/duration
> 2022-09-06 14:02:19.109 | vodclass <ERROR> Could not find duration of maxim_2022-08-31T04-57-29Z_46004791628
> Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"uuid":"0c6...
> 2022-09-06 14:02:22.198 | channel <INFO> Download VOD 1576885257
> 2022-09-06 14:02:22.479 | vodclass <INFO> Download of maxim_2022-08-30T13-02-57Z_1.mp4 successful
> Broadcasting data to 1 clients: {"server":true,"action":"video_download","data":{"success":true,...
> 2022-09-06 14:02:22.479 | channel <INFO> Create VOD JSON for maxim: maxim_2022-08-30T13-02-57Z_1.json @ /usr/local/share/twitchautomator/data/storage/vods/maxim
> 2022-09-06 14:02:22.480 | vodclass <SUCCESS> Saving JSON of maxim_2022-08-30T13-02-57Z_1  (create json)
> 2022-09-06 14:02:22.484 | vodclass <ERROR> No chapters on maxim_2022-08-30T13-02-57Z_1!
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MrBrax** [comment]
sounds to me like it's duplicate?

**Comment by Serph91P** [comment]
> sounds to me like it's duplicate?

Your probably right there are like 3 vods that are like this alle about the same length maybe the streamer had some errors himself. What's interesting is that you can watch it on twitch have not looked at the other ones what if they are the same.

**Comment by Serph91P** [comment]
> yeah that's what the {id} template variable would help with, unless you're using it and it's broken?

No not using it, just thinking where I could put it so Plex would still like it and don't fuck the whole season recognition up again.

**Comment by MrBrax** [comment]
you should be able to put it in square or curly brackets
