### ISSUE TITLE
VOD showing conversion still active from a week ago, no processes active and multiple restarts have not fixed

### ISSUE THREAD

**Issue by cr08** [MrBrax/LiveStreamDVR#292]
Subject TL;DR here. So far LiveStreamDVR has been working beautifully for my needs. Nothing I can really add at this point in time.

One thing I did notice though and might have been something I did is I have two VODs on the same day (Sept 1st) that are showing a conversion is still active. I've been intentionally running on the develop-ts branch and keeping that docker updated on my machine and so it has seen a number of restarts along the way but this still remains.

![image](https://user-images.githubusercontent.com/1199481/188884836-9b87e8ec-7527-4780-892c-0c8c04fe14d1.png)

Just curious if there's any easy way to kick this out of that conversion step? Mostly an annoyance at this point seeing the lone pink VODs just hanging out there in the list.

**Comment by MrBrax** [comment]
if all else fails you can edit the vod json and set `is_converting` to false and restart the server

**Comment by MrBrax** [comment]
adding a fix on develop for it
