### ISSUE TITLE
[Help] Streams are shown live

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#293]
I have multiple streamer that appear online in the overlay but aren't. I checked the Jason and none have is online set to true. Also deleted db files just to be sure. Dunno what to do here?
![Screenshot_20220907-172119](https://user-images.githubusercontent.com/8904984/188917031-934e1daa-992b-449d-a2e4-b56c0293bb54.png)

**Comment by MrBrax** [comment]
live status is set by keyvalues, if you edit those you can get it unstuck

**Comment by Serph91P** [comment]
> live status is set by keyvalues, if you edit those you can get it unstuck

OK closed thank you

**Comment by MrBrax** [comment]
made the channel refresh feature check live status now
