### ISSUE TITLE
[Bug] Stream is online before application start

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#294]
Stream is already online. Application is started after minutes it registered the stream is live and crashes:

> /usr/local/share/twitchautomator/server/src/Core/Automator.ts:467

>         const body = current_chapter.title;
>                                      ^
> 
> 
> TypeError: Cannot read properties of undefined (reading 'title')
>     at Automator.notifyChapterChange (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:467:38)
>     at Automator.updateGame (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:391:22)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.8.0
> error Command failed with exit code 1.
> 2022-09-07 18:14:20.759 | helper.getSubsList <INFO> Requesting subscriptions list
> 2022-09-07 18:14:20.759 | helper.getSubsList <INFO> Fetch subs page 0
> 2022-09-07 18:14:21.063 | helper.getSubsList <INFO> 27 subscriptions
> 2022-09-07 18:14:21.064 | helper <INFO> Subscribe to 73437396:stream.offline (bonjwa)
> 2022-09-07 18:14:21.358 | helper <ERROR> Could not subscribe to 73437396:stream.offline: Request failed with status code 409 / subscription already exists
> 2022-09-07 18:14:21.359 | helper.getSubsList <INFO> Requesting subscriptions list
> 2022-09-07 18:14:21.359 | helper.getSubsList <INFO> Fetch subs page 0
> 2022-09-07 18:14:21.647 | helper.getSubsList <INFO> 27 subscriptions
> 2022-09-07 18:14:21.649 | helper <INFO> Subscribe to 73437396:channel.update (bonjwa)
> 2022-09-07 18:14:21.918 | helper <ERROR> Could not subscribe to 73437396:channel.update: Request failed with status code 409 / subscription already exists
> 2022-09-07 18:14:21.919 | helper.getSubsList <INFO> Requesting subscriptions list
> 2022-09-07 18:14:21.919 | helper.getSubsList <INFO> Fetch subs page 0
> 2022-09-07 18:14:22.215 | helper.getSubsList <INFO> 27 subscriptions
> 10.1.0.226 - - [07/Sep/2022:16:15:04 +0000] "HEAD / HTTP/1.1" 200 485 "-" "Notifiarr"
> 2022-09-07 18:15:27.374 | vod.matchProviderVod <INFO> Trying to match handiofiblood (2022) - s{season}e01 to provider...
> 2022-09-07 18:15:27.657 | vod.matchProviderVod <SUCCESS> Found matching VOD for handiofiblood (2022) - s{season}e01
> 2022-09-07 18:15:27.659 | vodclass <SUCCESS> Saving JSON of handiofiblood (2022) - s{season}e01  (matched provider vod)
> Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"uuid":"aca...
> 2022-09-07 18:15:36.660 | channel <INFO> Download VOD 1584242284
> 2022-09-07 18:15:36.932 | channel <INFO> Downloading VOD 1584242284...
> 2022-09-07 18:15:36.940 | helper.execAdvanced <EXEC> Executing job 'download_vod_1584242284': $ /usr/local/bin/streamlink --ffmpeg-ffmpeg /usr/bin/ffmpeg -o /usr/local/share/twitchautomator/data/cache/1584242284.ts --hls-segment-threads 10 --url https://www.twitch.tv/videos/1584242284 --default-stream best
> 2022-09-07 18:15:36.942 | helper.execAdvanced <SUCCESS> Spawned process 79 for download_vod_1584242284
> 2022-09-07 18:15:36.944 | job <INFO> Save job download_vod_1584242284 with PID 79 to /usr/local/share/twitchautomator/data/cache/pids/download_vod_1584242284.json
> Broadcasting data to 1 clients: {"server":true,"action":"job_save","data":{"job_name":"download_...
> 2022-09-07 18:15:36.945 | helper.execAdvanced <INFO> Attached to all streams for process 79 for download_vod_1584242284
> Broadcasting data to 1 clients: {"server":true,"action":"job_update","data":{"job_name":"downloa...
> 2022-09-07 18:16:03.650 | hook <INFO> Hook called
> 2022-09-07 18:16:03.652 | automator.handle <INFO> Automator channel.update event for royalphunk
> Notifying clients: Live non-capturing channel royalphunk changed status: Rust (PhunkRoyal - RUST A LOT mit König Frank - Tag 5 - Lockeres Mittelalter Roleplay - !wer !r2), category offlineStatusChange
> 2022-09-07 18:16:03.653 | automator <INFO> Channel royalphunk not capturing, saving channel data to cache: Rust (PhunkRoyal - RUST A LOT mit König Frank - Tag 5 - Lockeres Mittelalter Roleplay - !wer !r2)
> 2022-09-07 18:16:03.654 | automator <INFO> Channel royalphunk status is online but not capturing, starting capture from chapter update.
> 2022-09-07 18:16:03.657 | channel <INFO> Create VOD JSON for royalphunk: royalphunk (2022) - s202209e36.json @ /usr/local/share/twitchautomator/data/storage/vods/royalphunk/Season 202209
> 2022-09-07 18:16:03.658 | vodclass <SUCCESS> Saving JSON of royalphunk (2022) - s202209e36  (create json)
> 2022-09-07 18:16:03.665 | vodclass <ERROR> No chapters on royalphunk (2022) - s202209e36!
> 2022-09-07 18:16:03.670 | vodclass <INFO> Run fixIssues for VOD royalphunk (2022) - s202209e36
> royalphunk (2022) - s202209e36 is not yet remuxed but no ts file found, skipping!
> 2022-09-07 18:16:03.671 | vodclass <WARNING> Loaded VOD royalphunk (2022) - s202209e36 is not finalized!
> 2022-09-07 18:16:03.672 | channel <ERROR> Vod on disk and vod in memory are not the same for royalphunk
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: royalphunk (2022) - s202209e02, royalphunk (2022) - s202209e04, royalphunk (2022) - s202209e06, royalphunk (2022) - s202209e08, royalphunk (2022) - s202209e08, royalphunk (2022) - s202209e28, royalphunk (2022) - s202209e28, royalphunk (2022) - s202209e28, royalphunk (2022) - s202209e28, royalphunk (2022) - s202209e36, category system
> 2022-09-07 18:16:03.673 | channel <ERROR> Vod on disk and vod in main memory are not the same for royalphunk
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: royalphunk (2022) - s202209e02, royalphunk (2022) - s202209e04, royalphunk (2022) - s202209e06, royalphunk (2022) - s202209e08, royalphunk (2022) - s202209e28, royalphunk (2022) - s202209e36, category system
> 2022-09-07 18:16:03.673 | channel <ERROR> Vod in memory and vod in main memory are not the same for royalphunk
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: , category system
> Broadcasting data to 1 clients: {"server":true,"action":"start_download","data":{"vod":{"uuid":"...
> 2022-09-07 18:16:03.676 | vodclass <WARNING> Saving JSON of royalphunk (2022) - s202209e36 with no chapters!!
> 2022-09-07 18:16:03.677 | vodclass <SUCCESS> Saving JSON of royalphunk (2022) - s202209e36  (is_capturing set)
> 2022-09-07 18:16:03.682 | automator <INFO> Update game for royalphunk (2022) - s202209e36
> 2022-09-07 18:16:03.682 | automator <SUCCESS> Channel data for royalphunk fetched from cache.
> 2022-09-07 18:16:03.684 | vodclass <WARNING> Saving JSON of royalphunk (2022) - s202209e36 with no chapters!!
> 2022-09-07 18:16:03.685 | vodclass <SUCCESS> Saving JSON of royalphunk (2022) - s202209e36  (dt_capture_started set)
> 2022-09-07 18:16:03.685 | automator <INFO> Starting capture with filename royalphunk (2022) - s202209e36.ts
> 2022-09-07 18:16:03.692 | automator <SUCCESS> Spawned process 94 for capture_royalphunk_39795989672
> 2022-09-07 18:16:03.695 | job <INFO> Save job capture_royalphunk_39795989672 with PID 94 to /usr/local/share/twitchautomator/data/cache/pids/capture_royalphunk_39795989672.json
> Broadcasting data to 1 clients: {"server":true,"action":"job_save","data":{"job_name":"capture_r...
> 2022-09-07 18:16:03.700 | vod.addChapter <INFO> Adding chapter PhunkRoyal - RUST A LOT mit König Frank - Tag 5 - Lockeres Mittelalter Roleplay - !wer !r2 (Rust) to royalphunk (2022) - s202209e28
> 2022-09-07 18:16:03.703 | vodclass <SUCCESS> Saving JSON of royalphunk (2022) - s202209e28  (game update)
> Broadcasting data to 1 clients: {"server":true,"action":"start_capture","data":{"vod":{"uuid":"a...
> Broadcasting data to 1 clients: {"server":true,"action":"chapter_update","data":{"chapter":{"tit...
> 2022-09-07 18:16:03.722 | automator <SUCCESS> Stream updated on 'royalphunk' to 'Rust' (PhunkRoyal - RUST A LOT mit König Frank - Tag 5 - Lockeres Mittelalter Roleplay - !wer !r2) using cache.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> ** Press ANY KEY to close this window **

**Comment by Serph91P** [comment]
Sorry for spamming Issues

**Comment by MrBrax** [comment]
odd that it happens, but i'll add an error check for it

**Comment by Serph91P** [comment]
> odd that it happens, but i'll add an error check for it

now its a bit different. Streamer changed Title/Section an DVR tried to record but crashed:

> 2022-09-07 20:00:40.803 | hook <INFO> Hook called
> 2022-09-07 20:00:40.804 | automator.handle <INFO> Automator channel.update event for giantwaffle
> Notifying clients: Live non-capturing channel giantwaffle changed status: Foxhole (Apple Event then Foxhole 1.0 Event), category offlineStatusChange
> 2022-09-07 20:00:40.806 | automator <INFO> Channel giantwaffle not capturing, saving channel data to cache: Foxhole (Apple Event then Foxhole 1.0 Event)
> 2022-09-07 20:00:40.807 | automator <INFO> Channel giantwaffle status is online but not capturing, starting capture from chapter update.
> 2022-09-07 20:00:40.809 | channel <INFO> Create VOD JSON for giantwaffle: giantwaffle (2022) - s202209e04.json @ /usr/local/share/twitchautomator/data/storage/vods/giantwaffle/Season 202209
> 2022-09-07 20:00:40.810 | vodclass <SUCCESS> Saving JSON of giantwaffle (2022) - s202209e04  (create json)
> 2022-09-07 20:00:40.815 | vodclass <ERROR> No chapters on giantwaffle (2022) - s202209e04!
> 2022-09-07 20:00:40.818 | vodclass <INFO> Run fixIssues for VOD giantwaffle (2022) - s202209e04
> giantwaffle (2022) - s202209e04 is not yet remuxed but no ts file found, skipping!
> 2022-09-07 20:00:40.819 | vodclass <WARNING> Loaded VOD giantwaffle (2022) - s202209e04 is not finalized!
> 2022-09-07 20:00:40.821 | channel <ERROR> Vod on disk and vod in memory are not the same for giantwaffle
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: giantwaffle (2022) - s202209e02, giantwaffle (2022) - s202209e04, category system
> 2022-09-07 20:00:40.821 | channel <ERROR> Vod on disk and vod in main memory are not the same for giantwaffle
> Notifying clients: VOD changed externally: Please do not delete or rename VOD files manually.
> Removed VODs: giantwaffle (2022) - s202209e02, giantwaffle (2022) - s202209e04, category system
> Broadcasting data to 1 clients: {"server":true,"action":"start_download","data":{"vod":{"uuid":"...
> 2022-09-07 20:00:40.824 | vodclass <WARNING> Saving JSON of giantwaffle (2022) - s202209e04 with no chapters!!
> 2022-09-07 20:00:40.824 | vodclass <SUCCESS> Saving JSON of giantwaffle (2022) - s202209e04  (is_capturing set)
> 2022-09-07 20:00:40.828 | automator <INFO> Update game for giantwaffle (2022) - s202209e04
> 2022-09-07 20:00:40.828 | automator <SUCCESS> Channel data for giantwaffle fetched from cache.
> 2022-09-07 20:00:40.829 | helper <WARNING> Game id 493388 not in cache.
> 2022-09-07 20:00:40.833 | vodclass <WARNING> Saving JSON of giantwaffle (2022) - s202209e04 with no chapters!!
> 2022-09-07 20:00:40.833 | vodclass <SUCCESS> Saving JSON of giantwaffle (2022) - s202209e04  (dt_capture_started set)
> 2022-09-07 20:00:40.834 | automator <INFO> Starting capture with filename giantwaffle (2022) - s202209e04.ts
> 2022-09-07 20:00:40.844 | automator <SUCCESS> Spawned process 45 for capture_giantwaffle_41234026747
> 2022-09-07 20:00:40.847 | job <INFO> Save job capture_giantwaffle_41234026747 with PID 45 to /usr/local/share/twitchautomator/data/cache/pids/capture_giantwaffle_41234026747.json
> Broadcasting data to 1 clients: {"server":true,"action":"job_save","data":{"job_name":"capture_g...
> Broadcasting data to 1 clients: {"server":true,"action":"start_capture","data":{"vod":{"uuid":"4...
> 54.184.54.118 - - [07/Sep/2022:18:00:40 +0000] "POST /api/v0/hook HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
> 2022-09-07 20:00:41.225 | helper <SUCCESS> New game saved to cache: Foxhole
> 2022-09-07 20:00:41.226 | vod.addChapter <INFO> Adding chapter Apple Event then Foxhole 1.0 Event (Foxhole) to giantwaffle (2022) - s202209e02
> 2022-09-07 20:00:41.227 | chapter <WARNING> No next chapter or vod end time for chapter Apple Event then Foxhole 1.0 Event (2022-09-07T18:00:40.805Z), duration will probably be 0.
> 2022-09-07 20:00:41.228 | vodclass <SUCCESS> Saving JSON of giantwaffle (2022) - s202209e02  (game update)
> Broadcasting data to 1 clients: {"server":true,"action":"chapter_update","data":{"chapter":{"tit...
> 2022-09-07 20:00:41.235 | automator <SUCCESS> Stream updated on 'giantwaffle' to 'Foxhole' (Apple Event then Foxhole 1.0 Event) using cache.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by MrBrax** [comment]
can't see an error in that one

**Comment by Serph91P** [comment]
> can't see an error in that one

But it crashed

**Comment by MrBrax** [comment]
must be that odd bug that occurred earlier with no stack trace or error

**Comment by Serph91P** [comment]
Hmmm

**Comment by MrBrax** [comment]
added a global exception handler that can be enabled in developer settings, it should catch everything and dump to crash.log in logs

**Comment by Serph91P** [comment]
> added a global exception handler that can be enabled in developer settings, it should catch everything and dump to crash.log in logs

got it again after streamer went offline handiofiblodd and bonjwa went online i guess. dunno log attached.
[error_develop.txt](https://github.com/MrBrax/LiveStreamDVR/files/9527456/error_develop.txt)

**Comment by MrBrax** [comment]
gonna have to test this on my own server, otherwise this sounds like a 100% unique problem just for your install..

**Comment by Serph91P** [comment]
> gonna have to test this on my own server, otherwise this sounds like a 100% unique problem just for your install..

ok that would be completely wired because i recently did a "fresh" install, imported some vods.

**Comment by MrBrax** [comment]
could there be anything wrong with the keyvalue store perhaps? because the download literally cannot start if the capture id is not set and yet it starts

**Comment by MrBrax** [comment]
ok i think i figured it out, it was from a chapter change and not a direct download
