### ISSUE TITLE
[Question] stream not being recorded

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#301]
What could be the problem if multiple streams are not being recorded but the dashboard says live. The docker was running at the time internet was also available. I even got the notification that the title was changed. But it's not being recorded. Will attach log later.

**Comment by MrBrax** [comment]
do the stream.online subs show up in the about page?

**Comment by Serph91P** [comment]
> do the stream.online subs show up in the about page?

They are alle there, this is only one example.
![Screenshot_20220920-141539](https://user-images.githubusercontent.com/8904984/191255096-ab061ab3-b8a0-4d95-81a0-f798cfc32419.png)

**Comment by MrBrax** [comment]
does it "go green/live" the moment the channel goes online or during a chapter update? because i think the latter checks online status and sets it to online if it wasn't before

**Comment by Serph91P** [comment]
> it saying false to the callback url is a bit concerning though

That's another streamer from the develop instance

**Comment by Serph91P** [comment]
> does it "go green/live" the moment the channel goes online or during a chapter update? because i think the latter checks online status and sets it to online if it wasn't before

Yes that's working but it's not recording.

**Comment by MrBrax** [comment]
hmm, could be a caught exception now that it doesn't crash the whole server anymore

**Comment by Serph91P** [comment]
It's about bonjwa, this eguy is from the develop instance that's why it says false.

**Comment by MrBrax** [comment]
try looking for error events coming from the automator source

**Comment by Serph91P** [comment]
> try looking for error events coming from the automator source


hmm dont see nothing here, maybe you spot something?
[error_log.txt](https://github.com/MrBrax/LiveStreamDVR/files/9608374/error_log.txt)

**Comment by Serph91P** [comment]
> > try looking for error events coming from the automator source
> 
> hmm dont see nothing here, maybe you spot something? [error_log.txt](https://github.com/MrBrax/LiveStreamDVR/files/9608374/error_log.txt)

found it I guess, the bonjwa.stream_number was at 1 but 1 was already present so it said already present and did not record I guess. But how it did that no idea.

**Comment by Serph91P** [comment]
> so which vod did not get captured exactly?

had it happen just now, giantwaffel the same the number was 1 and it tried to record but said already present.

**Comment by MrBrax** [comment]
where are you seeing this? there's no message like that in the code

**Comment by Serph91P** [comment]
> where are you seeing this? there's no message like that in the code

is more recent thats why its not in the log:

022-09-20 16:15:37.063 | automator.handle <INFO> Automator stream.online event for giantwaffle (retry 0)
2022-09-20 16:15:37.064 | automator.handle <INFO> giantwaffle stream has ID 41293031787, started 2022-09-20T14:14:30Z
Notifying clients: giantwaffle is live!: Just Chatting
NVidia Presser and Construction Sim, category streamOnline
Broadcasting data to 1 clients: {"action":"notify","data":{"title":"giantwaffle is live!","body"...
2022-09-20 16:15:37.068 | automator <ERROR> Cancel download of giantwaffle (2022) - s202209e02, vod already exists
2022-09-20 16:15:37.069 | automator.handle <ERROR> how did you get here

**Comment by MrBrax** [comment]
yeah you should probably make the name template more unique, like having an id in there or something

**Comment by Serph91P** [comment]
![image](https://user-images.githubusercontent.com/8904984/191300010-3ebbdc1a-6f1c-4e15-913a-10ee291e489b.png)

**Comment by MrBrax** [comment]
uhh those don't even have correct episode numbering, seems to be a bigger issue
