### ISSUE TITLE
[Feature suggestion] More options in the "render menu" 

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/LiveStreamDVR#302]
Hi,

I'm a huge fan of your project. And with every update it gets better and better :) ! 

I mainly use this because it also records the chat and it can even be burned in. But there always is a offset between de video and the recorded chat. 

When using the "Render Menu" to burn in the chat, could it be possible to change the offset to get a correct sync between the video and the chat and maybe get a preview of the outcoming product to see if it will burn in at the right timing. 

Also, the burning in of the chat takes a lot of cpu resources. So when I'm rendering my cpu is at 100%, could it be possible to use the GPU for this task?

Totally understandable if this is beyond the scope of this project :)

Thanks again

**Comment by MrBrax** [comment]
Syncing has always been an issue, I could add a manual seconds input, but I don't think a preview would work. I guess the vod player with chat could be used in beforehand?

GPU burning can work if you don't use docker, and most seem to. Reencoder does use it, just haven't copied it over.

**Comment by CappiSteijns** [comment]
> 

Hmm, yes the vod player could be a good tool to measure the offsync. I geuss in theorie if the offsync is set up in de vod player you could just use the offset time in the burning menu. 

And yes, I do use docker. There are options to use a gpu in a docker? But I most certainly trust you if you say it is only possible outside docker. Maybe I could find a way to burn on my pc, have to look into that when I have the time :)

**Comment by mr-flibble** [comment]
> GPU burning can work if you don't use docker, and most seem to. Reencoder does use it, just haven't copied it over.

AFAIK GPU burnings theoretically should work, peoples are using Jellyfin/Emby/Plex in docker with GPU acceleration. Generally you just need to add something like to the docker config
`   devices:
      - /dev/dri:/dev/dri `
source:
https://ryanbritton.com/2022/05/hardware-transcoding-on-synology-docker-without-privileged-mode/
