### ISSUE TITLE
Suggestion: [Option to] write to cache, then move to storage when stream ends

### ISSUE THREAD

**Issue by 0x1f415** [MrBrax/LiveStreamDVR#307]
hey, I've been running this application for a few weeks now and it's served my purposes pretty well.

I'm running this via docker on my unraid box and when a stream is live my CPU usage looks like this:

![image](https://user-images.githubusercontent.com/6064300/192821159-76a89036-eb5c-4979-85cd-38d2159aeccf.png)

docker mounts are as such;

![image](https://user-images.githubusercontent.com/6064300/192821371-6d99fcf5-710a-4061-958e-0512b680222f.png)

/mnt/user/Twitch VODs/ is cache: yes and /mnt/user/appdata/ is of course cache: prefer

glances shows that my CPU has very high IOWAIT:

![image](https://user-images.githubusercontent.com/6064300/192821761-e18aecd9-0442-4814-9265-645bd2978afb.png)

for a minute I thought this was writes but while watching the dashboard I see disk reads going up for my array. IMO there is no reason why the array needs to be read from to archive a live stream if the share is set to cache: yes.

in unraid's share browser the interface shows that the directory for this streamer is on the array, including the JSON for the currently recording stream:

![image](https://user-images.githubusercontent.com/6064300/192823274-8716fb47-4a50-4a48-9113-0604318ab910.png)

my knowledge of how unraid's file system works is not 100% but it seems that writing a file to a directory still triggers a read of the array disk if that directory is on the array, even if the share is set to cache: yes.

so I believe that the IOWAIT CPU spikes are occurring because LiveStreamDVR is writing the currently live stream's .ts and .json files to the storage volume, when IMO it could be writing to the cache volume for the duration of the stream to avoid unnecessary array access.

**Comment by MrBrax** [comment]
hmm, i guess that's a viable idea

**Comment by Serph91P** [comment]
> hey, I've been running this application for a few weeks now and it's served my purposes pretty well.
> 
> I'm running this via docker on my unraid box and when a stream is live my CPU usage looks like this:
> 
> ![image](https://user-images.githubusercontent.com/6064300/192821159-76a89036-eb5c-4979-85cd-38d2159aeccf.png)
> 
> docker mounts are as such;
> 
> ![image](https://user-images.githubusercontent.com/6064300/192821371-6d99fcf5-710a-4061-958e-0512b680222f.png)
> 
> /mnt/user/Twitch VODs/ is cache: yes and /mnt/user/appdata/ is of course cache: prefer
> 
> glances shows that my CPU has very high IOWAIT:
> 
> ![image](https://user-images.githubusercontent.com/6064300/192821761-e18aecd9-0442-4814-9265-645bd2978afb.png)
> 
> for a minute I thought this was writes but while watching the dashboard I see disk reads going up for my array. IMO there is no reason why the array needs to be read from to archive a live stream if the share is set to cache: yes.
> 
> in unraid's share browser the interface shows that the directory for this streamer is on the array, including the JSON for the currently recording stream:
> 
> ![image](https://user-images.githubusercontent.com/6064300/192823274-8716fb47-4a50-4a48-9113-0604318ab910.png)
> 
> my knowledge of how unraid's file system works is not 100% but it seems that writing a file to a directory still triggers a read of the array disk if that directory is on the array, even if the share is set to cache: yes.
> 
> so I believe that the IOWAIT CPU spikes are occurring because LiveStreamDVR is writing the currently live stream's .ts and .json files to the storage volume, when IMO it could be writing to the cache volume for the duration of the stream to avoid unnecessary array access.

That's way to high CPU usage for the recording task. Are you sure that this is only recording and not remuxing? Because for me my CPU sits at 5-6% while recording. Btw if correctly setup your mount it should write only to cache and move the file to your array when the file is finished. As far as I know is the iowait  a form of idle time when nothing could be scheduled. So it could mean that your CPU is either idle or underpowered

**Comment by MrBrax** [comment]
ts and mp4 files have always been stored in the same folder, so it's pushing data constantly to the storage

**Comment by Serph91P** [comment]
Yeah what I meant is unRAID specific you can setup that if to a path new files are written those files are firstly written to a "cache" pool which most of the time is a SSD and later moved to a spinning drive.

**Comment by 0x1f415** [comment]
looks like this has solved my issue, thanks!

![image](https://user-images.githubusercontent.com/6064300/193316042-db5b3faa-4b55-470e-871a-e1cabb3d04b7.png)

![image](https://user-images.githubusercontent.com/6064300/193316081-b9672088-540c-470d-8cf4-d547e73e4e16.png)
