### ISSUE TITLE
FFMpeg output not in the correct directory causing failure

### ISSUE THREAD

**Issue by ermosk** [MrBrax/LiveStreamDVR#309]
I've just noticed that ffmpeg output directory is not rightly specified, causing the remux to fail

From the logs the command run is 

`/usr/bin/ffmpeg -i /usr/local/share/twitchautomator/data/cache/1599913530.ts -i /usr/local/share/twitchautomator/data/cache/1599913530.ffmpeg.txt -map_metadata 1 -c copy -bsf:a aac_adtstoasc -movflags faststart -loglevel repeat+level+verbose dota2ti_2022-09-24T12_47_11Z_41311401771/dota2ti_2022-09-24T12_47_11Z_41311401771.mp4`

As you can see, the output file, does not have the /usr/local/share/twitchautomator/data/storage prepended, causing the remux to fail.

**Comment by MrBrax** [comment]
where was this called from?

**Comment by ermosk** [comment]
![image](https://user-images.githubusercontent.com/5785917/193403946-633e5512-1d43-40b4-8376-eb9fbae7ff50.png)

The .ts downloads fine in the cache directory, but from there onward when ffmpeg remuxes to the .mp4 it bombs out.
