### ISSUE TITLE
Force record don't work after docker update

### ISSUE THREAD

**Issue by mr-flibble** [MrBrax/LiveStreamDVR#310]
Hello, in latest docker version function "Force record" no longer work.
I tried clean deployment and behaviour is same:

Steps to reproduce:

1. have some live channel
2. click Force record
3. get message box "No live stream found"
4. get single log line:
helper  INFO  Querying streams for streamer"
and nothing happens 

**Broken version is:**
Backend version: 1.1.0
Backend git hash: 48942d00cf8e64915368e2feadfcbec75c9caf92
Frontend version: 2.1.0
Frontend build: production
Frontend verbose: 2.1.0 (2022-09-30T07:38:32.763Z / 48942d0)

**Old Working version:**
Backend version: 0.6.0-hotfix1
Backend git hash: 70c4ff1741fecc848b0ac940768ce1fa0cc9dd93
Frontend version: 1.1.0
Frontend build: production
Frontend verbose: 1.1.0 (2022-09-16T14:04:28.633Z / 70c4ff1)

**Comment by MrBrax** [comment]
alright easy fix

**Comment by mr-flibble** [comment]
Thanks! Can confirm that fix works and forced recording records : )
