### ISSUE TITLE
[BUG] Youtube

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#314]
If the Sign in with Goolge Button is pressed (client and secret is entered), a new tab with the title undefined is openend and nothing happens. This was working bevore dunno what changed. Log that appears when pressed is this: 

> redacted - - [03/Oct/2022:13:03:01 +0000] "GET /api/v0/channels HTTP/1.1" 200 1170570 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36"
redacted - - [03/Oct/2022:13:03:02 +0000] "GET /api/v0/auth/check HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36"
redacted - - [03/Oct/2022:13:03:02 +0000] "GET /api/v0/settings HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36"
redacted - - [03/Oct/2022:13:03:02 +0000] "GET /api/v0/channels HTTP/1.1" 200 1170469 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36"
redacted - - [03/Oct/2022:13:03:03 +0000] "GET /api/v0/jobs HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36"
JSON from 172.18.0.1: { action: 'helloworld' }

**Comment by MrBrax** [comment]
your google session might be broken, sometimes it thinks you're already authenticated

**Comment by Serph91P** [comment]
> your google session might be broken, sometimes it thinks you're already authenticated

If I click destroy, it says "No access token to revoke."

**Comment by Serph91P** [comment]
> does the new tab get an url at all?

https://example.com/api/v0/youtube/authenticate

**Comment by MrBrax** [comment]
ok so it doesn't redirect to another page? maybe it's not receiving an url then

**Comment by Serph91P** [comment]
> ok so it doesn't redirect to another page? maybe it's not receiving an url then

no you stay basically on the same page after you click on that button only the url changes.
From https://myawesomeurl.de/settings/config to https://myawesomeurl.de/api/v0/youtube/authenticate

**Comment by MrBrax** [comment]
it works on my end, so not sure what's happening. i put an error message if there was no url at least

**Comment by Serph91P** [comment]
> it works on my end, so not sure what's happening. i put an error message if there was no url at least

question, in the docs you wrote 

> Application type: Web application
Authorized JavaScript origins: App URL (ex. https://livestreamdvr.example.com)
Authorized redirect URI: App URL with callback (ex. https://livestreamdvr.example.com/api/v0/youtube/callback)

you should use ur own url no? so actually enter the url ur using.

**Comment by MrBrax** [comment]
yes, the domain name should be your own, the route path is separate for each service now

**Comment by Serph91P** [comment]
Because all my browser dont work, will try google chrome now.

> yes, the domain name should be your own, the route path is separate for each service now

then I dunno what went wrong now, just created a new project just to make sure google didnt do some kind of crazy shit. Even installed google chrome it wont work anymore.

**Comment by MrBrax** [comment]
if you have the developer tools open and check the network tab, does it try to redirect?

**Comment by Serph91P** [comment]
Just disabled my pihole, the same nothing changes. Nowhere it seems to work. Windows Linux or android with different browsers.

**Comment by MrBrax** [comment]
pretty odd considering i never put a status code 200 anywhere

**Comment by Serph91P** [comment]
> pretty odd considering i never put a status code 200 anywhere

I meant like pictures and that the page loaded.

**Comment by Serph91P** [comment]
Develop does not work aswell.

**Comment by MrBrax** [comment]
it has to be something on your end then i guess, if it hasn't worked in a while? what about a private tab?

**Comment by Serph91P** [comment]
> it has to be something on your end then i guess, if it hasn't worked in a while? what about a private tab?

Same in a private tab. it stopped working like almost a week ago. Dunno what changed, besides kernel from the os or update to the browser but tried every other browser there is.

**Comment by Serph91P** [comment]
Something I can delete and still keep my streamer and streams but deletes the config for that?

**Comment by MrBrax** [comment]
the youtube json files and username txt file in cache can be deleted.

i added a 404 page if a page wasn't found, should have done that ages ago

**Comment by Serph91P** [comment]
> the youtube json files and username txt file in cache can be deleted.
> 
> i added a 404 page if a page wasn't found, should have done that ages ago

Where would that file be? Because in the cache folder there is no such file.
In none of these folders. Or is it the OAUTH one?
![image](https://user-images.githubusercontent.com/8904984/193636110-71b76f44-346a-4cba-95bf-47829ba3b471.png)

**Comment by MrBrax** [comment]
they are deleted when invalid, so it means you're not authenticated, basically...

i feel like there should be some kind of log happening when you try to auth

**Comment by Serph91P** [comment]
> they are deleted when invalid, so it means you're not authenticated, basically...
> 
> i feel like there should be some kind of log happening when you try to auth

and iam not authenticated because I cannot. Or is it because I misconfigured something in the google dev wrong?

**Comment by MrBrax** [comment]
does the /authenticate visit not show up anywhere in the log?

**Comment by Serph91P** [comment]
The last thing I could Imaginge would help us find the error:
https://user-images.githubusercontent.com/8904984/193639365-61112533-58ee-4590-ae0b-76128eb00cc6.mp4

**Comment by Serph91P** [comment]
> does the /authenticate visit not show up anywhere in the log?

BTW just noticed there are no notifications send via discord anymore aswell.

**Comment by MrBrax** [comment]
is there something with your reverse proxy? the authenticate page should not be handled by the client

**Comment by Serph91P** [comment]
> is there something with your reverse proxy? the authenticate page should not be handled by the client

What do you mean?

**Comment by MrBrax** [comment]
/api/v0/youtube/authenticate and all /api calls are handled by the server and not by the client in its routing, something is preventing the server from "sending" the page to the user

**Comment by Serph91P** [comment]
> /api/v0/youtube/authenticate and all /api calls are handled by the server and not by the client in its routing, something is preventing the server from "sending" the page to the user

I guess it's cloudfare, need to identify what they changed so those requests are blocked.

**Comment by MrBrax** [comment]
what happens if you curl get&post the youtube thing?

**Comment by Serph91P** [comment]
> what happens if you curl get&post the youtube thing?

Access denied if I curl the adress

**Comment by Serph91P** [comment]
> is there something with your reverse proxy? the authenticate page should not be handled by the client

I guess API should be passed through any other subfolders that should be passed through? Sub or something, will edit my reverse proxy config accordingly.

**Comment by MrBrax** [comment]
maybe cloudflare gets confused if there's a redirect on the page

**Comment by MrBrax** [comment]
i made the popup be in a new window instead and don't redirect like other applications, maybe that helps visualise it

**Comment by Serph91P** [comment]
> i made the popup be in a new window instead and don't redirect like other applications, maybe that helps visualise it

just tested it, in the method with popup I can authenticate but after the process and I click contintue i get redirected in the popup and am still not authenticated.

**Comment by MrBrax** [comment]
anything in the logs about it after you press it?

**Comment by Serph91P** [comment]
> anything in the logs about it after you press it?

2022-10-04 11:06:02.848 | YouTube <INFO> Begin auth process...
2022-10-04 11:06:02.849 | YouTube <SUCCESS> Send raw URL to user: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly&response_type=code&client_id=581273685678-gl0aglaek5nqu91ouvlck5jsc74f3ii8.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fredacted%2Fapi%2Fv0%2Fyoutube%2Fcallback

**Comment by MrBrax** [comment]
so nothing at all? the callback url is not visited?

**Comment by Serph91P** [comment]
thats the only thing that has the slightest to do with auth, the rest ist just that the page is loading and stuff

**Comment by Serph91P** [comment]
nope

**Comment by MrBrax** [comment]
and if you visit /api/v0/youtube/callback manually?

**Comment by Serph91P** [comment]
> thats the only thing that has the slightest to do with auth, the rest ist just that the page is loading and stuff
copied everything just to make shure
2022-10-04 11:06:02.848 | YouTube <INFO> Begin auth process...
2022-10-04 11:06:02.849 | YouTube <SUCCESS> Send raw URL to user: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly&response_type=code&client_id=581273685678-gl0aglaek5nqu91ouvlck5jsc74f3ii8.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Ftdeleted%2Fapi%2Fv0%2Fyoutube%2Fcallback
37.209.39.18 - - [04/Oct/2022:09:06:02 +0000] "GET /api/v0/youtube/authenticate?rawurl=true HTTP/1.1" 200 459 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:06:13 +0000] "GET /api/v0/auth/check HTTP/1.1" 200 107 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:06:13 +0000] "GET /api/v0/settings HTTP/1.1" 200 17716 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:06:13 +0000] "GET /api/v0/channels HTTP/1.1" 200 44101 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:06:13 +0000] "GET /api/v0/jobs HTTP/1.1" 200 25 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:06:13 +0000] "GET /cache/thumbs/7b1e179f63a73604f45caab4cc45e6af.jpg HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
JSON from 172.18.0.1: { action: 'helloworld' }
37.209.39.18 - - [04/Oct/2022:09:06:14 +0000] "GET /sw.js HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:06:14 +0000] "GET /workbox-3ea082d2.js HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /assets/roboto-latin-700-normal.0eaeadb5.woff2 HTTP/1.1" 304 - "https://twitch.mebert-server.de/assets/index.9a372d5d.css" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /assets/roboto-latin-400-normal.cc46322d.woff2 HTTP/1.1" 304 - "https://twitch.mebert-server.de/assets/index.9a372d5d.css" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /api/v0/auth/check HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /api/v0/settings HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /api/v0/channels HTTP/1.1" 200 44101 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /api/v0/jobs HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
37.209.39.18 - - [04/Oct/2022:09:07:37 +0000] "GET /assets/roboto-condensed-latin-400-normal.53b90732.woff2 HTTP/1.1" 304 - "https://twitch.mebert-server.de/assets/index.9a372d5d.css" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
JSON from 172.18.0.1: { action: 'helloworld' }
37.209.39.18 - - [04/Oct/2022:09:07:38 +0000] "GET /sw.js HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"

**Comment by Serph91P** [comment]
> and if you visit /api/v0/youtube/callback manually?

still the undefined page where nothing laods

**Comment by MrBrax** [comment]
do you have trust proxy enabled? otherwise i don't really have many solutions left, really sounds like something wrong with your reverse proxy

**Comment by Serph91P** [comment]
> do you have trust proxy enabled? otherwise i don't really have many solutions left, really sounds like something wrong with your reverse proxy

ok that is very odd, I changed nothing but I cannot even access my other pages especially organizt wich is almost reporting the same. 
![image](https://user-images.githubusercontent.com/8904984/193791040-00e15fe1-1320-4235-940c-049e56fdf080.png)
This version is two years old and I had it running for almost that time. Like iam on a newer version. It has to do with cloudfare. But what.

**Comment by MrBrax** [comment]
breaking update at cloudflare? sounds like it's rewriting the url somehow

**Comment by Serph91P** [comment]
> breaking update at cloudflare? sounds like it's rewriting the url somehow

maybe its a setting of cloudflare dunno

**Comment by Serph91P** [comment]
its the only thing that may have changed the rest is the same, setting wise I changed lokal nothing. I can access organizr lokal aswell so it has to do with it.

**Comment by MrBrax** [comment]
make sure it's not adding or changing anything with the reverse proxy stuff other than the forwarded ip, with some proxy stuff you can have it all redirect to index.html and similar, could depend on the content-type too

**Comment by Serph91P** [comment]
> make sure it's not adding or changing anything with the reverse proxy stuff other than the forwarded ip, with some proxy stuff you can have it all redirect to index.html and similar, could depend on the content-type too

ok I have my own page fixed its not showing an error again I guess. But lsdvr now shows this when I try to authenticate: error 400: redirect_uri_mismatch

**Comment by MrBrax** [comment]
is the redirect uri set correctly at google?

**Comment by Serph91P** [comment]
> is the redirect uri set correctly at google?

example.com/api/v0/youtube/callback

**Comment by MrBrax** [comment]
and what url are you getting redirected to when authenticating? does it include exactly everything in that address?

**Comment by Serph91P** [comment]
> and what url are you getting redirected to when authenticating? does it include exactly everything in that address? https included?

thats the first thing I get https://accounts.google.com/signin/oauth/error/v2?authError=ChVyZWRpcmVjdF91cmlfbWlzbWF0Y2gS3AEKU2llIGvDtm5uZW4gc2ljaCBuaWNodCBpbiBkaWVzZXIgQXBwIGFubWVsZGVuLCB3ZWlsIHNpZSBuaWNodCBkZW4gR29vZ2xlLVJpY2h0bGluaWVuIGbDvHIgT0F1dGjCoDIuMCBlbnRzcHJpY2h0LgoKV2VubiBTaWUgZGVyIEFwcC1FbnR3aWNrbGVyIHNpbmQsIHJlZ2lzdHJpZXJlbiBTaWUgZGVuIFdlaXRlcmxlaXR1bmdzLVVSSSBpbiBkZXIgR29vZ2xlIENsb3VkIENvbnNvbGUuCiAgGm1odHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3dlYi1zZXJ2ZXIjYXV0aG9yaXphdGlvbi1lcnJvcnMtcmVkaXJlY3QtdXJpLW1pc21hdGNoIJADKkAKDHJlZGlyZWN0X3VyaRIwaHR0cHM6Ly9tZWJlcnQtc2VydmVyLmRlL2FwaS92MC95b3V0dWJlL2NhbGxiYWNrMtACCAES3AEKU2llIGvDtm5uZW4gc2ljaCBuaWNodCBpbiBkaWVzZXIgQXBwIGFubWVsZGVuLCB3ZWlsIHNpZSBuaWNodCBkZW4gR29vZ2xlLVJpY2h0bGluaWVuIGbDvHIgT0F1dGjCoDIuMCBlbnRzcHJpY2h0LgoKV2VubiBTaWUgZGVyIEFwcC1FbnR3aWNrbGVyIHNpbmQsIHJlZ2lzdHJpZXJlbiBTaWUgZGVuIFdlaXRlcmxlaXR1bmdzLVVSSSBpbiBkZXIgR29vZ2xlIENsb3VkIENvbnNvbGUuCiAgGm1odHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3dlYi1zZXJ2ZXIjYXV0aG9yaXphdGlvbi1lcnJvcnMtcmVkaXJlY3QtdXJpLW1pc21hdGNo&client_id=418383967832-dcf90dt9ofkcbdu5v7dfeveh5ip3bu2e.apps.googleusercontent.com

**Comment by MrBrax** [comment]
still seems like your uri is invalid somehow

**Comment by Serph91P** [comment]
> and what url are you getting redirected to when authenticating? does it include exactly everything in that address? https included?

OK was stupid this one is on me. error still exists. After auth of goole get redirected to https://twitch.example.com/api/v0/youtube/callback?code=4/0ARtbsJrgCev5up4djB7pf_X8Viz_f6FrohmR1Ah0HPUN9zoc0PjgOe3YjjCRPETQqw6-yQ&scope=profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/youtube.upload%20https://www.googleapis.com/auth/youtube.readonly

**Comment by MrBrax** [comment]
and that url gets handled by the client still? which is the weird part

you should probably delete the urls since they contain session id's and stuff

**Comment by Serph91P** [comment]
My proxy configs look like this dunno if you can help with that:
subdomain.conf:

> 
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name twitch.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
	
    #if ($lan-ip = yes) { set $geo-whitelist yes; }
    #if ($geo-whitelist = no) { return 404; }

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.178.3;
        set $upstream_port 8146;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
    location ^~ /api/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.178.3;
        set $upstream_port 8146;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}

proxy.conf:

## Version 2021/10/26 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/proxy.conf

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Proxy Connection Settings
proxy_buffers 32 4k;
proxy_connect_timeout 240;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
proxy_http_version 1.1;
proxy_read_timeout 240;
proxy_redirect  http://  $scheme://;
proxy_send_timeout 240;

# Proxy Cache and Cookie Settings
proxy_cache_bypass $cookie_session;
#proxy_cookie_path / "/; Secure"; # enable at your own risk, may break certain apps
proxy_no_cache $cookie_session;

# Proxy## Version 2021/10/26 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/proxy.conf

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Proxy Connection Settings
proxy_buffers 32 4k;
proxy_connect_timeout 240;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
proxy_http_version 1.1;
proxy_read_timeout 240;
proxy_redirect  http://  $scheme://;
proxy_send_timeout 240;

# Proxy Cache and Cookie Settings
proxy_cache_bypass $cookie_session;
#proxy_cookie_path / "/; Secure"; # enable at your own risk, may break certain apps
proxy_no_cache $cookie_session;

# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;
 Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;

**Comment by Serph91P** [comment]
> and that url gets handled by the client still? which is the weird part
> 
> you should probably delete the urls since they contain session id's and stuff, post history is public too

what do you mean by that "by the client" 

Deletet all posts about something url ish

**Comment by Serph91P** [comment]
> and what url are you getting redirected to when authenticating? does it include exactly everything in that address? https included?

forgot the https but its there.

**Comment by Serph91P** [comment]
> i don't think the api block is required in the reverse proxy, i don't have it at least
> 
> what's cloudflare for if you don't use that for proxying?
> 
> > what do you mean by that "by the client"
> 
> the client is handling the request which should not be happening, that's the job of the server since it's an api request

my reverse proxy is swag, where those two configs came from the api part was a test.Cloudflare is setup as a proxy this is correct. Why the client is handling the request I dunno.

**Comment by MrBrax** [comment]
so you have two reverse proxies chained? might cause some issues

**Comment by Serph91P** [comment]
> so you have two reverse proxies chained? might cause some issues

cloudflare is only pointing to the right ip and swag is distributing to the correct application. As far as i know this is used like this.

**Comment by Serph91P** [comment]
> > so you have two reverse proxies chained? might cause some issues
> 
> cloudflare is only pointing to the right ip and swag is distributing to the correct application. As far as i know this is used like this.

https://docs.ibracorp.io/cloudflare-tunnel/ so I donot have to port forward anything it just goes directly to the server and is then handled by swag so everything goes to the correct application

**Comment by MrBrax** [comment]
way more involved than anything i use, don't think i can help with that

**Comment by Serph91P** [comment]
> way more involved than anything i use, don't think i can help with that

its quite easy to use now since you can do it via gui now. Disabled cloudflare for the lsdvr adress just to make sure its not this. And its still the same. Will ask in the discord channel from swag for help maybe they know whats going on.

**Comment by MrBrax** [comment]
![1664905730443](https://user-images.githubusercontent.com/1517911/193890229-fdbe8da1-f83f-4dd9-bce2-a3c5fcb63664.png)
i found the issue, it's the service worker/pwa caching the api directory. if you force refresh (shift+reload) the page it should work. i gotta find some way to ignore the api path

**Comment by MrBrax** [comment]
it worked for me because service workers don't run in development mode, great

**Comment by Serph91P** [comment]
> ![1664905730443](https://user-images.githubusercontent.com/1517911/193890229-fdbe8da1-f83f-4dd9-bce2-a3c5fcb63664.png) i found the issue, it's the service worker/pwa caching the api directory. if you force refresh (shift+reload) the page it should work. i gotta find some way to ignore the api path

Great work thank you. Now I get further than before. But after login I get this error.
![Screenshot_20221005-071528](https://user-images.githubusercontent.com/8904984/193986567-81871fc0-ed95-4693-8698-919b1bbefbdc.png)

**Comment by Serph91P** [comment]
But I am logged in now.

**Comment by MrBrax** [comment]
i get that one too sometimes, i think it has to do with multiple sessions and revoking

**Comment by Serph91P** [comment]
> i get that one too sometimes, i think it has to do with multiple sessions and revoking

Hmm just tried an upload to YouTube but the video is not appearing anywhere. Log says video upload finished successful.

**Comment by Serph91P** [comment]
It's the correct account etc.

**Comment by Serph91P** [comment]
Found them -> working. When do you think you will push this to master?

**Comment by MrBrax** [comment]
soonish probably. guessing the videos were private?
