### ISSUE TITLE
[Feature] YouTube add to playlist

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#317]
1. Would be great if you could implement that the video exported to youtube would get automatically added to a specified playlist.

2. Auto exporter with extra settings for every streamer so you can set a specific playlist like the Season theme you already did with naming would be great.

**Comment by MrBrax** [comment]
creating playlists might be a bit overkill, i'll make it so you have to create your own and input them in the config for now

**Comment by Serph91P** [comment]
> creating playlists might be a bit overkill, i'll make it so you have to create your own and input them in the config for now

You write as tooltip that Use this format: channelname=ABC123;secondchannel=DEF456
example thiseguy=playlist ID or playlist name?

**Comment by MrBrax** [comment]
the playlist id yes, i'll make the id visible in the export dialog too

**Comment by MrBrax** [comment]
does it add the video to the playlist? i have no idea

**Comment by Serph91P** [comment]
> does it add the video to the playlist? i have no idea

just tried to upload a video to a playlist, the video appears in the youtube manager but the job is kinda funky in the gui:

![grafik](https://user-images.githubusercontent.com/8904984/195056604-af0a1e34-1613-4b88-ad92-7ea779c48cb2.png)


[11/Oct/2022:09:29:38 +0000] "GET /api/v0/youtube/playlists HTTP/1.1" 200 6466 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
Create exporter youtube vod {
  title_template: '[{login}] {title} ({date})',
  directory: '',
  host: '',
  username: '',
  password: '',
  description: 'VOD',
  tags: 'Gaming VOD',
  category: '20',
  file_source: 'segment',
  privacy: 'private',
  vod: 'thiseguy (2022) - s202210e04',
  remote: '',
  playlist_id: 'PLqBFPPTpZzdGtIZzC2wVwrligyBBfC24l'
}
2022-10-11 11:29:45.372 | YouTubeExporter <INFO> Uploading /usr/local/share/twitchautomator/data/storage/vods/thiseguy/Season 02/thiseguy (2022) - s202210e04.mp4 to YouTube...
2022-10-11 11:29:45.374 | job <INFO> Save job YouTubeExporter_thiseguy (2022) - s202210e04.mp4 with PID undefined to /usr/local/share/twitchautomator/data/cache/pids/YouTubeExporter_thiseguy (2022) - s202210e04.mp4.json
Broadcasting data to 1 clients: {"server":true,"action":"job_save","data":{"job_name":"YouTubeEx...

**Comment by Serph91P** [comment]
> > does it add the video to the playlist? i have no idea
> 
> just tried to upload a video to a playlist, the video appears in the youtube manager but the job is kinda funky in the gui:
> 
> ![grafik](https://user-images.githubusercontent.com/8904984/195056604-af0a1e34-1613-4b88-ad92-7ea779c48cb2.png)
> 
> [11/Oct/2022:09:29:38 +0000] "GET /api/v0/youtube/playlists HTTP/1.1" 200 6466 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0" Create exporter youtube vod { title_template: '[{login}] {title} ({date})', directory: '', host: '', username: '', password: '', description: 'VOD', tags: 'Gaming VOD', category: '20', file_source: 'segment', privacy: 'private', vod: 'thiseguy (2022) - s202210e04', remote: '', playlist_id: 'PLqBFPPTpZzdGtIZzC2wVwrligyBBfC24l' } 2022-10-11 11:29:45.372 | YouTubeExporter Uploading /usr/local/share/twitchautomator/data/storage/vods/thiseguy/Season 02/thiseguy (2022) - s202210e04.mp4 to YouTube... 2022-10-11 11:29:45.374 | job Save job YouTubeExporter_thiseguy (2022) - s202210e04.mp4 with PID undefined to /usr/local/share/twitchautomator/data/cache/pids/YouTubeExporter_thiseguy (2022) - s202210e04.mp4.json Broadcasting data to 1 clients: {"server":true,"action":"job_save","data":{"job_name":"YouTubeEx...

btw not added to playlist so far

**Comment by MrBrax** [comment]
hmm ok, no playlist add errors?

**Comment by Serph91P** [comment]
> 

Nope none it's just not added if I edit the video file on YouTube I see that there is no playlist selected.

**Comment by MrBrax** [comment]
i don't know if i accidentally fixed it but it seems to be working on my end now at least
