### ISSUE TITLE
[Bug] Notifications dont work anymore

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#318]
This error that the notifications no longer work seems to have happened at the same time as the Youtube authentication. Both Discord and Telegram no longer work. Only the browser notifications still work.

**Comment by Serph91P** [comment]
> i use telegram notifications myself which still work, any errors from it? maybe the token ran out?

and discord? the webhook url is still the same. Copied the information for Telegram again and enabled it again. Lets see if this works.

**Comment by Serph91P** [comment]
> i use telegram notifications myself which still work, any errors from it? maybe the token ran out?

jsut found this wtf: 2022-10-05 16:19:46.737 | webhook <ERROR> Discord error: Request failed with status code 400

**Comment by MrBrax** [comment]
sounds like an unauthorized request, i'll add the response data to the error

**Comment by Serph91P** [comment]
> sounds like an unauthorized request, i'll add the response data to the error

how, I copied recently the url again so its quite up to date.

**Comment by Serph91P** [comment]
> maybe ip banned or something? i have no idea

stopped at 2022.10.01 why would it be banned

**Comment by MrBrax** [comment]
discord works for me too, can't really be cloudflare since it's outgoing only but i dunno

**Comment by Serph91P** [comment]
> discord works for me too, can't really be cloudflare since it's outgoing only but i dunno

this was working aswell so it shouldnt be cloudflare. You never know. Checked all settings and it should not be cloudflare since I enabled to set updated/new settings to disabled.

**Comment by Serph91P** [comment]
maybe add a test for notifications button?

**Comment by MrBrax** [comment]
yeah just made one

telegram already has a whole bunch of error output, if something is wrong it should be logged

**Comment by Serph91P** [comment]
> yeah just made one
> 
> telegram already has a whole bunch of error output, if something is wrong it should be logged if their api returned success nothing is logged at all

Telegram is working fine for me as well. That's wired.

**Comment by MrBrax** [comment]
ok so only discord giving a 400? could you test with the new update that outputs the response data?

it might be some formatting error depending on what text is sent

**Comment by Serph91P** [comment]
> ok so only discord giving a 400? could you test with the new update that outputs the response data?
> 
> it might be some formatting error depending on what text is sent

2022-10-05 18:55:10.869 | vodclass <SUCCESS> Saving JSON of herrmaximal (2022) - s{season}e01  (game update)
Broadcasting data to 1 clients: {"server":true,"action":"chapter_update","data":{"chapter":{"tit...
2022-10-05 18:55:10.873 | automator <SUCCESS> Stream updated on 'herrmaximal' to 'Godlike Burger' (Lasst uns den besten Bürger machen) using cache.
Notifying clients: herrmaximal is now playing Godlike Burger!: Lasst uns den besten Bürger machen, category streamStatusChange
37.209.39.18 - - [05/Oct/2022:16:55:11 +0000] "GET /cache/covers/418591187.jpg HTTP/1.1" 200 13060 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
2022-10-05 18:55:11.108 | notify <ERROR> Discord error: Request failed with status code 400 ([object Object])
2022-10-05 18:55:11.400 | automator <INFO> Stream resolution for herrmaximal (2022) - s{season}e01: 720p60
2022-10-05 18:55:11.401 | automator <WARNING> Stream resolution 720p60 assumed to not be in channel quality list
2022-10-05 18:55:11.402 | automator <INFO> Capturing of herrmaximal (2022) - s{season}e01, will try to remove ads!

**Comment by MrBrax** [comment]
what if you click on the log line in the dashboard log viewer?

**Comment by Serph91P** [comment]
> what if you click on the log line in the dashboard log viewer?

pretty much the same:

> <html>
<body>


2022-10-05 18:55:10 | job | INFO | Save job capture_herrmaximal_39912275336 with PID 75 to /usr/local/share/twitchautomator/data/cache/pids/capture_herrmaximal_39912275336.json
-- | -- | -- | --
2022-10-05 18:55:10 | notify | ERROR | Discord error: Request failed with status code 400 ([object Object])
2022-10-05 18:55:10 | helper | SUCCESS | New game saved to cache: Godlike Burger


</body>
</html>

**Comment by MrBrax** [comment]
if you click on the log line text it should make a popup with the stored metadata of that log event

**Comment by Serph91P** [comment]
> if you click on the log line text it should make a popup with the stored metadata of that log event

{
"err": {
"message": "Request failed with status code 400",
"name": "Error",
"stack": "Error: Request failed with status code 400\n at createError (/usr/local/share/twitchautomator/server/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/usr/local/share/twitchautomator/server/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/usr/local/share/twitchautomator/server/node_modules/axios/lib/adapters/http.js:322:11)\n at IncomingMessage.emit (node:events:525:35)\n at endReadableNT (node:internal/streams/readable:1359:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
"config": {
"transitional": {
"silentJSONParsing": true,
"forcedJSONParsing": true,
"clarifyTimeoutError": false
},
"transformRequest": [
null
],
"transformResponse": [
null
],
"timeout": 0,
"xsrfCookieName": "XSRF-TOKEN",
"xsrfHeaderName": "X-XSRF-TOKEN",
"maxContentLength": -1,
"maxBodyLength": -1,
"headers": {
"Accept": "application/json, text/plain, */*",
"Content-Type": "application/json",
"User-Agent": "axios/0.26.0",
"Content-Length": 202
},
"method": "post",
"url": "https://discordapp.com/api/webhooks/radacted",
"data": "{\"content\":\"**herrmaximal is live!**\\nGodlike Burger\\ntest\\n\\nhttps://twitch.tv/herrmaximal\",\"avatar_url\":\"/cache/thumbs/ea3faa8abdf1c0a028b1cf717f97f5c8.jpg\",\"tts\":false}"
},
"status": 400
},
"response": {
"avatar_url": [
"Scheme \"/cache/thumbs/ea3faa8abdf1c0a028b1cf717f97f5c8.jpg\" is not supported. Scheme must be one of ('http', 'https')."
]
}
}

**Comment by MrBrax** [comment]
> "Scheme "/cache/thumbs/ea3faa8abdf1c0a028b1cf717f97f5c8.jpg" is not supported. Scheme must be one of ('http', 'https')."

got it, it's not using the full url

**Comment by Serph91P** [comment]
> > "Scheme "/cache/thumbs/ea3faa8abdf1c0a028b1cf717f97f5c8.jpg" is not supported. Scheme must be one of ('http', 'https')."
> 
> got it, it's not using the full url

yep working again thanks
