### ISSUE TITLE
[Info] Delete Files

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#319]
Should I manualy delete Files via the GUI of LiveStreamDVR or would it be no Problem if they got deletet by another program which I use to convert to h265.

**Comment by MrBrax** [comment]
deleting files would make the list in memory and disk inconsistent which breaks cleanup and some other features

**Comment by Serph91P** [comment]
> deleting files would make the list in memory and disk inconsistent which breaks cleanup and some other features

OK so I should use cleanup Feature to get them "deleted".

**Comment by MrBrax** [comment]
yes or just the delete button on the vod

**Comment by MrBrax** [comment]
if you actually want to delete the entire vod that is, replacing the video file isn't "officially" supported

**Comment by Serph91P** [comment]
> if you actually want to delete the entire vod that is, replacing the video file isn't "officially" supported

Yeah not gonna replace the files, transcoding to tmp directory and after finished moving it to different direcotry but copying everything with it. So the orig Files are not touched at all.

**Comment by Serph91P** [comment]
Will set up the cleanup to be dunno 4 streams so they get deleted quite "fast".

**Comment by MrBrax** [comment]
i'll finally make it remove the vod from the database if the json is removed, was unsure if it would work a long time ago
