### ISSUE TITLE
Video Player not opening on latest master

### ISSUE THREAD

**Issue by McHauge** [MrBrax/LiveStreamDVR#329]
Hi, so I have been using this for a fair bit over the last 2 weeks with no problems, but today I chose to update it, and now the recording and all still works fine, but one thing I used a lot was the ability to playback the video in the browser after and share that link to others so they could pull it down again.

However in the new version, it seems that the Video player is broken or at least it's not linking correctly to it, as I'm not able to playback a recorded file, I can find it locally on the drive. But the Video Player button just gives me this:
![image](https://user-images.githubusercontent.com/31018035/194799970-1ca1b871-87dd-43f3-958d-6b3d8f67b3db.png)

Clicking the link to the segment just returns this instead:
![image](https://user-images.githubusercontent.com/31018035/194800017-a077de23-92d5-4a50-979e-ca4b912b823a.png)
![image](https://user-images.githubusercontent.com/31018035/194799955-62a8ffab-5363-4897-ad53-63fab8a2953b.png)

Before this update, it would give me a player where the viewer had the option to view and download the file directly. This seems to have broken in over the last week.

**Comment by McHauge** [comment]
The version that has worked for the last week or so was pulled before the 29. September, but that's the date I set it up, but it had been lying around for a bit before, without any notifications about an update being available until yesterday. I'm running it on an Unraid server if that makes any difference.

**Comment by MrBrax** [comment]
it's sending the index.html file for the single page app for most routes now, i honestly don't know if it's possible to have both working, gonna have to research real hard for this

**Comment by speedone** [comment]
+1 i have the same problem with all vods.

**Comment by McHauge** [comment]
@MrBrax Can confirm this works again, thank you! I did not expect it to be that fast of a response. Thanks for the work you're doing on this project.

I have one thing that could be nice to have, which would be the ability to live record the VRCDN.live network (in the same way as twitch) over RTMP or RTSP. It has an API for monitoring channel status and viewer counts, so it could be set up the same as for twitch where you just type in the Streamer Name and then it fetches the rest.

For testing you can test against the user/stream:
VRCDN or McHauge
RTMP | rtmp://stream.vrcdn.live/live/vrcdn
RTMP | rtmp://stream.vrcdn.live/live/mchauge

https://vrcdn.live/

API Docs:
https://wiki.vrcdn.live/en/api/documentation
https://api.vrcdn.live/api-docs

I can move it to a separate issue if that is nicer :)

**Comment by MrBrax** [comment]
yes please keep all issues separate

service additions can be quite tough however, as i need to make developer accounts and test stream setups for all of them

**Comment by McHauge** [comment]
I'll not go further with this one, just asked the devs of the platform, and sounds like a major overhaul to the API is in the works, so not worth working on for now, i might come back later in a new request when that comes out :)

Thanks again!
