### ISSUE TITLE
[BUG] Develop crashing on startup after update

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#333]
> Initialising...
Environment: undefined
Running as user undefined
AppRoot: /usr/local/share/twitchautomator
DataRoot: /usr/local/share/twitchautomator/data
Client is built: /usr/local/share/twitchautomator/client-vue/dist/index.html
VOD player is built: /usr/local/share/twitchautomator/twitch-vod-chat/dist/index.html
Chat dumper is built: /usr/local/share/twitchautomator/twitch-chat-dumper/build/index.js
Loading key-value pairs...
Loaded 66 key-value pairs
Loading config...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --enable-source-maps build/server.js
Could not compare version 1.1.4.1 to : Invalid argument not valid semver ('' received)
Initialising...
Environment: undefined
Running as user undefined
AppRoot: /usr/local/share/twitchautomator
DataRoot: /usr/local/share/twitchautomator/data
Client is built: /usr/local/share/twitchautomator/client-vue/dist/index.html
VOD player is built: /usr/local/share/twitchautomator/twitch-vod-chat/dist/index.html
Chat dumper is built: /usr/local/share/twitchautomator/twitch-chat-dumper/build/index.js
Loading key-value pairs...
Loaded 66 key-value pairs
Loading config...

**Comment by MrBrax** [comment]
is that it? nothing more?

doesn't seem like anything is broken

**Comment by Serph91P** [comment]
> is that it? nothing more?
> 
> doesn't seem like anything is broken

thaths the whole log from start to crash:

> yarn run v1.22.19
$ node --enable-source-maps build/server.js
Could not compare version 1.1.4.1 to : Invalid argument not valid semver ('' received)
Initialising...
Environment: undefined
Running as user undefined
AppRoot: /usr/local/share/twitchautomator
DataRoot: /usr/local/share/twitchautomator/data
Client is built: /usr/local/share/twitchautomator/client-vue/dist/index.html
VOD player is built: /usr/local/share/twitchautomator/twitch-vod-chat/dist/index.html
Chat dumper is built: /usr/local/share/twitchautomator/twitch-chat-dumper/build/index.js
Folder '/usr/local/share/twitchautomator/public' does not exist, creating.
Created folder: /usr/local/share/twitchautomator/public
Data folder '/usr/local/share/twitchautomator/data/payloads' does not exist, creating.
Created data folder: /usr/local/share/twitchautomator/data/payloads
Created data folder: /usr/local/share/twitchautomator/data/backup
Data folder '/usr/local/share/twitchautomator/data/backup' does not exist, creating.
Loading key-value pairs...
Loaded 66 key-value pairs
Loading config...
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _Config.loadConfig (/usr/local/share/twitchautomator/server/src/Core/Config.ts:415:28)
    at Function.init (/usr/local/share/twitchautomator/server/src/Core/Config.ts:787:30)
    at Object.<anonymous> (/usr/local/share/twitchautomator/server/src/index.ts:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MrBrax** [comment]
is your config file corrupted? good thing it makes backups

**Comment by Serph91P** [comment]
> is your config file corrupted? good thing it makes backups

you are right it has only 0bytes, but why?

**Comment by MrBrax** [comment]
crash when writing maybe? filesystem corruption? could be anything really

**Comment by Serph91P** [comment]
> crash when writing maybe? filesystem corruption? could be anything really

oh could have been my cache drive running full. Set to move files of it to save from corruption. Was the first time happening.
