### ISSUE TITLE
[Enhancement] Delete files after crash

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#334]
could you implement that after a crash that here are more information or mark the vod or delete the files or reinitilize the recording or download the vod. So it does not stay like empty and says basicaly nothing.
![grafik](https://user-images.githubusercontent.com/8904984/194905767-35c097a1-cb21-4cbb-80a0-55436ebeedfe.png)

**Comment by MrBrax** [comment]
i've found that in most cases a server restart fixes them (or the fixissues button i guess?)

i'm adding more and more checks, but there are many different combinations of broken that i haven't encountered yet

**Comment by MrBrax** [comment]
can you post the json here that includes the basic stuff? no file paths or mediainfo needed

**Comment by Serph91P** [comment]
> can you post the json here that includes the basic stuff? no file paths or mediainfo needed

restart did not fix it. what is going on here?

>  "segments": [
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39898139704) - s202210e03.mp4",
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39914064040) - s202210e08.mp4",
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39921706744) - s202210e11.mp4",
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39927447880) - s202210e12.mp4"
    ],


`{
    "version": 2,
    "type": "twitch",
    "uuid": "cd60b59e-8d90-4f9d-9c27-622275483561",
    "capture_id": "39931344936",
    "streamer_name": "Bonjwa",
    "streamer_id": "73437396",
    "streamer_login": "bonjwa",
    "channel_uuid": "d644bc75-5bd2-40fe-a36f-6e2ee7585bad",
    "chapters": [
        {
            "started_at": "2022-10-10T17:02:58.554Z",
            "game_id": "417752",
            "game_name": "Talk Shows & Podcasts",
            "title": "Bonjwa Briefing mit Leon und Matteo",
            "is_mature": false,
            "online": false,
            "viewer_count": 3576,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/417752.jpg"
        },
        {
            "started_at": "2022-10-10T17:02:58.930Z",
            "game_id": "417752",
            "game_name": "Talk Shows & Podcasts",
            "title": "Bonjwa Briefing mit Leon und Matteo",
            "is_mature": false,
            "online": true,
            "viewer_count": 3576,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/417752.jpg"
        },
        {
            "started_at": "2022-10-10T17:04:17.755Z",
            "game_id": "417752",
            "game_name": "Talk Shows & Podcasts",
            "title": "Bonjwa Briefing mit Leon und Matteo !gheed #Werbung",
            "is_mature": false,
            "online": true,
            "viewer_count": 3942,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/417752.jpg"
        },
        {
            "started_at": "2022-10-10T17:04:18.262Z",
            "game_id": "417752",
            "game_name": "Talk Shows & Podcasts",
            "title": "Bonjwa Briefing mit Leon und Matteo !gheed #Werbung",
            "is_mature": false,
            "online": true,
            "viewer_count": 3942,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/417752.jpg"
        },
        {
            "started_at": "2022-10-10T18:04:10.738Z",
            "game_id": "509658",
            "game_name": "Just Chatting",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 6490,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/509658.jpg"
        },
        {
            "started_at": "2022-10-10T18:04:10.751Z",
            "game_id": "509658",
            "game_name": "Just Chatting",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 6490,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/509658.jpg"
        },
        {
            "started_at": "2022-10-10T20:47:37.472Z",
            "game_id": "1906677264",
            "game_name": "Rogue: Genesia",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 7133,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/1906677264.jpg"
        },
        {
            "started_at": "2022-10-10T20:47:37.723Z",
            "game_id": "1906677264",
            "game_name": "Rogue: Genesia",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 7133,
            "box_art_url": "https://lsdvr.mebert-server.de/cache/covers/1906677264.jpg"
        },
        {
            "started_at": "2022-10-10T22:06:15.060Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 4088,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:06:19.569Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 4088,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:06:30.880Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 4088,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:06:37.687Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 4088,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:06:57.964Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund mit Lion",
            "is_mature": false,
            "online": true,
            "viewer_count": 4088,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:07:13.025Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund mit Lion",
            "is_mature": false,
            "online": true,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:07:16.844Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund mit Lion",
            "is_mature": false,
            "online": true,
            "viewer_count": 3934,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:07:19.191Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 3934,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:07:22.269Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund",
            "is_mature": false,
            "online": true,
            "viewer_count": 3934,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:07:49.650Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund mit Lion",
            "is_mature": false,
            "online": true,
            "viewer_count": 3934,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-10T22:07:47.775Z",
            "game_id": "556660222",
            "game_name": "Marauders",
            "title": "Mental am Abgrund mit Lion",
            "is_mature": false,
            "online": true,
            "viewer_count": 3934,
            "box_art_url": "redacted"
        },
        {
            "started_at": "2022-10-11T02:20:12.123Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:20:19.022Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:20:42.550Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:20:42.700Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:21:04.162Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:21:13.805Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:21:34.012Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        },
        {
            "started_at": "2022-10-11T02:21:34.900Z",
            "game_id": "",
            "game_name": "",
            "title": "Streamende",
            "is_mature": false,
            "online": true,
            "viewer_count": 494,
            "box_art_url": ""
        }
    ],
    "segments": [
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39898139704) - s202210e03.mp4",
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39914064040) - s202210e08.mp4",
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39921706744) - s202210e11.mp4",
        "/usr/local/share/twitchautomator/data/storage/vods/bonjwa/Season 202210/bonjwa (2022) (39927447880) - s202210e12.mp4"
    ],
    "is_capturing": false,
    "is_converting": false,
    "is_finalized": false,
    "duration": 0,
    "saved_at": "2022-10-11T02:21:37.148Z",
    "created_at": "2022-10-10T13:42:53.635Z",
    "not_started": false,
    "prevent_deletion": false,
    "failed": false,
    "bookmarks": [],
    "cloud_storage": false,
    "stream_resolution": "1080p60",
    "capture_started": "2022-10-10T13:43:02.369Z",
    "capture_started2": "2022-10-10T13:43:13.721Z",
    "started_at": "2022-10-10T13:41:30.000Z",
    "stream_number": 13,
    "stream_season": "202210",
    "stream_absolute_season": 1
}`

**Comment by MrBrax** [comment]
the fact that a single vod has multiple segments is more of an issue here, that should definitely not be happening

**Comment by MrBrax** [comment]
are you not getting any "fix;;" or bright colored messages at boot for this vod?

**Comment by MrBrax** [comment]
![1665483486756](https://user-images.githubusercontent.com/1517911/195064782-0a34b6f4-b1e7-4897-9011-00bd9db27a63.png)
it feels like this one should be triggered

**Comment by Serph91P** [comment]
> are you not getting any "fix;;" or bright colored messages at boot for this vod?

There are multiple vods that are like this I did not touch any file. Will check the log later again if there is said message.

**Comment by MrBrax** [comment]
i'm enhancing the add segment message, but generally there should never be more than one segment per vod. has this happened before?

**Comment by Serph91P** [comment]
> i'm enhancing the add segment message, but generally there should never be more than one segment per vod. has this happened before?

Like I wrote there are other streams that have that. But will look at it later.

**Comment by Serph91P** [comment]
> can you post the json here that includes the basic stuff? no file paths or mediainfo needed

it happend all on the same day 10.10 but for different reason two have no chapters the other has chapters but is still "running".

**Comment by MrBrax** [comment]
you must have a really strange setup going on honestly

**Comment by MrBrax** [comment]
current master now has a few warnings when more than 1 segment is added to a vod, keep a lookout for that
