### ISSUE TITLE
[Bug] Mobile browser formatting issue after update

### ISSUE THREAD

**Issue by akumar95** [MrBrax/LiveStreamDVR#337]
![E1F5A02F-7BAD-4075-A565-3C2D9D3E7D76](https://user-images.githubusercontent.com/39446555/195621099-5935591c-65c9-46e0-934f-1271052195ca.jpeg)

Since the latest update it seems when browsing the application via mobile browser the sidebar extends too far. Previously it would dynamically change based on mobile screen size allowing for ease of use but now I’m unable to use the application or alter settings. 

Apologies for no tests I’m on mobile github. Let me know if you need anything.

**Comment by Serph91P** [comment]
@MrBrax when will it be pushed to master?

**Comment by MrBrax** [comment]
a few risky additions, let's hope it doesn't break
