### ISSUE TITLE
Docker setup crash after configuration

### ISSUE THREAD

**Issue by qqaatw** [MrBrax/LiveStreamDVR#341]
After setting client id and secret of twitch on the web interface (app url was set `debug`), the web server created in the container immediately crashed so that I could no longer connect to the web interface unless the config file was restored to default, and the container was restarted.

I'm not sure if the client and secret are incorrect, but normally, I think the web server should not crash even if the configuration is incorrect or the connection to twitch is blocked for any reason. 

Here is the error message from `docker logs`:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

<ref *1> Error: getaddrinfo EAI_AGAIN id.twitch.tv
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    at __node_internal_ (node:internal/errors:706:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
```

**Comment by qqaatw** [comment]
For the error message itself, this post provides some clues:

https://stackoverflow.com/questions/65925304/eai-again-when-running-npm-install-in-docker-container

Adding `network_mode: host` to `docker-compose.yml` fixes it.

**Comment by MrBrax** [comment]
are you running it on a regular docker setup and not unraid? haven't heard of this issue before

**Comment by qqaatw** [comment]
Yes it's a regular docker setup on a Synology NAS.

**Comment by MrBrax** [comment]
i forgot i had this added in my docker-compose file and it broke for me, so it's a case-by-case basis and not standard
