### ISSUE TITLE
[BUG] VOD Segment mix up.

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#342]
Cought it doing it, added another segment to a stream that ended dunno why. Attached full log. Just saw it happening Stream was ending and before the file was transoced another one was added to the stream. Like 4 is beeing remuxed and 3 is beeing added while it is remuxed.

[error_log.txt](https://github.com/MrBrax/LiveStreamDVR/files/9841562/error_log.txt)

**Comment by MrBrax** [comment]
and you did not use fixissues this time either? is this on the latest master update?

**Comment by Serph91P** [comment]
I did use the button. Thought it would be visible in the logs. That's why I attached the whole log.

**Comment by MrBrax** [comment]
the thing that probably messes stuff up here is that the vod folder has the same name for every vod, causing the rebuild segments function to break

**Comment by Serph91P** [comment]
> if you use it while the vod is doing anything by itself it can really mess stuff up, it should be completely done before you click it

Then maybe show it only when it's done dunno. Just did what you suggested last time. I mean I clicked it as soon as I saw it because I thought something fucked up. Just a thought shoulnt this only happen in the rarest case or something. Just trying to be helpful here 😅

**Comment by MrBrax** [comment]
i could add a warning when clicking it, the reason it's always available is because the server could have been restarted in between actions so it doesn't know what stage it's on, if it's actually running or just flagged to be, so the option is there to fix it when you know it's broken for real
