### ISSUE TITLE
[Info] cannot access gui

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#350]
started recieving those errors when trying to access the gui. Master aswell as Develop:

![grafik](https://user-images.githubusercontent.com/8904984/198270838-e80d531d-1a40-4b9f-805e-2ea2b8ecce1a.png)

My guess would be Authelia changed something since the last update. Besides /api is there anything else that needs to be accessible without auth? Got those setup sofar and was working before.
 ```
  resources:  
        - "^/api([/?].*)?$"  
        - "^/identity.*$"  
        - "^/triggers.*$"  
        - "^/meshagents.*$"  
        - "^/meshsettings.*$"  
        - "^/agent.*$"  
        - "^/control.*$"  
        - "^/meshrelay.*$"  
        - "^/wl.*$"  
      policy: bypass  
```
if I clear the cache and authenticate again it is working again.

**Comment by MrBrax** [comment]
this is probably a bit out of scope if you're using another service for authentication, but no, api is really the only thing on the server itself

**Comment by MrBrax** [comment]
you could check what the result is of the xhr request to the settings endpoint, probably a 403

**Comment by Serph91P** [comment]
> you could check what the result is of the xhr request to the settings endpoint, probably a

> you could check what the result is of the xhr request to the settings endpoint, probably a 403

actually its a 302 it tries to refer me to authelia again, which it cant. I think I fixed it. editing the nginx config to only do this on the main page. and if you try to get access to other pages it wont load ok. Hope I fixed it. Thanks

**Comment by Serph91P** [comment]
> > you could check what the result is of the xhr request to the settings endpoint, probably a
> 
> > you could check what the result is of the xhr request to the settings endpoint, probably a 403
> 
> actually its a 302 it tries to refer me to authelia again, which it cant. I think I fixed it. editing the nginx config to only do this on the main page. and if you try to get access to other pages it wont load ok. Hope I fixed it. Thanks



> you could check what the result is of the xhr request to the settings endpoint, probably a 403

hmm what is the adress for the websocket?

**Comment by MrBrax** [comment]
/socket
forgot that one

**Comment by Serph91P** [comment]
> /socket

any other subfolders that need to be excluded?

**Comment by MrBrax** [comment]
is it not easier to just make it a blacklist instead? if you allow all the required ones you might as well make the entire thing public

```
/vodplayer
/vods
/saved_vods
/saved_clips
/cache
/logs
```

**Comment by MrBrax** [comment]
is there not a way to disable authentication for that block completely? on that authelia thing i mean. different api routes have different authentication requirements, so adding a blanket over everyting would just break everything if you wanted it private for just certain things. the entire web interface is cached on the client, all the data is fetched from the api

**Comment by Serph91P** [comment]
> is there not a way to disable authentication for that block completely? on that authelia thing i mean. different api routes have different authentication requirements, so adding a blanket over everything would just break everything if you wanted it private for just certain things. the entire web interface is cached on the client, all the data is fetched from the api

hmmm yeah get where you are going, the porblem with that is if I enter domain.com/settings for example I would get in without login.

**Comment by Serph91P** [comment]
> the settings are fetched from /api anyway, the /settings is just a clientside page rendered in your browser only. no request is ever made to /settings on the server due to how single page applications work 👍 someone crafty would be able to hijack into the client router and change the page to settings which would fetch the fields and values from /api

will leave it with api and socket "exposed". btw found another one. If you delete the password from the interface and save. It still asks for it in ikognito mode.
