### ISSUE TITLE
[BUG] Channels Settings Page

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#358]
This page is not working correctly. If you press on one streamer and change settings. It always says Channel '{{0}}' updated. And then it does not matter on what channel you click it always shows the same settings. Only the name and uuid etc change but for example "Don't record streams (disable capture completely)" cannot be set for one channel.
![grafik](https://user-images.githubusercontent.com/8904984/199191517-6283a6ee-ee2d-41b2-a2c7-dd028e8a1e2a.png)
![grafik](https://user-images.githubusercontent.com/8904984/199191639-9964fe8a-a956-455b-95d8-b87e82a4633e.png)

**Comment by MrBrax** [comment]
that must have been there for a while, it probably thought the form was just the same every time
