### ISSUE TITLE
Option to change date format

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/LiveStreamDVR#359]
Is it possible to change the date format from YYYY-DD-MM to dd-mm yyyy?

This is especially useful when exporting files using ftp so I can order the files correctly by using the date.

**Comment by MrBrax** [comment]
uhh how are you sorting something that's not in biggest to smallest order? 🤔 

but yeah sure that could be possible

**Comment by CappiSteijns** [comment]
For me the use case would be something like this. But then with the video files, when ordering "name" it will show the vids from old to new. Hope it makes sense. And yyyy-dd-mm is a very American thing
![image](https://user-images.githubusercontent.com/84481241/199497309-a7d90d2a-8a30-4aaa-b1e3-08dde620e8c8.png)

**Comment by MrBrax** [comment]
but.. when you sort with the iso standard it will order them correctly too, yeah?

**Comment by CappiSteijns** [comment]
Geuss it does but feels uncomfortable using yyyy-dd-mm :P

**Comment by MrBrax** [comment]
yyyy-mm-dd you mean? because the american way won't order properly
