### ISSUE TITLE
Twitch authentication "Access token is not a user token."

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/LiveStreamDVR#365]
When trying to authenticate Twitch using "buttons.authmethod1" and "buttons.authmethod2" I get the following:

![image](https://user-images.githubusercontent.com/84481241/200882230-12de0fa5-f121-4f40-9aa5-446c4725a4dd.png)

For some reason it takes me to the following link:
![image](https://user-images.githubusercontent.com/84481241/200882353-09594107-aa41-4efe-8efc-3370efcc50f2.png)

Log:
![image](https://user-images.githubusercontent.com/84481241/200883069-a6cf05e3-9182-4487-91c6-390c829197b6.png)

If this was working would that mean you can use the "VOD Download" for sub only VODS? (if not how can I set that up, can't find any location to use a cookie file) 

Thanks

**Comment by MrBrax** [comment]
That is only required when using user tokens, i should disable that when not enabled.

OAuth token used for subscriptions is placed in `/config/twitch_oauth.txt`, there is no GUI for this.
