### ISSUE TITLE
How to use the LiveStreamDVR safely?

### ISSUE THREAD

**Issue by devchae1** [MrBrax/LiveStreamDVR#368]
In order to use the Twitch API, we have no choice but to open port 443 to everyone.
However, there are sensitive personal information such as client id and client secret in the config of the homepage. How can I hide these?
How can I use LiveStreamDVR safely?

**Comment by MrBrax** [comment]
set a password in the config or set your reverse proxy to only expose `/api/v0/hook*`

**Comment by devchae1** [comment]
> proxy

Thank you!
