### ISSUE TITLE
Twitch inserted "prelude" in all new vods?

### ISSUE THREAD

**Issue by Coalbus** [MrBrax/LiveStreamDVR#371]
Since at least Nov 9th, live-captured VODs include a little 10ish second prelude that is clearly from Twitch themselves. It says "Preparing your stream..." and has random dumb message beside it. See here: [https://i.imgur.com/kCv448t.png](https://i.imgur.com/kCv448t.png) and here: [https://i.imgur.com/cvQJ8ut.png](https://i.imgur.com/cvQJ8ut.png) for examples.

This is probably entirely outside your control, but do you have any idea why those are in my recordings now or if there's a way to make it stop happening? As far as I can tell, it's playing over the stream so for as long as that screen is visible I'm missing out on recording whatever is happening on stream. Not that there's much happening on stream in the first 10 seconds but it still bother's me that Twitch insists on doing this. 

I also checked my backup stream recorder which is just a dead simple python/streamlink script and it's happening there too, so it's not just LiveStreamDVR. Figured I'd ask here since you probably know more about what's going on with the technical side of things more so than most other people and maybe even know some way to make it stop.

Thanks!

**Comment by MrBrax** [comment]
does not happen for me it seems, might be some country-based thing. i have read about it though.

this is up to streamlink, if they fix it, a new docker push would include it

**Comment by MrBrax** [comment]
i have now changed the duration field from file to video, seems like file kept the full stream duration with ads but video cut them out. the difference on a very long stream can be **40+ minutes lost**

not a very good situation at all, this

**Comment by MrBrax** [comment]
fixed with new streamlink version, and i added stream pause logging

**Comment by akumar95** [comment]
Quick question. Are stream pauses including ad breaks? I personally have twitch turbo so I do not have have ads but for some reason all of my recorded vods have stream pauses that are in the >15 range resulting in significant portions missing.

**Comment by MrBrax** [comment]
yup those are ad breaks

**Comment by akumar95** [comment]
Ahhh I see. Since streamlink is used is it possible to implement twitch turbo auth in order for stream pauses to not happen? Seems possible to do this by glancing over the documentation referenced by this streamlink issue: https://github.com/streamlink/streamlink/issues/4949#issue-1445229121

https://streamlink.github.io/latest/cli/plugins/twitch.html#authentication

**Comment by MrBrax** [comment]
it is, check the help&tips section in settings for instructions
