### ISSUE TITLE
arm support?

### ISSUE THREAD

**Issue by heryoff** [MrBrax/LiveStreamDVR#385]
Please 👉 👈

**Comment by MrBrax** [comment]
uhh i actually have no idea how to do that, but building it manually should work?

**Comment by heryoff** [comment]
Yeah I thought the same, but It gives me "exec format error"
I'll try again, and post the logs if there is any

**Comment by heryoff** [comment]
```
Attaching to livestreamdvr_web_1
web_1  | exec /usr/local/bin/yarn: exec format error
livestreamdvr_web_1 exited with code 1
```

**Comment by MrBrax** [comment]
hmm, shouldn't the correct arch of the node image be downloaded when you build it manually?

**Comment by heryoff** [comment]
I actually don't know, if you suggest anything I can try and tell you right now

**Comment by MrBrax** [comment]
if there's no solution to docker you should be able to run it bare metal

**Comment by heryoff** [comment]
Yeah but I don't usually run stuff on bare metal, I'd like to keep all things organized under docker. 
Anyway I'll keep looking onto this and see if I can find any fix

**Comment by MrBrax** [comment]
what if you edit the dockerfile and change the top to something like `arm64v8/node:18-bullseye-slim` or whichever your pi's arm version is at

**Comment by heryoff** [comment]
```
Step 6/31 : COPY --chown=node:node --chmod=775 ./common /usr/local/share/twitchautomator/common
the --chmod option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
ERROR: Service 'web' failed to build : Build failed
```

**Comment by heryoff** [comment]
Tried with ` DOCKER_BUILDKIT=1 docker-compose up --build`

```
 > [ 8/20] RUN cd /usr/local/share/twitchautomator/twitch-chat-dumper     && yarn install --immutable --immutable-cache     && yarn build     && rm -rf node_modules     && rm -rf .yarn/cache     && yarn cache clean --all:                   
#10 0.906 ➤ YN0000: ┌ Resolution step                                           
#10 1.050 ➤ YN0000: └ Completed                                                 
#10 1.076 ➤ YN0000: ┌ Fetch step
#10 1.162 ➤ YN0013: │ esbuild-linux-arm64@npm:0.15.12 can't be found in the cache and will be fetched from the remote registry
#10 1.162 ➤ YN0056: │ esbuild-linux-arm64@npm:0.15.12: Cache entry required but missing for esbuild-linux-arm64@npm:0.15.12
#10 1.165 ➤ YN0013: │ esbuild-windows-arm64@npm:0.15.12 can't be found in the cache and will be fetched from the remote registry
#10 1.165 ➤ YN0056: │ esbuild-windows-arm64@npm:0.15.12: Cache entry required but missing for esbuild-windows-arm64@npm:0.15.12
#10 1.283 ➤ YN0000: └ Completed in 0s 206ms
#10 1.283 ➤ YN0000: Failed with errors in 0s 381ms
------
executor failed running [/bin/sh -c cd /usr/local/share/twitchautomator/twitch-chat-dumper     && yarn install --immutable --immutable-cache     && yarn build     && rm -rf node_modules     && rm -rf .yarn/cache     && yarn cache clean --all]: exit code: 1
ERROR: Service 'web' failed to build : Build failed
```

**Comment by MrBrax** [comment]
![1669905502969](https://user-images.githubusercontent.com/1517911/205080683-e1809ec2-4955-41e9-a695-073152728926.png)

adding these in all `.yarnrc.yml` files might help?

**Comment by heryoff** [comment]
I don't have those files, where are they located?

**Comment by MrBrax** [comment]
in each package directory, like server, client-vue, twitch-chat-dumper, twitch-vod-chat

**Comment by heryoff** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/26651237/205081920-56dc138d-d650-4b1b-b57d-aa0f594b15e9.png">
Am I doing something wrong?

**Comment by heryoff** [comment]
Ok found it, I had a typo in the filename

**Comment by heryoff** [comment]
Still having errors
```
 > [ 8/20] RUN cd /usr/local/share/twitchautomator/twitch-chat-dumper     && yarn install --immutable --immutable-cache     && yarn build     && rm -rf node_modules     && rm -rf .yarn/cache     && yarn cache clean --all:                                                                         
#12 0.767 ➤ YN0000: ┌ Resolution step                                                             
#12 0.895 ➤ YN0000: └ Completed                                                                   
#12 0.922 ➤ YN0000: ┌ Fetch step
#12 1.007 ➤ YN0013: │ esbuild-linux-arm64@npm:0.15.12 can't be found in the cache and will be fetched from the remote registry
#12 1.008 ➤ YN0056: │ esbuild-linux-arm64@npm:0.15.12: Cache entry required but missing for esbuild-linux-arm64@npm:0.15.12
#12 1.010 ➤ YN0013: │ esbuild-windows-arm64@npm:0.15.12 can't be found in the cache and will be fetched from the remote registry
#12 1.010 ➤ YN0056: │ esbuild-windows-arm64@npm:0.15.12: Cache entry required but missing for esbuild-windows-arm64@npm:0.15.12
#12 1.131 ➤ YN0000: └ Completed in 0s 208ms
#12 1.131 ➤ YN0000: Failed with errors in 0s 366ms
------
executor failed running [/bin/sh -c cd /usr/local/share/twitchautomator/twitch-chat-dumper     && yarn install --immutable --immutable-cache     && yarn build     && rm -rf node_modules     && rm -rf .yarn/cache     && yarn cache clean --all]: exit code: 1
ERROR: Service 'web' failed to build : Build failed
```

**Comment by MrBrax** [comment]
try running yarn install in those folders too after changing the configs

i'll probably make an arm version after this so it won't be required each time

**Comment by heryoff** [comment]
Ok thanks, then I'm going to wait for a official version from you since I'm not really that good with those kind of stuff

**Comment by MrBrax** [comment]
i don't really have a way to test if it's working, so i can't really verify if this works

**Comment by heryoff** [comment]
Sorry for the late response, but if you need someone to test it, I can do it for you

**Comment by MrBrax** [comment]
i do have a spare rpi 3b+ at home that i might be able to test on but not certain

**Comment by Rajpratik71** [comment]
HI @MrBrax , @heryoff ,

It is do able but

 https://github.com/MrBrax/LiveStreamDVR/blob/31a6e3fa23a395db0090ae26ace2f9d6acd8c15f/docker/fetch-tdl.sh#L11 

will conflict as x64 binary download is harcoded

**Comment by MrBrax** [comment]
that one could have a different version i suppose, but i wouldn't recommend encoding any video with it at least

**Comment by Rajpratik71** [comment]
yes, there we have to use arm binaries of TwitchDownloader.

**Comment by Rajpratik71** [comment]
I wonder, is "TwitchDownloader" a necessary component/dependency or we can remove it  ?

**Comment by MrBrax** [comment]
it's not necessary, no. downloading chats from vods is only possible with that one now i think

**Comment by luckiestone** [comment]
> 

I've tested it, and it's doable, after some yarn reinstall and nodejs update.

**Comment by heryoff** [comment]
If anyone comes up with an Docker image, I'll be glad to help testing

**Comment by luckiestone** [comment]
I've tested on to arm ubuntu, and the app works without any issue. Maybe an official modification and push?
Here the steps:
1. Clone the repo
2. Modify the files https://github.com/MrBrax/LiveStreamDVR/issues/385#issuecomment-1333864948
3. yarn and node update
4. `docker-compose up --build -d` and there's no need to run yarn install in those `.yarnrc.yml` folders

**Comment by luckiestone** [comment]
> > yarn and node update
> 
> what did you mean by this? wouldn't yarn update upgrade dependencies?

I have no idea what's the reason, but unless an reinstall of yarn, I was keeping getting this error. It's exactly the same as the one here: https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by luckiestone** [comment]
Update: No need to modify all `.yarnrc.yml` files except the one in submodule `twitch-vod-chat`, and `yarn install` is needed to run in each sub folder. After all that, an ARM linux docker version is built.

**Comment by MrBrax** [comment]
nice, i need to fix issues preventing `twitch-vod-chat` from upgrading, and i'll try to make an arm published image

**Comment by MrBrax** [comment]
yarnrc now fixed on dev branch, so everything should probably be compatible with docker now? i made it publish to dockerhub but i have no idea if it actually works

**Comment by MrBrax** [comment]
ok i finally got it to push to dockerhub, but the build time went from 5 minutes to 2 hours lol

considering it actually built i suppose it should be working?

**Comment by luckiestone** [comment]
Update: ARM support is good now I think, for both docker hub and manual build. No more additional modifications needed now for manual build, git clone and docker-compose and done.
