### ISSUE TITLE
API client id not set, can't setup axios

### ISSUE THREAD

**Issue by bondurantdt** [MrBrax/LiveStreamDVR#387]
Trying to use the new version on Ubuntu 20.04. Have everything built and nginx configured to reverse proxy. When I run yarn run start in ./server, the server starts, but I do get a log of

Setting up axios...
API client id not set, can't setup axios

When I go to the server in a browser I get this AxiosError: Request failed with status code 404 and I cant get much to load.

Any ideas? Thanks!

**Comment by MrBrax** [comment]
client id is not set in the config

**Comment by bondurantdt** [comment]
Never mind, just needed to modify my nginx config, it still had references to the old php app.
