### ISSUE TITLE
HTTP_PROXY not working

### ISSUE THREAD

**Issue by luckiestone** [MrBrax/LiveStreamDVR#392]
I've set environment variable HTTP_PROXY in the container, but it does not seem to work. I can't find any request log in my proxy server. It worked fine with some other containers, just have no idea why it just does not work this time.

**Comment by MrBrax** [comment]
that's not something i've added, is that a docker native thing?

**Comment by luckiestone** [comment]
https://docs.docker.com/network/proxy/
I guess it's a native thing, I added HTTP_PROXY and then run it, just not working. I'll do some more google work.

**Comment by MrBrax** [comment]
is it a general proxy thing you want or just ad filtering?

**Comment by luckiestone** [comment]
> is it a general proxy thing you want or just ad filtering?

a global proxy

**Comment by MrBrax** [comment]
alright, yeah i don't really know anything about proxies since i haven't used one in 15 years, the docs say to change the docker client settings but that's about it

**Comment by luckiestone** [comment]
> alright, yeah i don't really know anything about proxies since i haven't used one in 15 years, the docs say to change the docker client settings but that's about it

thanks, I'll try that

**Comment by MrBrax** [comment]
also don't people use vpn's nowadays for that kinda stuff? i feel like proxies were the proto-vpns of the 1990s-2000s

**Comment by luckiestone** [comment]
> 

My local ISP does not have a consistent reliable and fast connection to twitch. I've done some tests, works fine with native ubuntu server and a windows11 WSL2 docker with proxy, it just won't work at my DSM NAS server. I think I should blame synology cuz it's an obscure linux based system.
BTW, if I add a channel, and it's already live, will this app start to record this live at some time?

**Comment by MrBrax** [comment]
i'm not sure i follow, why should a proxy change the reliability?

>  BTW, if I add a channel, and it's already live, will this app start to record this live at some time?

if it encounters a chapter update yes, or you can force record

**Comment by luckiestone** [comment]
It's a censorship thing, and I use proxy to bypass that.

**Comment by MrBrax** [comment]
i just realised now, you're setting both http and https env variables right?

**Comment by luckiestone** [comment]
> 

It was only http at first and it didn't work, then I added https one I'm not 100% sure cuz I've deleted the container. Will build one and find out.

**Comment by MrBrax** [comment]
everything uses https today so only http would definitely not work
