### ISSUE TITLE
hook FATAL Invalid signature check for message

### ISSUE THREAD

**Issue by pressheart** [MrBrax/LiveStreamDVR#393]
Hi I keep getting fatal webhook error. Can anyone help me understand what this is ane tell me how to fix it?
![Screenshot_20221218_114625_Firefox](https://user-images.githubusercontent.com/18250553/208279108-52e650f2-b704-43d6-98a8-0929fa99df88.jpg)
![Screenshot_20221218_114853_Firefox](https://user-images.githubusercontent.com/18250553/208279113-aa698f1c-18cb-4c51-a60d-0fdc8b209901.jpg)
![Screenshot_20221218_115117_Firefox](https://user-images.githubusercontent.com/18250553/208279112-b8caaaed-990c-4419-930c-ae9187ed46eb.jpg)

![Screenshot_20221218_115309_Firefox](https://user-images.githubusercontent.com/18250553/208279114-6b7548ac-2544-449d-b46a-bddba4070c93.jpg)

**Comment by MrBrax** [comment]
this only really happens if the eventsub secret has changed, does a resubscribe to the channels fix it?

**Comment by pressheart** [comment]
Deleting channels and resubbing helped. Thanks!

Also may I ask where the default eventsub secret comes from? Is there a need to make my own?

**Comment by MrBrax** [comment]
it should get generated on first launch, you can set your own in the settings somewhere
