### ISSUE TITLE
Error banner of pipenv

### ISSUE THREAD

**Issue by luckiestone** [MrBrax/LiveStreamDVR#398]
Hello, I've done some issues search and found that the pipenv error or something else showing not found should not affect anything.
Here's a screenshot of those not found:
![image](https://user-images.githubusercontent.com/35324456/209286750-b7ce3310-13c9-4c53-8ee4-f2c05ba3a689.png)
But the error banner shown on top of dashboard(pic below) is somewhat annoying, and is there a way to just not show these errors which won't affect anything?
![image](https://user-images.githubusercontent.com/35324456/209286296-6cf94e01-0e67-4f70-baaa-8ad7d10bb363.png)

**Comment by MrBrax** [comment]
you're right, pipenv is not used, just a relic from the old version. probably gonna remove it completely some day or integrate it again
