### ISSUE TITLE
How to change storage directory in config?

### ISSUE THREAD

**Issue by tylerdak** [MrBrax/LiveStreamDVR#405]
I'd like to have my storage directory placed in a different location than LSDVR's data directory, because I keep my configs and my media in separate locations on my host drive. Is there a setting that lets me change this already? I couldn't find it under Storage in Config.

**Comment by MrBrax** [comment]
add volume mappings in docker for `/usr/local/share/twitchautomator/data` or use `--dataroot` when launching via node

**Comment by tylerdak** [comment]
I tried making one mapping for the twitchautomator/data and one for twitchautomator/data/storage but I can't separate them like that. Ideally the storage location could be mapped to some other path (i.e. /media/storage) instead of twitchautomator/data/storage so I could put them on different drives.

Instead, my work around was to map each individual subdirectory separately as such:
```
volumes:
      - ./appdata/twitch-dvr/data/cache:/usr/local/share/twitchautomator/data/cache
      - ./appdata/twitch-dvr/data/config:/usr/local/share/twitchautomator/data/config
      - ./appdata/twitch-dvr/data/logs:/usr/local/share/twitchautomator/data/logs
      - ./appdata/twitch-dvr/data/payloads:/usr/local/share/twitchautomator/data/payloads
      - /server/media/twitch:/usr/local/share/twitchautomator/data/storage
```
