### ISSUE TITLE
Can't subscribe to events for whatever reason

### ISSUE THREAD

**Issue by Slopz** [MrBrax/LiveStreamDVR#412]
I'm hosting LiveStreamDVR via Docker behind Cloudflare's proxy. I created a new app on dev.twitch.tv and set the OAuth Redirect URL to https://livestreamdvr.mydomain.com/api/v0/twitch/callback. 

Whenever I try to use the "App" auth type, I get this timeout error
```
2023-02-21 09:14:55.243 | tw.ch.subWebhook <INFO> Subscribe to 123456789:stream.online (channel)
2023-02-21 09:14:55.246 | tw.ch.subWebhook <INFO> Subscribe request for 123456789:stream.online (channel) sent, awaiting response...
2023-02-21 09:15:05.249 | tw.ch.subWebhook <ERROR> Subscription for 123456789:stream.online (channel) failed, no response received within 10 seconds.
/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchChannel.ts:1737
                            reject(new Error("Timeout, no response received within 10 seconds."));
                                   ^
Error: Timeout, no response received within 10 seconds.
    at Timeout._onTimeout (/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchChannel.ts:1737:36)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Node.js v18.12.1
```

However, when I set the auth type to user with the same credentials, I get this
```
2023-02-21 09:22:31.992 | tw.ch.subWebhook <INFO> Subscribe to 123456789:stream.online (channel)
2023-02-21 09:22:32.193 | tw.ch.subWebhook <ERROR> Could not subscribe to 123456789:stream.online: Request failed with status code 400 / auth must use app access token to create webhook subscription
```
I can also confirm that the user auth works and it shows me as being authenticated when checking the Twitch login status.

So it's definitely not a network issue. I can also add channels and force record just fine...but for whatever reason I can't get the app auth to work. 

What am I doing wrong? Thanks!

**Comment by MrBrax** [comment]
is the external accessible in a web browser? do you get log output when you visit it?

> set the OAuth Redirect 

i don't think the webhook url thing is called that, it should be another option where you put the hook into

**Comment by Slopz** [comment]
> is the external accessible in a web browser? do you get log output when you visit it?
By external I assume you mean the public URL? If so, then yes, LiveStreamDVR is accessible from my domain and I get log output with different requests from my IP. 

> i don't think the webhook url thing is called that, it should be another option where you put the hook into
When I created an app on dev.twitch.tv, it asked me for a OAuth Redirect URL, so I set it to https://livestreamdvr.mydomain.com/api/v0/twitch/callback. I then entered the app credentials and tried to subscribe to a channel's events. 
Was I supposed to set up a webhook somewhere in LiveStreamDVR as well?

**Comment by MrBrax** [comment]
wow i really do forget things quickly, haven't gotten back into the project again so i don't really have the flow remembered...

this has happened to people before but it was usually a firewall issue

**Comment by Slopz** [comment]
Are there any ports I should open?

**Comment by MrBrax** [comment]
have you tested it outside your environment? could the cloudflare stuff maybe do their ip check thing which makes it time out?

**Comment by Slopz** [comment]
Managed to make it work, turns out Cloudflare's "Bot Fight Mode" prevented access to "/api/v0/hook/twitch" so anyone that's facing the same issue, you must turn off Bot Fight Mode as firewall rules can't bypass it. 


Thanks for your help!
