### ISSUE TITLE
SFTP Error Code 1

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#413]
Generated a keypair and copied the public key to the server. Still getting Error Code 1. Where would the application expect the key to be?
Running in Docker on a vps an trying to copy files away from it since only little space.

**Comment by MrBrax** [comment]
it might be an user issue, are you adding the key stuff to the node user? i think that's the one running everything at least. you could try the rclone stuff otherwise

**Comment by Serph91P** [comment]
> it might be an user issue, are you adding the key stuff to the node user? i think that's the one running everything at least. you could try the rclone stuff otherwise

yeah thats propably the problem, I think I used another user.
