### ISSUE TITLE
API requires UUID instead of username

### ISSUE THREAD

**Issue by makiele** [MrBrax/LiveStreamDVR#417]
Hi

Updated LiveStreamDVR for the first time in a while and noticed that the API to force record stopped working again (#256 was my issue last time).

I just found out that the command now requires the UUID of the channel instead of the username - using the username in the api call returns `{"status":"ERROR","message":"Channel not found"}`

any chance you can change this back to username? looking up the UUIDs for every streamer is a little inconvenient.

thanks again for your amazing work

**Comment by MrBrax** [comment]
the entire channel route uses the same unique identifier for all actions so not really possible without some rewrites i think. could maybe find a solution somehow but i'm not sure.

do you have dozens of channels? getting the id could be as quick as right clicking on the channel name in the sidebar and copying the link, the uuid will be in the hash

**Comment by makiele** [comment]
got it - for my script itself it's not that much of a hassle, as it's a one-time job. just thought the general usage of the api gets a little inconvenient if you have to look up the uuid every time. nevertheless, i totally get that my usage of livestreamdvr is an edge case, so i understand that it's not worth the time.

don't know if you want to keep the issue open for further consideration or just close it.

thank you

**Comment by MrBrax** [comment]
pushed untested stuff to develop branch where 'name' can be used for all channel operations, uses the internal channel name/login

**Comment by makiele** [comment]
thank you! will look into it
