### ISSUE TITLE
Using Stream Title or Game in the file name of vods?

### ISSUE THREAD

**Issue by Johnnycyan** [MrBrax/LiveStreamDVR#428]
Unless I'm missing something, I can't find a way to do this. Is this currently possible? If not then I would love for it to be implemented. I love the program <3

**Comment by MrBrax** [comment]
it kinda works against itself as the title may not be set until after the stream goes live, or if the streamer has just been added there would be no title at all

**Comment by Johnnycyan** [comment]
Could just make it return nothing if there is no title

**Comment by olig89** [comment]
I'd also be keen for adding the title to the options - I'm using it for vod downloads so the titles should be settled by then.

**Comment by MrBrax** [comment]
just pushed an update to develop branch for this, you can try it out by switching

**Comment by olig89** [comment]
Adding the title works for me on the files it produces.

FYI it doesn't _look_ like it works in the automated preview, for me {title} still shows as {title} rather than your example text, even though the underlying functionality is good.
