### ISSUE TITLE
[Feature] Call Webhook after stream ends

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#431]
Would be great if this can be added, that after a stream has ended a Webhook is called. 
For those using a Media Server Like plex or emby. So Autoscan cann be called and save resources.

**Comment by MrBrax** [comment]
unless it's been broken since implementation this already exists, but docs are outdated. the webhook url config option is the one to configure for this

**Comment by Serph91P** [comment]
> unless it's been broken since implementation this already exists, but docs are outdated. the webhook url config option is the one to configure for this

ok thats great, what information are send?
Because if I setup the webhook to be this ULR: http://autoscan:3030/triggers/manual?dir=%2Fdata%2Fmedia%2Ftwitch_vods_download%2Fvods

Will it send it via POST and file info or what is send?

**Comment by Serph91P** [comment]
I guess you need to set in notification websocket? Kinda confusing because its calles Webhook. Also would be great to have the notifcation option after transcode finishes if possible. Thanks.

**Comment by MrBrax** [comment]
webhooks are kinda separate from notifications as they're sent regardless of notification category settings, the filtering has to be done on the receiving end. transcoding event should be sent also as 'end_convert'

**Comment by Serph91P** [comment]
> webhooks are kinda separate from notifications as they're sent regardless of notification category settings, the filtering has to be done on the receiving end. transcoding event should be sent also as 'end_convert'

Hmm thats too bad, autoscan, as far as I understand requires specific Information to be called.
https://github.com/Cloudbox/autoscan#manual

**Comment by MrBrax** [comment]
they're really two different things, that one is more like calling a set url every time or programatically, this is a webhook that sends everything to one script that's supposed to handle it depending on the data

**Comment by Serph91P** [comment]
> they're really two different things, that one is more like calling a set url every time or programatically, this is a webhook that sends everything to one script that's supposed to handle it depending on the data

Got it Working, my webhook url was wrong.
