### ISSUE TITLE
Confusion between Capture/VOD/Manual VOD download settings

### ISSUE THREAD

**Issue by olig89** [MrBrax/LiveStreamDVR#432]
I'm having trouble working out which settings relate to which functionality - it could also just be my understanding of terminology.

Goal: to have streams download once a streamer has finished, with the correct naming scheme & folder structure.

Settings I am trying to use:

- In `Settings > Config > Video`, I've set the Vod file+folder settings to do what I want
- In `Settings > Config > Storage`, I've ticked channel folders & VOD folders (dont know if this is relevant)
- In the streamer's channel settings, I've disabled stream capture, and enabled "download VOD at end of stream"

What happens:

- The stream is downloaded as expected after stream is concluded but the file is in the root folder and with a generic name, e.g. `[streamerID]_2023-04-23T21-23-54Z_46812074828.mp4` - ignoring the VOD settings

note - before I disabled stream capture, when a recording finished it _would_ follow the file+folder settings I set for VOD downloads.

Any help would be appreciated, all the systems seem to work great individually for what I want, just having trouble combining & automating.

**Comment by olig89** [comment]
Currently saves mp4 & json to `vods/[streamerID]/` pretty reliably.

Is this something that could be achieved with the exporter, similar to a radarr/sonarr?

**Comment by olig89** [comment]
Well my use-case/need is for a streamer DVR catch-up for narrative-based gaming streamers - pretty mild content, nothing that would be ever deleted/muted by twitch. It's currently just loading up a Plex library so I can watch them back in my own time/during travel, manually sorting the downloaded files atm and working well.

My assumption was that capturing/remuxing/whatever would use more CPU than just downloading the finished VOD

**Comment by MrBrax** [comment]
considering it's being spread out over a longer time it probably uses more yes

i wonder if it's somehow saving even without the vod folder being created, which is pretty weird. it should just fail completely

**Comment by olig89** [comment]
So I had it test overnight;

- Captures are following the Vod file+directory rules in `Settings > Config > Video`
- VODs (auto-downloads after stream has finished) are going to the parent folder like I showed previously

If it's a pain to fix/intended functionality, I guess the title for those fields in the UI should be changed to something that better reflects that it's about the captures rather than downloaded VODs.

**Comment by MrBrax** [comment]
i'm really really rusty right now so if this works i'll be surprised

**Comment by olig89** [comment]
It works! Not so rusty after all, thanks for the effort :)
