### ISSUE TITLE
[Question] pushover config

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#439]
How would you go about configuring pushover. Pushover has a user key and an API key. LSDVR requires a pushover token and pushover user. What is to be entered here?

Thank you in advance.

**Comment by MrBrax** [comment]
user key should probably be the user field, and api key the token

**Comment by Serph91P** [comment]
> user key should probably be the user field, and api key the token

Yep that was it. Thank you.
