### ISSUE TITLE
Websockets are only for authenticated users

### ISSUE THREAD

**Issue by Silergo** [MrBrax/LiveStreamDVR#440]
When I set password in Interface setting websocket disconnected with "Websockets are only for authenticated users" message. But without password it connected fine. How can I sent password to websocket or at least hide server from internet?

**Comment by MrBrax** [comment]
i can't reproduce this, seems to work fine for me. do you maybe have a weirdly configured reverse proxy or something?

**Comment by MrBrax** [comment]
i'm using double with both nginx and caddy, they're really nothing more than the very basics

**Comment by Silergo** [comment]
Alright, the problem was in address. When I login through web address like _https://example.com_ everything works fine, but when I login through local address like _http://192.xxx.xxx.xxx_ it give me message "Websockets are only for authenticated users"

**Comment by Silergo** [comment]
> hmm, i wonder if it's because the connection address is different

I think it because websockets using https and not http.
