### ISSUE TITLE
Container crashes when access deleted channel

### ISSUE THREAD

**Issue by luckiestone** [MrBrax/LiveStreamDVR#449]
When delete one channel the address in the browser stays the same with channel id. If refresh this page, container will crash when re-access this deleted channel.
Auto redirecting to `example.com/settings/channels` once a channel is deleted may solve this issue?

**Comment by MrBrax** [comment]
do you mean accessing it on the channel edit/update page? do you have the stack trace from the console log?

**Comment by luckiestone** [comment]
> 

Yes, and I tried just now but didn't reproduce this time, don't know if it's related to vods, I cleared every channel and readded them before.

**Comment by MrBrax** [comment]
it really has to be triggered by something else, there's nothing that access anything volatile in the settings fetch from what i can see 🤔
