### ISSUE TITLE
Pushover Notifications

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#452]
They show "{{0}} is online" and stuff. I think we had this before.

**Comment by Serph91P** [comment]
But only sometimes, some are working correct.

**Comment by MrBrax** [comment]
is this on the main branch? did i really push the broken version?

**Comment by Serph91P** [comment]
> is this on the main branch? did i really push the broken version?

Yep this is on main. The live notification is the one showing {{0}}. The rest seems to be working fine.

**Comment by MrBrax** [comment]
ok i think all messages should be changed now, it's building main
