### ISSUE TITLE
Streamer Poster

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#453]
Could this be implemented again, that the poster is downloaded automatically again. It was done because some of the streamers i have added have this and some dont.

**Comment by MrBrax** [comment]
i'm not sure what you mean by poster, the user avatar or game posters?

**Comment by Serph91P** [comment]
> i'm not sure what you mean by poster, the user avatar or game posters/covers?

The user poster, this is so that Plex or any other media server can show the poster.
![Screenshot_20230707-201920](https://github.com/MrBrax/LiveStreamDVR/assets/8904984/51c68a9f-e8a7-4eda-9397-5d6e7eb68420)

**Comment by MrBrax** [comment]
oooh yeah those things, totally forgot it had a downloader too

**Comment by MrBrax** [comment]
it does seem like the poster is copied automatically from the avatar in cache on boot, is it copying an empty file or something?

**Comment by Serph91P** [comment]
> it does seem like the poster is copied automatically from the avatar in cache on boot, is it copying an empty file or something?

Nope the newer added ones don't have them at all no files. Set it up on my VPS as well. There are none downloaded at all.

**Comment by MrBrax** [comment]
is the avatar cached locally? and is the filename written into the nfo file?
