### ISSUE TITLE
Trying to open the logs via the UI causes a 400

### ISSUE THREAD

**Issue by Nincodedo** [MrBrax/LiveStreamDVR#459]
Running Server 1.6.1, Client 2.3.4 in Docker. Clicking on the Logs box at the bottom of the UI causes a 400 error.

`2023-08-28 00:22:20 livestreamdvr  | 2023-08-28T05:22:20.371Z | http.api <error> API error 400 returned: {"status":"ERROR","message":"query() may not be used without the json option being set to true"}`

**Comment by MrBrax** [comment]
it does yes, don't know if it was a bad idea switching to a real log provider because their searching is broken
