### ISSUE TITLE
Fetching vod list from Video Download no results occur

### ISSUE THREAD

**Issue by feavle** [MrBrax/LiveStreamDVR#462]
Hi,

Unsure of how long this has been happening but when you go to a channel, click on video download, then click on fetch video list a loading prompt appears for about a second then disappears. Turning on developer logs just shows this:

`172.70.254.223 - - [08/Sep/2023:01:19:00 +0000] "GET /api/v0/twitchapi/videos/ HTTP/1.1" 404 219 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"`

**Comment by MrBrax** [comment]
there's seemingly no channel id passed to the url, could you maybe check the browser dev tools console as you do all this and check for any errors?

**Comment by MrBrax** [comment]
i just realised why this was happening, i pushed an update to dev that's building
