### ISSUE TITLE
Feature Request: Add Game to json not stream title

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#474]
The title describes it basically, would be great to change a setting or something so the games are setup as chapters not the Stream Titel. Like this it is quite hard to know what the chapter is about: 
<img width="627" alt="grafik" src="https://github.com/MrBrax/LiveStreamDVR/assets/8904984/8b17fc46-06f3-4137-a27c-f4740e07767b">

**Comment by MrBrax** [comment]
new option under video on dev, but new major version can really break things

**Comment by Serph91P** [comment]
> new option under video on dev, but new major version can really break things

saw the new feature for the chapters. Thanks for that. 

What is the split folder path and name and where does one enable or disable?

**Comment by MrBrax** [comment]
> What is the split folder path and name and where does one enable or disable?

which one are you referring to? templating?

**Comment by Serph91P** [comment]
> > What is the split folder path and name and where does one enable or disable?
> 
> which one are you referring to? templating?

those two. The splitting how is it enabled or disabled?
<img width="713" alt="grafik" src="https://github.com/MrBrax/LiveStreamDVR/assets/8904984/14119a3f-ede4-4fca-9000-9a0ed28e3979">

**Comment by MrBrax** [comment]
as of now, it is only done when you click the split button in the expanded vod controls

**Comment by Serph91P** [comment]
> as of now, it is only done when you click the split button in the expanded vod controls

ah ok thanks for clarifying. Closed
