### ISSUE TITLE
Can't add two Twitch channels

### ISSUE THREAD

**Issue by JoaoZanetti** [MrBrax/LiveStreamDVR#478]
Brand new Docker installation using master image.
For some reason after I add one Twitch channel, I can't add more channels.
```
2023-11-18T20:03:33.870Z | route.channels.add <error> Failed to create channel: Error: Channel phasiot1 already exists in config
2023-11-18T20:03:33.871Z | http.api <error> API error 400 returned: {"status":"ERROR","message":"Channel phasiot1 already exists in config"}
```
![image](https://github.com/MrBrax/LiveStreamDVR/assets/18476803/e2fd12c2-5e0f-4e84-a678-b013c30de720)
![image](https://github.com/MrBrax/LiveStreamDVR/assets/18476803/ec7f0e0d-4e9d-435d-b370-0ad73c451cab)

**Comment by JoaoZanetti** [comment]
Maybe I found the problem.  [TwitchChannels.ts](https://github.com/MrBrax/LiveStreamDVR/blob/dde7cdc491fda3d2626376868da67c1d46ca6dc6/server/src/Core/Providers/Twitch/TwitchChannel.ts#L1829C8-L1840C1) is trying to compare **ch.login** with **config.login**, login field is deprecated, so both of them are null and this will return a false true validation.

`const exists_config = LiveStreamDVR.getInstance().channels_config.find(
            (ch) =>
                ch.provider == "twitch" &&
                (ch.login === config.login ||
                    ch.internalName === config.login ||
                    ch.internalName === config.internalName)
        );
        if (exists_config)
            throw new Error(
                `Channel ${config.internalName} already exists in config`
            );`
![image](https://github.com/MrBrax/LiveStreamDVR/assets/18476803/a7239b3d-f58d-4441-ac5e-9900829ea979)

**Comment by MrBrax** [comment]
good call, pushed an update with some reworked logic

**Comment by JoaoZanetti** [comment]
> good call, pushed an update with some reworked logic

I just updated to the latest version, It's working now! Thanks.
