### ISSUE TITLE
Problem with null framerate

### ISSUE THREAD

**Issue by JoaoZanetti** [MrBrax/LiveStreamDVR#480]
For some reason, some streams have a null framerate, and this null framerate is translated as NaN when trying to render the chat, making TwitchDownloader throw '_Option 'framerate' is defined with a bad format._'.

![Screenshot 2023-11-20 091208](https://github.com/MrBrax/LiveStreamDVR/assets/18476803/7f37b43c-8b59-491e-b83b-58b1b7a30947)
![Screenshot 2023-11-20 091228](https://github.com/MrBrax/LiveStreamDVR/assets/18476803/4ea8ce3f-6e74-4802-9c15-e642b1540eda)
![image](https://github.com/MrBrax/LiveStreamDVR/assets/18476803/e04582ac-0b8f-4f45-a87e-8134046fc78c)

**Comment by MrBrax** [comment]
could you try and find the mediainfo cache file in `/cache/mediainfo/*.json` and check what the various frame rate fields are set to?

**Comment by JoaoZanetti** [comment]
Activating the remux option in config fixes the problem. Thanks!
