### ISSUE TITLE
[Error] if there are too many VODs in the list, the recording does not work

### ISSUE THREAD

**Issue by devpanda0** [MrBrax/LiveStreamDVR#485]
if about 170 VODs in the list, recording no longer works properly.

**Comment by MrBrax** [comment]
what is "not properly"? does it just cut out or not at all? any logs when it happens?

**Comment by devpanda0** [comment]
He wants to start recording, but then stops and doesn't say what's wrong. It just doesn't work anymore

**Comment by devpanda0** [comment]
and since yesterday I have this problem that the stream just stops for no reason. I have not changed anything on the system

![image](https://github.com/MrBrax/LiveStreamDVR/assets/49129501/0e7233d5-1379-4753-bc64-323ad270257e)

**Comment by MrBrax** [comment]
can you check the capture logs in the data/logs/software directory?

**Comment by MrBrax** [comment]
i've updated streamlink, it could be the issue along with #486

**Comment by devpanda0** [comment]
Thanks, had already seen it and directly pulled it from docker but unfortunately no success

**Comment by MrBrax** [comment]
i feel like it must either be a streamlink error or your network connection, but i guess it could also be some kind of system stall. does it use up 100% cpu?

**Comment by devpanda0** [comment]
The CPU chills its life with 10% maximum load
I have check it and i have no network problems

**Comment by MrBrax** [comment]
i mistakenly set the new queue threshold to disable itself at 0, you could try raising it to a higher number as well as the stream timeout, if it's at all related to #486

**Comment by devpanda0** [comment]
okay, i try it with the new build :)

**Comment by devpanda0** [comment]
okay, doesn't stop more but is come this error and he record only in 360p but i have choose best and 360p is not the best xD

![image](https://github.com/MrBrax/LiveStreamDVR/assets/49129501/f2c10f0c-5d9b-43af-a9ed-e31acc0ec7f3)

**Comment by MrBrax** [comment]
you're gonna have to check the logs for all of these things, seems to be an unique error for your setup unless someone else reports in too

**Comment by devpanda0** [comment]
I have been using the tool for almost 2 years now and the problems started after an update. I just can't remember exactly which one. I can reinstall the recorder, but this didn't help last time

[LiveStreamDVR-2024-01-15.log](https://github.com/MrBrax/LiveStreamDVR/files/13937486/LiveStreamDVR-2024-01-15.log)
[capture_pnation_42217575609_stdout.log](https://github.com/MrBrax/LiveStreamDVR/files/13937487/capture_pnation_42217575609_stdout.log)

**Comment by devpanda0** [comment]
In what way do you mean ratelimit? From Twitch?

**Comment by MrBrax** [comment]
preventing abuse by too many requests from twitch yes, i tried running the same command and it seems to capture just fine

**Comment by devpanda0** [comment]
Okay, it worked fine for me for about 10 minutes, then it stopped (error). I only record one streamer and the server also has an IP for itself.

**Comment by MrBrax** [comment]
it's going on for 23 minutes for me so far, no problems. i feel like it must be on your end somehow. could your country be rate limiting too?

**Comment by devpanda0** [comment]
I am Germany and so is the server. I don't know that we have a limit on Twitch. It's been running for almost the last 2 years and we've accumulated 16 TB of VOD material

**Comment by MrBrax** [comment]
In that case I'm out of ideas for now, I'm guessing it's more of a streamlink problem, and that can happen if twitch changes something, being a coincidence.

**Comment by devpanda0** [comment]
Okay, I'll now set up a second instance of the recorder and test it with a different IP

**Comment by MrBrax** [comment]
I am getting the `[stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.` error on this test capture intermittently but that's probably just the ads. Try it with a vpn to another country if you can.

**Comment by devpanda0** [comment]
VPN is on Linux server not so easy :(

**Comment by Serph91P** [comment]
> VPN is on Linux server not so easy :(

since you are using docker you can use something like gluetun and connect this docker through gluetun and let it use the vpn connection from it.

**Comment by devpanda0** [comment]
But that can't be THE solution. There must be another way. I don't want to spend money on a VPN service now.

**Comment by MrBrax** [comment]
if the proxy is having issues then so will you

**Comment by MrBrax** [comment]
it could be an isp issue that's blocking things or just functioning incorrectly, using a public dns could help with that. it being the `video-weaver.waw02.hls.ttvnw.net` address which probably is just a common cdn url it shouldn't have a problem

**Comment by Serph91P** [comment]
> it could be an isp issue that's blocking things or just functioning incorrectly, using a public dns could help with that. it being the `video-weaver.waw02.hls.ttvnw.net` address which probably is just a common cdn url it shouldn't have a problem

hmmm true.

@devpanda0 where is your server hosted?

**Comment by devpanda0** [comment]
@Serph91P ActiveServers - Interwerk https://active-servers.com/

**Comment by devpanda0** [comment]
> video-weaver.waw02.hls.ttvnw.net

I always use the dns from Cloudflare

**Comment by Serph91P** [comment]
> @Serph91P ActiveServers - Interwerk https://active-servers.com/

never heard of them but does not mean they are bad. Cannot find anything out of the ordinary from them.
What server hardware did you rent?

**Comment by devpanda0** [comment]
I have a BareMetal server there (i9-7920X, 128 GB memory, 250 Gb nvme systemplate, 2x 2TB nvme for VM space, 4x 16 TB HDD for VOD space and OS Proxmox) I've been with them for over 4 years now, no problems. I don't think it has anything to do with the IP or the server

**Comment by Serph91P** [comment]
> I have a BareMetal server there (i9-7920X, 128 GB memory, 250 Gb nvme systemplate, 2x 2TB nvme for VM space, 4x 16 TB HDD for VOD space and OS Proxmox) I've been with them for over 4 years now, no problems. I don't think it has anything to do with the IP or the server

how many streamer do you have subscribed to?

**Comment by devpanda0** [comment]
one

**Comment by Serph91P** [comment]
> one

yeah then @MrBrax got it right something is definetly blocking or throttling. What reverse proxy are you using because this is the only thing I can think of what could come from your end and block or throttle.

**Comment by devpanda0** [comment]
I use nginx as a reverse proxy

**Comment by MrBrax** [comment]
reverse proxy wouldn't block anything as that's on the inverse, but is the ttv lol plugin active, or any other kind of proxy?

**Comment by Serph91P** [comment]
> reverse proxy wouldn't block anything as that's on the inverse, but is the ttv lol plugin active, or any other kind of proxy?

Some reverse proxy can have some kind of firewall etc so they can def block stuff.

**Comment by MrBrax** [comment]
> > reverse proxy wouldn't block anything as that's on the inverse, but is the ttv lol plugin active, or any other kind of proxy?
> 
> Some reverse proxy can have some kind of firewall etc so they can def block stuff.

the reverse proxy only handles incoming traffic, the software inside your nat can use any socket and port to communicate outwards

**Comment by devpanda0** [comment]
I still use an opnSense firewall but I allow port 80 and 443 to the server for the Nginx webserver.

I can try it again without the firewall but it didn't cause any problems either

I tried my Twitch bot on the server and it has no problem communicating with Twitch using the IP

**Comment by MrBrax** [comment]
a regular bot probably wouldn't be affected as it doesn't fetch video content, but if you have a firewall that *might* affect things i suppose?

**Comment by devpanda0** [comment]
It worked for 2 years with the firewall. Nothing was changed in the firewall. So I think no, it doesn't affect it

**Comment by MrBrax** [comment]
twitch might have changed things. when you use external services, anything can change at any time. with an issue as odd as this, you gotta expect anything.

**Comment by devpanda0** [comment]
So do I really have to get a VPN or a new IP address for this?

**Comment by MrBrax** [comment]
ci is currently building a new version with streamlink updated, they released something two days ago, might be worth trying out later. but anything that changes the network would be closer, like external firewall changes, internal firewall, dns, ip address, geolocation, abuse blacklist checks

**Comment by devpanda0** [comment]
It has now recorded for 2:30 minutes but then stopped again. But the resolution is right again.

**Comment by devpanda0** [comment]
Is it possible for you to activate the debug log from the stream link? That's enough in the develop branch

**Comment by MrBrax** [comment]
if you enable debug mode in settings it should use the default debug mode in streamlink too

**Comment by devpanda0** [comment]
okay, thx. 
Could this also have something to do with it? When I call up the URL myself, I get the following answer: "No data supplied"
![image](https://github.com/MrBrax/LiveStreamDVR/assets/49129501/e3ed36ab-638e-4359-aa0a-07a253e7b000)

**Comment by MrBrax** [comment]
no, that's fine. internal communication should work fine

**Comment by devpanda0** [comment]
What can we do now?

**Comment by MrBrax** [comment]
if neither a dns, ip, or vpn location change works, and the same streamlink capture launched either in the docker container or on the same machine and getting the same error, you'd have to contact streamlink authors/making an issue there

**Comment by devpanda0** [comment]
problem solved. IP change was the solution

**Comment by MrBrax** [comment]
very cursed and unfortunate problem, might be worth contacting the isp or host about

**Comment by devpanda0** [comment]
thanks for your help and perseverance with the problem

**Comment by devpanda0** [comment]
Why come this always? 
![image](https://github.com/MrBrax/LiveStreamDVR/assets/49129501/f294c3c7-993c-45ef-8cd1-9cabc1799ec9)

**Comment by MrBrax** [comment]
i made it as a warning for me if a capture fails and a huge ts capture file gets left behind, you can see it and move it out of there since it doesn't appear in the ui. mine would take up hundreds of gigs and i'd wonder what was using space.

**Comment by MrBrax** [comment]
are those vods being captured right now? otherwise it's just a file that will do nothing in there

**Comment by devpanda0** [comment]
Yes, he is currently recording

**Comment by MrBrax** [comment]
then i'll make it so it doesn't show when recording, the feature itself wouldn't be intrusive

**Comment by devpanda0** [comment]
Thanks, that would be nice if it's not there during the recording
