### ISSUE TITLE
mkv file does not work with editor

### ISSUE THREAD

**Issue by devpanda0** [MrBrax/LiveStreamDVR#492]
mkv file does not work with editor. only with mp4? 

![image](https://github.com/MrBrax/LiveStreamDVR/assets/49129501/1b428d11-2f49-4728-815e-7051eccdb3db)

**Comment by MrBrax** [comment]
that would indeed not work, an oversight by me. i don't think browsers support mkv still so it wouldn't be able to play it anyway
