### ISSUE TITLE
Subfolder support for file exporter

### ISSUE THREAD

**Issue by 0x1f415** [MrBrax/LiveStreamDVR#494]
**Is your feature request related to a problem? Please describe.**
since I abandoned my old ticket #444 and decided to use the file exporter as an alternative, I've noticed that the file exporter strips slashes from the title template meaning the external folder needs to be a flat folder structure.

my default title template is:

```
{internalName}/{year}-{month}/[{date}] {internalName} - {title}
```

to attempt to create a show-like structure to be hosted by Jellyfin.

you can see slashes in the export menu that seem to imply that this would work:

![image](https://github.com/MrBrax/LiveStreamDVR/assets/6064300/84a70c80-637f-4177-b05b-1cada5012124)

but the exported file ends up in the root directory, taking on the entire title stripped of slashes:

![image](https://github.com/MrBrax/LiveStreamDVR/assets/6064300/58f1b0e3-c244-4936-ac72-8e958f3f1bd7)

also in case it wasn't clear I intend to use the auto exporter normally rather than manually exporting each file, but am using the manual export for this example - assuming they follow the same code path

possibly related: #472

**Describe the solution you'd like**
file exporter allows the user to use slashes to define a folder hierarchy of exported files.

**Describe alternatives you've considered**
this is the alternative to pointing jellyfin directly at the vods directory. that approach allowed jellyfin to read series/season/episode info from the folder hierarchy but stopped working eventually as the server would crash from attempting to read over 100 vods from its storage directory, as well as the UI becoming cluttered.

**Additional context**
S1.7.2.1/C2.4.2, running in docker on unraid

**Comment by MrBrax** [comment]
wonder if it's sane at all to just remove the sanitization checks, it's for security but on the other hand i'm not sure what it would even prevent

**Comment by MrBrax** [comment]
the default directory config option is now a template field and should be parsed in the suitable exporters
