### ISSUE TITLE
Limit of Subscriptions ? Twitch Auth issue ?

### ISSUE THREAD

**Issue by Pinso2727** [MrBrax/LiveStreamDVR#495]
**Describe the bug**
Hello, 

Here's my problem, when subscribing, it works but only for 3/4 channels maximum, whereas I've added several, I've tried to remove them to re-add them but the problem persists.

See the screen below but I think I have an authentication problem with Twitch, when I enter the links I get error messages. I don't think there's much missing to make it work.

My goal is to have Subscription on all the channels I add.

**Screenshots**
![Capture d'écran 2024-02-13 123601](https://github.com/MrBrax/LiveStreamDVR/assets/101926076/eb0ed743-dbe3-4697-9497-f7297741d082)

![Capture  d'écran 2024-02-13 123928](https://github.com/MrBrax/LiveStreamDVR/assets/101926076/feb6b220-f16e-4231-8c1b-c66e02c61b2a)

![Ca111pture d'écran 2024-02-13 124123](https://github.com/MrBrax/LiveStreamDVR/assets/101926076/8774a492-28d6-4505-9df4-e86583661ca0)

![Capture d'écran 2024-02-13 12ffff4431](https://github.com/MrBrax/LiveStreamDVR/assets/101926076/dd51a40f-d066-4bda-b5cc-52aaed693540)

![Capture d'écran 202dddd4-02-13 124548](https://github.com/MrBrax/LiveStreamDVR/assets/101926076/7fc46392-e51d-4af5-be77-a43dbb57237f)

**Server:**
 - Docker (Unraid)
 -  NPM
 - OVH Domain

**Comment by MrBrax** [comment]
user/websocket auth type has a limit of 10 subs or so

**Comment by Pinso2727** [comment]
> user/websocket auth type has a limit of 10 subs or so

@MrBrax 

ohh ok, so should I switch to another type? app/user and webhook/websocket? or whatever combination we're limited to 10?

**Comment by MrBrax** [comment]
app + webhook is the default yes
