### ISSUE TITLE
Streamlink not found/  can't change Streamlink PATH from settings

### ISSUE THREAD

**Issue by 111100001** [MrBrax/LiveStreamDVR#497]
**Describe the bug**
i'm getting this error : Failed to find streamlink
 i looked in the settings to see if i can give it the path myself (using the command which stremlink it gave me : /home/rebyc/.local/bin/streamlink)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please attach logs for both the main server and capture if applicable, can be found in `data/logs/` and `data/logs/software/` respectively.
Please also use code tags and try to keep line breaks if possible.

**Server:**
 - OS or Docker: [e.g. Debian]

**Additional context**

**Comment by 111100001** [comment]
it looks like it is installing streamlink in /home/rebyc/.local/bin/streamlink
while this webapp is looking for it in /usr/bin/python3/streamlink 

i cant symlink it or make pip install in system-wide path

**Comment by 111100001** [comment]
i'm also using linux wsl2 sorry forgot to say

**Comment by 111100001** [comment]
solved the issue by creating a venv and adding that to the settings

**Comment by MrBrax** [comment]
you can change the python directory in settings, but i would just recommend using docker instead. venv would work too yes.
