### ISSUE TITLE
No stream found

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#499]
**Describe the bug**
No stream is being recorded or notified when online. Force record a online stream returns "no stream found"

**To Reproduce**
Have the latest docker version installed.

**Expected behavior**
Streams are being recorded when a streamer goes live.

**Screenshots**
![grafik](https://github.com/MrBrax/LiveStreamDVR/assets/8904984/057843d3-5219-48db-800c-400233832fd0)

**Logs**
```
2024-02-28 19:53:52	tw.channel.getStreams	error	Could not get streams for 73437396: getaddrinfo EAI_AGAIN api.twitch.tv
2024-02-28 19:53:52	http.api	error	API error 400 returned: {"status":"ERROR","message":"No streams found"}
```

**Server:**
 - Docker on Ubuntu 22.04

**Comment by MrBrax** [comment]
something with your networking is wrong, probably dns

**Comment by Serph91P** [comment]
> something with your networking is wrong, probably dns

Hmm the only thing changed is the firewall. So dunno what is wrong there will have to check. Because other containers work just fine.

**Comment by MrBrax** [comment]
firewall could also be routing things wrong. someone else had this issue before

**Comment by Serph91P** [comment]
> firewall could also be routing things wrong. someone else had this issue before

fixed thank you.
