### ISSUE TITLE
Failed to find streamlink

### ISSUE THREAD

**Issue by cha1r** [MrBrax/LiveStreamDVR#503]
Hello, I cannot seem to find how I provide the path for the streamlink binary. 

Under the config section, I navigate to binaries, and  the option to link streamlink is not listed.

I have streamlink installed and am running Version: 6.7.1

**Comment by MrBrax** [comment]
streamlink is a python binary and should be provided in the "python binary directory" option

**Comment by cha1r** [comment]
thank you, i got that working!

if i could bother you with one final question here instead of opening a new issue.

is it possible to download the VOD version of the player? i have the VOD i've downloaded set with the chat at the perfect size + settings with a gradient, but I cant seem to download it. do i have to use the burn option in order merge the chat and the VOD? the later option works, but it doesnt have as much customization as the player, and i'd like to be able to include the gradient and settings into my exported final VOD.

**Comment by MrBrax** [comment]
the vod player can only play video+chat, you'd have to use something like obs to capture the browser in real time to a final output video
