### ISSUE TITLE
the bottom right says Disconnected and (is not subscribed to stream.online. Please check the config and subscribe.)

### ISSUE THREAD

**Issue by 111100001** [MrBrax/LiveStreamDVR#512]
i have everything set up. I have an https set up and accessible. i set up the twitch extension Client ID and twitch secret and connected to it. 

but i still have the errors: 

![image](https://github.com/MrBrax/LiveStreamDVR/assets/24229327/f027612e-a81a-4d1e-9fc8-f37637e6b035)

and still says Disconnected :

![image](https://github.com/MrBrax/LiveStreamDVR/assets/24229327/3d1e8c06-ffa8-4f00-9253-1995a89d5675)

**Comment by MrBrax** [comment]
disconnected means that the websocket isn't set up correctly, it's just used for live updates in the gui.

i'm guessing something is wrong with your reverse proxy for the webhooks to not subscribe

**Comment by 111100001** [comment]
thank you! 
after some digging, i fixed it by adding this to the reverse proxy conf file: 

```
  proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
```
