### ISSUE TITLE
Stream does not get updated correclty

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/LiveStreamDVR#517]
**Describe the bug**
Streamer changes category to something does not matter. Streamer goes offline.
Streamer goes online again. Category does not get updated. And Category or stream is kinda continued?

**To Reproduce**
Streamer changes category to something does not matter. Streamer goes offline.
Streamer goes online again. Category does not get updated. And Category or stream is kinda continued?

**Expected behavior**
Category and streamer state gets correctly updated

**Screenshots**

![image](https://github.com/user-attachments/assets/95e8b520-6886-429d-b252-bb7e8302218e)
![image](https://github.com/user-attachments/assets/85eecfd9-a360-48f7-bed2-f1096e157e74)

**Logs**
Please attach logs for both the main server and capture if applicable, can be found in `data/logs/` and `data/logs/software/` respectively.
Please also use code tags and try to keep line breaks if possible.

**Server:**
 - Docker.

**Additional context**
if you kill the recording and delte everthing from that streamer and force the recording it gets updated again.

**Comment by MrBrax** [comment]
does it never update the game/title? are you missing the update webhook subscription for that streamer?

**Comment by Serph91P** [comment]
> does it never update the game/title? are you missing the update webhook subscription for that streamer?

No never updated. But how am I missing suddenly the update webhook subscription.

**Comment by MrBrax** [comment]
it has happened to me before without reason, it didn't appear in the subscriptions list

**Comment by Serph91P** [comment]
> it has happened to me before without reason, it didn't appear in the subscriptions list

ok thansk, fixed.
